pluginManagement {
    repositories {
        maven {
            url = "https://repo.repsy.io/mvn/jixxed/maven/"
        }
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
        gradlePluginPortal()
        mavenLocal()
        maven {
            name 'nexus'
            url "https://nexus.jixxed.nl/content/repositories/releases/"
            credentials {
                username = System.getenv('NEXUS_REPO_USER')
                password = System.getenv('NEXUS_REPO_PASS')
            }
        }
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = 'EDOMH'
include 'bootstrap'
include 'application'
