package nl.jixxed.eliteodysseymaterials.service.eddn;

import nl.jixxed.eliteodysseymaterials.enums.Expansion;
import nl.jixxed.eliteodysseymaterials.schemas.eddn.carrierjump.*;
import nl.jixxed.eliteodysseymaterials.schemas.journal.CarrierJump.CarrierJump;

public class EDDNCarrierJumpMapper extends EDDNMapper {
    public static Message mapToEDDN(final CarrierJump carrierJump, final Expansion expansion) {
        return new Message.MessageBuilder()
                .withTimestamp(carrierJump.getTimestamp())
                .withEvent(carrierJump.getEvent())
                .withStarPos(carrierJump.getStarPos())
                .withStarSystem(carrierJump.getStarSystem())
                .withSystemAddress(carrierJump.getSystemAddress())
                .withHorizons(expansion.equals(Expansion.HORIZONS) || expansion.equals(Expansion.ODYSSEY))
                .withOdyssey(expansion.equals(Expansion.ODYSSEY))
                .withBodyID(carrierJump.getBodyID())
                .withBody(carrierJump.getBody())
                .withBodyType(carrierJump.getBodyType())
                .withMarketID(carrierJump.getMarketID())
                .withDocked(carrierJump.getDocked())
                .withTaxi(carrierJump.getTaxi().orElse(null))
                .withMulticrew(carrierJump.getMulticrew().orElse(null))
                .withPopulation(carrierJump.getPopulation())
                .withPowerplayState(carrierJump.getPowerplayState().orElse(""))
                .withPowers(carrierJump.getPowers().orElse(null))
                .withStationEconomies(carrierJump.getStationEconomies().stream()
                                .map(stationEconomy -> new StationEconomy.StationEconomyBuilder()
                                        .withName(stationEconomy.getName())
                                        .withProportion(stationEconomy.getProportion())
                                        .build())
                                .toList())
                .withStationEconomy(carrierJump.getStationEconomy())
                .withStationFaction(new SystemFaction.SystemFactionBuilder()
                        .withName(carrierJump.getStationFaction().getName())
                        .build())
                .withStationGovernment(carrierJump.getStationGovernment())
                .withStationName(carrierJump.getStationName())
                .withStationServices(carrierJump.getStationServices())
                .withStationType(carrierJump.getStationType())
                .withSystemEconomy(carrierJump.getSystemEconomy())
                .withSystemAllegiance(carrierJump.getSystemAllegiance())
                .withSystemFaction(carrierJump.getSystemFaction()
                        .map(faction -> new SystemFaction.SystemFactionBuilder()
                                .withName(faction.getName())
                                .withFactionState(faction.getFactionState().orElse(null))
                                .build())
                        .orElse(null))
                .withSystemGovernment(carrierJump.getSystemGovernment())
                .withSystemSecondEconomy(carrierJump.getSystemSecondEconomy())
                .withSystemSecurity(carrierJump.getSystemSecurity())
                .withFactions(carrierJump.getFactions().map(factions -> factions.stream()
                        .map(faction -> new Faction.FactionBuilder()
                                .withName(faction.getName())
                                .withFactionState(faction.getFactionState())
                                .withAllegiance(faction.getAllegiance())
                                .withGovernment(faction.getGovernment())
                                .withHappiness(faction.getHappiness())
                                .withInfluence(faction.getInfluence())
                                .withActiveStates(faction.getActiveStates()
                                        .map(activeStates -> activeStates.stream()
                                                .map(activeState -> new ActiveState.ActiveStateBuilder().withState(activeState.getState()).build())
                                                .toList())
                                        .orElse(null))
                                .withPendingStates(faction.getPendingStates()
                                        .map(pendingStates -> pendingStates.stream()
                                                .map(pendingState -> new PendingState.PendingStateBuilder().withState(pendingState.getState()).build())
                                                .toList())
                                        .orElse(null))
                                .withRecoveringStates(faction.getRecoveringStates()
                                        .map(recoveringStates -> recoveringStates.stream()
                                                .map(recoveringState -> new RecoveringState.RecoveringStateBuilder().withState(recoveringState.getState()).build())
                                                .toList())
                                        .orElse(null))
                                .build())
                        .toList()).orElse(null))
                .withConflicts(carrierJump.getConflicts()
                        .map(conflicts -> conflicts.stream()
                                .map(conflict -> new Conflict.ConflictBuilder()
                                        .withStatus(conflict.getStatus())
                                        .withWarType(conflict.getWarType())
                                        .withFaction1(new ConflictFaction.ConflictFactionBuilder()
                                                .withName(conflict.getFaction1().getName())
                                                .withStake(conflict.getFaction1().getStake())
                                                .withWonDays(conflict.getFaction1().getWonDays())
                                                .build())
                                        .withFaction2(new ConflictFaction.ConflictFactionBuilder()
                                                .withName(conflict.getFaction2().getName())
                                                .withStake(conflict.getFaction2().getStake())
                                                .withWonDays(conflict.getFaction2().getWonDays())
                                                .build())
                                        .build())
                                .toList())
                        .orElse(null))
                .build();
    }
}
