package nl.jixxed.eliteodysseymaterials.trade.message.inbound;

public enum MessageType {
    ENLIST, GETOFFERS, PUBLISHOFFER, DROPOFFERS, XBIDPUSH, XBIDPULL, XBIDACCEPT, XMESSAGE, ONLINEOFFERS, OFFLINEOFFERS, ACCEPTEDOFFERS, DECLINEDOFFERS
}
