module nl.jixxed.eliteodysseymaterials {
    requires jdk.crypto.ec;
    requires javafx.fxml;
    requires transitive javafx.controls;
    requires transitive javafx.media;
    requires javafx.swing;
    requires org.controlsfx.controls;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.datatype.jsr310;
    requires io.reactivex.rxjava3;
    requires java.net.http;
    requires org.jfxtras.styles.jmetro;
    requires org.slf4j;
    requires com.google.common;
    requires java.naming;
    requires jdk.naming.dns;
    requires static lombok;
    requires org.apache.poi.poi;
    requires org.apache.poi.ooxml;
    requires org.apache.poi.ooxml.schemas;
    requires org.apache.commons.csv;
    requires scribejava.core;
    requires org.openpnp;
    requires net.java.dev.jna;
    requires com.sun.jna.platform;
    requires nl.jixxed.tess4j;
    requires nl.jixxed.lept4j;
    requires org.apache.commons.io;
    requires java.desktop;
    opens nl.jixxed.eliteodysseymaterials to javafx.graphics, java.desktop;
    opens nl.jixxed.eliteodysseymaterials.service.message to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.trade.message.outbound to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.trade.message.outbound.payload to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.trade.message.common to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.trade.message.inbound to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.templates to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.destroyables to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials;
    exports nl.jixxed.eliteodysseymaterials.enums;
    exports nl.jixxed.eliteodysseymaterials.domain;
    exports nl.jixxed.eliteodysseymaterials.templates;
    exports nl.jixxed.eliteodysseymaterials.service;
    opens nl.jixxed.eliteodysseymaterials.domain to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.enums to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.templates.components.segmentbar to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.service.ar;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.commodities;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.commodities to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.engineers;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.engineers to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.materials;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.materials to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.wishlist;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.wishlist to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.materials;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.materials to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.loadout;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.loadout to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.engineers;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.engineers to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.wishlist;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.wishlist to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.trade;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.trade to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.components;
    opens nl.jixxed.eliteodysseymaterials.templates.components to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.overlay.ar;
    opens nl.jixxed.eliteodysseymaterials.templates.overlay.ar to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.generic;
    opens nl.jixxed.eliteodysseymaterials.templates.generic to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.settings;
    opens nl.jixxed.eliteodysseymaterials.templates.settings to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.templates.dialog;
    opens nl.jixxed.eliteodysseymaterials.templates.dialog to javafx.fxml, org.controlsfx.controls;
    exports nl.jixxed.eliteodysseymaterials.journalevents;
    opens nl.jixxed.eliteodysseymaterials.journalevents to com.fasterxml.jackson.databind;
    exports nl.jixxed.eliteodysseymaterials.journalevents.AfmuRepairs;
    exports nl.jixxed.eliteodysseymaterials.journalevents.AppliedToSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ApproachBody;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ApproachSettlement;
    exports nl.jixxed.eliteodysseymaterials.journalevents.AsteroidCracked;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Backpack;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BackpackChange;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BookDropship;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BookTaxi;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Bounty;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuyAmmo;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuyDrones;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuyExplorationData;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuyMicroResources;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuySuit;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuyTradeData;
    exports nl.jixxed.eliteodysseymaterials.journalevents.BuyWeapon;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CancelDropship;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CancelTaxi;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CapShipBond;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Cargo;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CargoDepot;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CargoTransfer;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierBankTransfer;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierBuy;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierCancelDecommission;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierCrewServices;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierDecommission;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierDepositFuel;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierDockingPermission;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierFinance;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierJump;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierJumpCancelled;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierJumpRequest;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierModulePack;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierNameChange;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierShipPack;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierStats;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CarrierTradeOrder;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ChangeCrewRole;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ClearImpound;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ClearSavedGame;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CockpitBreached;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CodexEntry;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CollectCargo;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CollectItems;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Commander;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CommitCrime;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoal;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoalDiscard;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoalJoin;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoalReward;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Continued;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CreateSuitLoadout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewAssign;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewFire;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewHire;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewLaunchFighter;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewMemberJoins;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewMemberQuits;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrewMemberRoleChange;
    exports nl.jixxed.eliteodysseymaterials.journalevents.CrimeVictim;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DatalinkScan;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DatalinkVoucher;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DataScanned;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DeleteSuitLoadout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Died;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DisbandedSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DiscoveryScan;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Disembark;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Docked;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockFighter;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockingCancelled;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockingDenied;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockingGranted;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockingRequested;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockingTimeout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DockSRV;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DropItems;
    exports nl.jixxed.eliteodysseymaterials.journalevents.DropshipDeploy;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EjectCargo;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Embark;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EndCrewSession;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EngineerContribution;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EngineerCraft;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EngineerLegacyConvert;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EngineerProgress;
    exports nl.jixxed.eliteodysseymaterials.journalevents.EscapeInterdiction;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FactionKillBond;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FCMaterials;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FetchRemoteModule;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FighterDestroyed;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FighterRebuilt;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Fileheader;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Friends;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FSDJump;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FSDTarget;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FSSAllBodiesFound;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FSSBodySignals;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FSSDiscoveryScan;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FSSSignalDiscovered;
    exports nl.jixxed.eliteodysseymaterials.journalevents.FuelScoop;
    exports nl.jixxed.eliteodysseymaterials.journalevents.HeatDamage;
    exports nl.jixxed.eliteodysseymaterials.journalevents.HeatWarning;
    exports nl.jixxed.eliteodysseymaterials.journalevents.HullDamage;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Interdicted;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Interdiction;
    exports nl.jixxed.eliteodysseymaterials.journalevents.InvitedToSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.JetConeBoost;
    exports nl.jixxed.eliteodysseymaterials.journalevents.JetConeDamage;
    exports nl.jixxed.eliteodysseymaterials.journalevents.JoinACrew;
    exports nl.jixxed.eliteodysseymaterials.journalevents.JoinedSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.KickCrewMember;
    exports nl.jixxed.eliteodysseymaterials.journalevents.KickedFromSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LaunchDrone;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LaunchFighter;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LaunchSRV;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LeaveBody;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LeftSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Liftoff;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LoadGame;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Loadout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LoadoutEquipModule;
    exports nl.jixxed.eliteodysseymaterials.journalevents.LoadoutRemoveModule;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Location;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Market;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MarketBuy;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MarketSell;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MassModuleStore;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MaterialCollected;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MaterialDiscarded;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MaterialDiscovered;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Materials;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MaterialTrade;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MiningRefined;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MissionAbandoned;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MissionAccepted;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MissionCompleted;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MissionFailed;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MissionRedirected;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Missions;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleBuy;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleInfo;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleRetrieve;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleSell;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleSellRemote;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleStore;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ModuleSwap;
    exports nl.jixxed.eliteodysseymaterials.journalevents.MultiSellExplorationData;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Music;
    exports nl.jixxed.eliteodysseymaterials.journalevents.NavBeaconScan;
    exports nl.jixxed.eliteodysseymaterials.journalevents.NavRoute;
    exports nl.jixxed.eliteodysseymaterials.journalevents.NavRouteClear;
    exports nl.jixxed.eliteodysseymaterials.journalevents.NewCommander;
    exports nl.jixxed.eliteodysseymaterials.journalevents.NpcCrewPaidWage;
    exports nl.jixxed.eliteodysseymaterials.journalevents.NpcCrewRank;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Outfitting;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Passengers;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PayBounties;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PayFines;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Powerplay;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayCollect;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayDefect;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayDeliver;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayFastTrack;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayJoin;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayLeave;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplaySalary;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayVote;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PowerplayVoucher;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Progress;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Promotion;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ProspectedAsteroid;
    exports nl.jixxed.eliteodysseymaterials.journalevents.PVPKill;
    exports nl.jixxed.eliteodysseymaterials.journalevents.QuitACrew;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Rank;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RebootRepair;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ReceiveText;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RedeemVoucher;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RefuelAll;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RefuelPartial;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RenameSuitLoadout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Repair;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RepairAll;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RepairDrone;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Reputation;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ReservoirReplenished;
    exports nl.jixxed.eliteodysseymaterials.journalevents.RestockVehicle;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Resupply;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Resurrect;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SAAScanComplete;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SAASignalsFound;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Scan;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ScanBaryCentre;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Scanned;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ScanOrganic;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ScientificResearch;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Screenshot;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SearchAndRescue;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SelfDestruct;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellDrones;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellExplorationData;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellMicroResources;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellOrganicData;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellShipOnRebuy;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellSuit;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SellWeapon;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SendText;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SetUserShipName;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SharedBookmarkToSquadron;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShieldState;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipLocker;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipLockerMaterials;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipTargeted;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Shipyard;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipyardBuy;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipyardNew;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipyardSell;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipyardSwap;
    exports nl.jixxed.eliteodysseymaterials.journalevents.ShipyardTransfer;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Shutdown;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SquadronCreated;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SquadronDemotion;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SquadronPromotion;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SquadronStartup;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SRVDestroyed;
    exports nl.jixxed.eliteodysseymaterials.journalevents.StartJump;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Statistics;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Status;
    exports nl.jixxed.eliteodysseymaterials.journalevents.StoredModules;
    exports nl.jixxed.eliteodysseymaterials.journalevents.StoredShips;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SuitLoadout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SupercruiseEntry;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SupercruiseExit;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SwitchSuitLoadout;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Synthesis;
    exports nl.jixxed.eliteodysseymaterials.journalevents.SystemsShutdown;
    exports nl.jixxed.eliteodysseymaterials.journalevents.TechnologyBroker;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Touchdown;
    exports nl.jixxed.eliteodysseymaterials.journalevents.TradeMicroResources;
    exports nl.jixxed.eliteodysseymaterials.journalevents.TransferMicroResources;
    exports nl.jixxed.eliteodysseymaterials.journalevents.UnderAttack;
    exports nl.jixxed.eliteodysseymaterials.journalevents.Undocked;
    exports nl.jixxed.eliteodysseymaterials.journalevents.UpgradeSuit;
    exports nl.jixxed.eliteodysseymaterials.journalevents.UpgradeWeapon;
    exports nl.jixxed.eliteodysseymaterials.journalevents.UseConsumable;
    exports nl.jixxed.eliteodysseymaterials.journalevents.USSDrop;
    exports nl.jixxed.eliteodysseymaterials.journalevents.VehicleSwitch;
    exports nl.jixxed.eliteodysseymaterials.journalevents.WingAdd;
    exports nl.jixxed.eliteodysseymaterials.journalevents.WingInvite;
    exports nl.jixxed.eliteodysseymaterials.journalevents.WingJoin;
    exports nl.jixxed.eliteodysseymaterials.journalevents.WingLeave;
    opens nl.jixxed.eliteodysseymaterials.journalevents.AfmuRepairs to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.AppliedToSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ApproachBody to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ApproachSettlement to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.AsteroidCracked to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Backpack to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BackpackChange to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BookDropship to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BookTaxi to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Bounty to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuyAmmo to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuyDrones to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuyExplorationData to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuyMicroResources to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuySuit to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuyTradeData to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.BuyWeapon to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CancelDropship to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CancelTaxi to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CapShipBond to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Cargo to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CargoDepot to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CargoTransfer to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierBankTransfer to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierBuy to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierCancelDecommission to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierCrewServices to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierDecommission to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierDepositFuel to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierDockingPermission to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierFinance to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierJump to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierJumpCancelled to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierJumpRequest to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierModulePack to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierNameChange to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierShipPack to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierStats to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CarrierTradeOrder to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ChangeCrewRole to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ClearImpound to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ClearSavedGame to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CockpitBreached to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CodexEntry to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CollectCargo to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CollectItems to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Commander to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CommitCrime to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoal to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoalDiscard to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoalJoin to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CommunityGoalReward to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Continued to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CreateSuitLoadout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewAssign to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewFire to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewHire to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewLaunchFighter to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewMemberJoins to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewMemberQuits to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrewMemberRoleChange to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.CrimeVictim to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DatalinkScan to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DatalinkVoucher to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DataScanned to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DeleteSuitLoadout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Died to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DisbandedSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DiscoveryScan to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Disembark to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Docked to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockFighter to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockingCancelled to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockingDenied to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockingGranted to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockingRequested to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockingTimeout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DockSRV to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DropItems to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.DropshipDeploy to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EjectCargo to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Embark to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EndCrewSession to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EngineerContribution to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EngineerCraft to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EngineerLegacyConvert to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EngineerProgress to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.EscapeInterdiction to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FactionKillBond to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FCMaterials to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FetchRemoteModule to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FighterDestroyed to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FighterRebuilt to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Fileheader to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Friends to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FSDJump to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FSDTarget to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FSSAllBodiesFound to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FSSBodySignals to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FSSDiscoveryScan to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FSSSignalDiscovered to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.FuelScoop to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.HeatDamage to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.HeatWarning to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.HullDamage to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Interdicted to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Interdiction to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.InvitedToSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.JetConeBoost to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.JetConeDamage to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.JoinACrew to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.JoinedSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.KickCrewMember to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.KickedFromSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LaunchDrone to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LaunchFighter to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LaunchSRV to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LeaveBody to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LeftSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Liftoff to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LoadGame to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Loadout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LoadoutEquipModule to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.LoadoutRemoveModule to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Location to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Market to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MarketBuy to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MarketSell to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MassModuleStore to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MaterialCollected to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MaterialDiscarded to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MaterialDiscovered to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Materials to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MaterialTrade to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MiningRefined to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MissionAbandoned to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MissionAccepted to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MissionCompleted to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MissionFailed to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MissionRedirected to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Missions to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleBuy to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleInfo to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleRetrieve to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleSell to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleSellRemote to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleStore to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ModuleSwap to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.MultiSellExplorationData to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Music to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.NavBeaconScan to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.NavRoute to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.NavRouteClear to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.NewCommander to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.NpcCrewPaidWage to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.NpcCrewRank to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Outfitting to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Passengers to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PayBounties to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PayFines to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Powerplay to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayCollect to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayDefect to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayDeliver to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayFastTrack to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayJoin to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayLeave to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplaySalary to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayVote to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PowerplayVoucher to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Progress to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Promotion to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ProspectedAsteroid to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.PVPKill to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.QuitACrew to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Rank to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RebootRepair to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ReceiveText to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RedeemVoucher to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RefuelAll to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RefuelPartial to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RenameSuitLoadout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Repair to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RepairAll to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RepairDrone to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Reputation to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ReservoirReplenished to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.RestockVehicle to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Resupply to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Resurrect to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SAAScanComplete to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SAASignalsFound to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Scan to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ScanBaryCentre to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Scanned to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ScanOrganic to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ScientificResearch to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Screenshot to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SearchAndRescue to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SelfDestruct to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellDrones to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellExplorationData to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellMicroResources to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellOrganicData to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellShipOnRebuy to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellSuit to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SellWeapon to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SendText to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SetUserShipName to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SharedBookmarkToSquadron to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShieldState to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipLocker to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipLockerMaterials to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipTargeted to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Shipyard to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipyardBuy to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipyardNew to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipyardSell to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipyardSwap to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.ShipyardTransfer to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Shutdown to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SquadronCreated to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SquadronDemotion to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SquadronPromotion to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SquadronStartup to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SRVDestroyed to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.StartJump to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Statistics to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Status to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.StoredModules to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.StoredShips to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SuitLoadout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SupercruiseEntry to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SupercruiseExit to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SwitchSuitLoadout to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Synthesis to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.SystemsShutdown to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.TechnologyBroker to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Touchdown to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.TradeMicroResources to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.TransferMicroResources to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.UnderAttack to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.Undocked to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.UpgradeSuit to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.UpgradeWeapon to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.UseConsumable to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.USSDrop to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.VehicleSwitch to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.WingAdd to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.WingInvite to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.WingJoin to com.fasterxml.jackson.databind;
    opens nl.jixxed.eliteodysseymaterials.journalevents.WingLeave to com.fasterxml.jackson.databind;
}