module nl.jixxed.eliteodysseymaterials {
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.datatype.jdk8;
    requires com.fasterxml.jackson.datatype.jsr310;
    requires com.google.common;
    requires com.google.j2objc.annotations;
    requires io.reactivex.rxjava3;
    requires java.naming;
    requires java.net.http;
    requires javafx.fxml;
    requires javafx.swing;
    requires javafx.graphics;
    requires jdk.naming.dns;
    requires nl.jixxed.lept4j;
    requires nl.jixxed.tess4j;
    requires org.apache.poi.ooxml.schemas;
    requires org.apache.poi.ooxml;
    requires org.apache.poi.poi;
    requires org.controlsfx.controls;
    requires org.jfxtras.styles.jmetro;
    requires org.slf4j;
    requires sentry;
    requires static lombok;
    requires javafx.controls;
    requires javafx.media;
    requires de.jensd.fx.glyphs.fontawesome;
    requires java.desktop;
    requires jdk.accessibility;
    requires de.jensd.fx.glyphs.commons;
    requires nl.jixxed.ed.awesome.api;
    requires nl.jixxed.ed.confidential.api;
    requires io.ebean;
    requires io.fair_acc.chartfx;
    requires io.fair_acc.dataset;
    requires io.fair_acc.bench;
    requires nl.jixxed.github.sponsor;
    requires nl.edomh.core;
    requires nl.edomh.ui.shared;
    requires org.jspecify;


    exports nl.jixxed.eliteodysseymaterials;
    exports nl.jixxed.eliteodysseymaterials.domain;
    exports nl.jixxed.eliteodysseymaterials.enums;
    exports nl.jixxed.eliteodysseymaterials.helper;
    exports nl.jixxed.eliteodysseymaterials.service;
    exports nl.jixxed.eliteodysseymaterials.service.ar;
    exports nl.jixxed.eliteodysseymaterials.service.event;
    exports nl.jixxed.eliteodysseymaterials.templates.dialog;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.commodities;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.engineers;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.materials;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.shipbuilder;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.wishlist;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons.menu;
    exports nl.jixxed.eliteodysseymaterials.templates.horizons;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.engineers;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.loadout;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.materials;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.wishlist;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey.menu;
    exports nl.jixxed.eliteodysseymaterials.templates.odyssey;
    exports nl.jixxed.eliteodysseymaterials.templates.other;
    exports nl.jixxed.eliteodysseymaterials.templates.other.colonisation;
    exports nl.jixxed.eliteodysseymaterials.templates.other.communitygoal;
    exports nl.jixxed.eliteodysseymaterials.templates.other.powerplay;
    exports nl.jixxed.eliteodysseymaterials.templates.other.permits;
    exports nl.jixxed.eliteodysseymaterials.templates.overlay.ar;
    exports nl.jixxed.eliteodysseymaterials.templates.settings.sections;
    exports nl.jixxed.eliteodysseymaterials.templates.settings;
    exports nl.jixxed.eliteodysseymaterials.templates;
    opens nl.jixxed.eliteodysseymaterials to javafx.graphics, java.desktop;
    opens nl.jixxed.eliteodysseymaterials.templates to java.desktop, javafx.fxml, javafx.graphics, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.dialog to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.dialog.importdialog to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.commodities to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.engineers to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.materials to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.horizons.wishlist to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.engineers to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.loadout to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.materials to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.odyssey.wishlist to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.other to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.other.communitygoal to javafx.fxml, org.controlsfx.controls, io.fair_acc.chartfx;
    opens nl.jixxed.eliteodysseymaterials.templates.overlay.ar to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.settings to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.templates.settings.sections to javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.domain to com.fasterxml.jackson.databind, javafx.fxml, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.enums to com.fasterxml.jackson.databind, org.hibernate.validator;
    opens nl.jixxed.eliteodysseymaterials.service.event to com.fasterxml.jackson.databind, org.hibernate.validator;
    opens nl.jixxed.eliteodysseymaterials.builder to java.desktop, javafx.fxml, javafx.graphics, org.controlsfx.controls;
    opens nl.jixxed.eliteodysseymaterials.helper to com.fasterxml.jackson.databind, org.hibernate.validator;
}