package nl.jixxed.eliteodysseymaterials.domain.ships.core_internals;

import lombok.Getter;
import nl.jixxed.eliteodysseymaterials.domain.ships.CoreModule;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleClass;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleSize;
import nl.jixxed.eliteodysseymaterials.domain.ships.ShipType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.List;
import java.util.Map;

public class Armour extends CoreModule {
    public static final Armour SIDE_WINDER_ARMOUR_GRADE_1 = new Armour(ShipType.SIDE_WINDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "SideWinder_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour SIDE_WINDER_ARMOUR_GRADE_2 = new Armour(ShipType.SIDE_WINDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 25600, "SideWinder_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour SIDE_WINDER_ARMOUR_GRADE_3 = new Armour(ShipType.SIDE_WINDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 80320, "SideWinder_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour SIDE_WINDER_ARMOUR_MIRRORED = new Armour(ShipType.SIDE_WINDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 132060, "SideWinder_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour SIDE_WINDER_ARMOUR_REACTIVE = new Armour(ShipType.SIDE_WINDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 139420, "SideWinder_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour EAGLE_ARMOUR_GRADE_1 = new Armour(ShipType.EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Eagle_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EAGLE_ARMOUR_GRADE_2 = new Armour(ShipType.EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 26880, "Eagle_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EAGLE_ARMOUR_GRADE_3 = new Armour(ShipType.EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 90050, "Eagle_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EAGLE_ARMOUR_MIRRORED = new Armour(ShipType.EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 140090, "Eagle_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour EAGLE_ARMOUR_REACTIVE = new Armour(ShipType.EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 150390, "Eagle_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour HAULER_ARMOUR_GRADE_1 = new Armour(ShipType.HAULER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Hauler_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour HAULER_ARMOUR_GRADE_2 = new Armour(ShipType.HAULER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 42180, "Hauler_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour HAULER_ARMOUR_GRADE_3 = new Armour(ShipType.HAULER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 185050, "Hauler_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour HAULER_ARMOUR_MIRRORED = new Armour(ShipType.HAULER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 270300, "Hauler_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour HAULER_ARMOUR_REACTIVE = new Armour(ShipType.HAULER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 282420, "Hauler_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour ADDER_ARMOUR_GRADE_1 = new Armour(ShipType.ADDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Adder_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ADDER_ARMOUR_GRADE_2 = new Armour(ShipType.ADDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 35120, "Adder_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 3.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ADDER_ARMOUR_GRADE_3 = new Armour(ShipType.ADDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 79030, "Adder_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ADDER_ARMOUR_MIRRORED = new Armour(ShipType.ADDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 186770, "Adder_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour ADDER_ARMOUR_REACTIVE = new Armour(ShipType.ADDER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 206960, "Adder_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour EMPIRE_EAGLE_ARMOUR_GRADE_1 = new Armour(ShipType.EMPIRE_EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Empire_Eagle_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_EAGLE_ARMOUR_GRADE_2 = new Armour(ShipType.EMPIRE_EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 66500, "Empire_Eagle_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_EAGLE_ARMOUR_GRADE_3 = new Armour(ShipType.EMPIRE_EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 222760, "Empire_Eagle_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_EAGLE_ARMOUR_MIRRORED = new Armour(ShipType.EMPIRE_EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 346550, "Empire_Eagle_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour EMPIRE_EAGLE_ARMOUR_REACTIVE = new Armour(ShipType.EMPIRE_EAGLE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 372040, "Empire_Eagle_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour VIPER_ARMOUR_GRADE_1 = new Armour(ShipType.VIPER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Viper_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VIPER_ARMOUR_GRADE_2 = new Armour(ShipType.VIPER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 57170, "Viper_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VIPER_ARMOUR_GRADE_3 = new Armour(ShipType.VIPER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 128640, "Viper_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 9.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VIPER_ARMOUR_MIRRORED = new Armour(ShipType.VIPER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 304010, "Viper_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 9.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour VIPER_ARMOUR_REACTIVE = new Armour(ShipType.VIPER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 336890, "Viper_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 9.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour COBRA_MK_III_ARMOUR_GRADE_1 = new Armour(ShipType.COBRA_MK_III, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "CobraMkIII_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour COBRA_MK_III_ARMOUR_GRADE_2 = new Armour(ShipType.COBRA_MK_III, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 151890, "CobraMkIII_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 14.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour COBRA_MK_III_ARMOUR_GRADE_3 = new Armour(ShipType.COBRA_MK_III, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 341750, "CobraMkIII_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 27.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour COBRA_MK_III_ARMOUR_MIRRORED = new Armour(ShipType.COBRA_MK_III, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 797410, "CobraMkIII_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 27.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour COBRA_MK_III_ARMOUR_REACTIVE = new Armour(ShipType.COBRA_MK_III, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 895000, "CobraMkIII_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 27.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour VIPER_MK_IV_ARMOUR_GRADE_1 = new Armour(ShipType.VIPER_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Viper_MkIV_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VIPER_MK_IV_ARMOUR_GRADE_2 = new Armour(ShipType.VIPER_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 175180, "Viper_MkIV_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VIPER_MK_IV_ARMOUR_GRADE_3 = new Armour(ShipType.VIPER_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 394140, "Viper_MkIV_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 9.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VIPER_MK_IV_ARMOUR_MIRRORED = new Armour(ShipType.VIPER_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 931490, "Viper_MkIV_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 9.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour VIPER_MK_IV_ARMOUR_REACTIVE = new Armour(ShipType.VIPER_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1033210, "Viper_MkIV_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 9.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour DIAMOND_BACK_ARMOUR_GRADE_1 = new Armour(ShipType.DIAMOND_BACK, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "DiamondBack_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DIAMOND_BACK_ARMOUR_GRADE_2 = new Armour(ShipType.DIAMOND_BACK, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 225730, "DiamondBack_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 13.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DIAMOND_BACK_ARMOUR_GRADE_3 = new Armour(ShipType.DIAMOND_BACK, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 507900, "DiamondBack_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 26.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DIAMOND_BACK_ARMOUR_MIRRORED = new Armour(ShipType.DIAMOND_BACK, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1185100, "DiamondBack_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 26.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour DIAMOND_BACK_ARMOUR_REACTIVE = new Armour(ShipType.DIAMOND_BACK, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1330120, "DiamondBack_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 26.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour COBRA_MK_IV_ARMOUR_GRADE_1 = new Armour(ShipType.COBRA_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "CobraMkIV_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour COBRA_MK_IV_ARMOUR_GRADE_2 = new Armour(ShipType.COBRA_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 305890, "CobraMkIV_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 14.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour COBRA_MK_IV_ARMOUR_GRADE_3 = new Armour(ShipType.COBRA_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 688250, "CobraMkIV_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 27.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour COBRA_MK_IV_ARMOUR_MIRRORED = new Armour(ShipType.COBRA_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1605910, "CobraMkIV_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 27.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour COBRA_MK_IV_ARMOUR_REACTIVE = new Armour(ShipType.COBRA_MK_IV, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1802440, "CobraMkIV_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 27.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_6_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_6, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Type6_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_6_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_6, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 418380, "Type6_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 12.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_6_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_6, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 941350, "Type6_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_6_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_6, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 2224730, "Type6_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_6_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_6, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 2465290, "Type6_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour DOLPHIN_ARMOUR_GRADE_1 = new Armour(ShipType.DOLPHIN, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Dolphin_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DOLPHIN_ARMOUR_GRADE_2 = new Armour(ShipType.DOLPHIN, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 534940, "Dolphin_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 32.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DOLPHIN_ARMOUR_GRADE_3 = new Armour(ShipType.DOLPHIN, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1203600, "Dolphin_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 63.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DOLPHIN_ARMOUR_MIRRORED = new Armour(ShipType.DOLPHIN, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 2808390, "Dolphin_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 63.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour DOLPHIN_ARMOUR_REACTIVE = new Armour(ShipType.DOLPHIN, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 3152080, "Dolphin_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 63.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour DIAMOND_BACK_XL_ARMOUR_GRADE_1 = new Armour(ShipType.DIAMOND_BACK_XL, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "DiamondBackXL_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DIAMOND_BACK_XL_ARMOUR_GRADE_2 = new Armour(ShipType.DIAMOND_BACK_XL, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 757900, "DiamondBackXL_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DIAMOND_BACK_XL_ARMOUR_GRADE_3 = new Armour(ShipType.DIAMOND_BACK_XL, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 1705290, "DiamondBackXL_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 47.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour DIAMOND_BACK_XL_ARMOUR_MIRRORED = new Armour(ShipType.DIAMOND_BACK_XL, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 3979000, "DiamondBackXL_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 47.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour DIAMOND_BACK_XL_ARMOUR_REACTIVE = new Armour(ShipType.DIAMOND_BACK_XL, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 4465960, "DiamondBackXL_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 47.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour EMPIRE_COURIER_ARMOUR_GRADE_1 = new Armour(ShipType.EMPIRE_COURIER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Empire_Courier_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_COURIER_ARMOUR_GRADE_2 = new Armour(ShipType.EMPIRE_COURIER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 1017200, "Empire_Courier_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_COURIER_ARMOUR_GRADE_3 = new Armour(ShipType.EMPIRE_COURIER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 2288600, "Empire_Courier_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_COURIER_ARMOUR_MIRRORED = new Armour(ShipType.EMPIRE_COURIER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 5408800, "Empire_Courier_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour EMPIRE_COURIER_ARMOUR_REACTIVE = new Armour(ShipType.EMPIRE_COURIER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 5993700, "Empire_Courier_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour INDEPENDANT_TRADER_ARMOUR_GRADE_1 = new Armour(ShipType.INDEPENDANT_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Independant_Trader_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour INDEPENDANT_TRADER_ARMOUR_GRADE_2 = new Armour(ShipType.INDEPENDANT_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 1250460, "Independant_Trader_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 12.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour INDEPENDANT_TRADER_ARMOUR_GRADE_3 = new Armour(ShipType.INDEPENDANT_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 2813540, "Independant_Trader_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour INDEPENDANT_TRADER_ARMOUR_MIRRORED = new Armour(ShipType.INDEPENDANT_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 6649330, "Independant_Trader_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour INDEPENDANT_TRADER_ARMOUR_REACTIVE = new Armour(ShipType.INDEPENDANT_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 7368340, "Independant_Trader_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 23.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour ASP_SCOUT_ARMOUR_GRADE_1 = new Armour(ShipType.ASP_SCOUT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Asp_Scout_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ASP_SCOUT_ARMOUR_GRADE_2 = new Armour(ShipType.ASP_SCOUT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 1584460, "Asp_Scout_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 21.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ASP_SCOUT_ARMOUR_GRADE_3 = new Armour(ShipType.ASP_SCOUT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 3565040, "Asp_Scout_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 42.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ASP_SCOUT_ARMOUR_MIRRORED = new Armour(ShipType.ASP_SCOUT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 8425380, "Asp_Scout_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 42.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour ASP_SCOUT_ARMOUR_REACTIVE = new Armour(ShipType.ASP_SCOUT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 9336440, "Asp_Scout_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 42.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour VULTURE_ARMOUR_GRADE_1 = new Armour(ShipType.VULTURE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Vulture_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VULTURE_ARMOUR_GRADE_2 = new Armour(ShipType.VULTURE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 1970250, "Vulture_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 17.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VULTURE_ARMOUR_GRADE_3 = new Armour(ShipType.VULTURE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 4433050, "Vulture_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 35.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour VULTURE_ARMOUR_MIRRORED = new Armour(ShipType.VULTURE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 10476780, "Vulture_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 35.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour VULTURE_ARMOUR_REACTIVE = new Armour(ShipType.VULTURE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 11609670, "Vulture_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 35.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour ASP_ARMOUR_GRADE_1 = new Armour(ShipType.ASP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Asp_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ASP_ARMOUR_GRADE_2 = new Armour(ShipType.ASP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 2664460, "Asp_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 21.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ASP_ARMOUR_GRADE_3 = new Armour(ShipType.ASP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 5995040, "Asp_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 42.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ASP_ARMOUR_MIRRORED = new Armour(ShipType.ASP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 14168270, "Asp_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 42.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour ASP_ARMOUR_REACTIVE = new Armour(ShipType.ASP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 15700340, "Asp_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 42.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour FEDERATION_DROPSHIP_ARMOUR_GRADE_1 = new Armour(ShipType.FEDERATION_DROPSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Federation_Dropship_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_DROPSHIP_ARMOUR_GRADE_2 = new Armour(ShipType.FEDERATION_DROPSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 5725680, "Federation_Dropship_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 44.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_DROPSHIP_ARMOUR_GRADE_3 = new Armour(ShipType.FEDERATION_DROPSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 12882780, "Federation_Dropship_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_DROPSHIP_ARMOUR_MIRRORED = new Armour(ShipType.FEDERATION_DROPSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 30446310, "Federation_Dropship_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour FEDERATION_DROPSHIP_ARMOUR_REACTIVE = new Armour(ShipType.FEDERATION_DROPSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 33738580, "Federation_Dropship_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_7_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_7, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Type7_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_7_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_7, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 6988900, "Type7_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 32.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_7_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_7, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 15725030, "Type7_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 63.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_7_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_7, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 37163480, "Type7_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 63.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_7_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_7, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 41182100, "Type7_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 63.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_X_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_X, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "TypeX_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_X, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 7752900, "TypeX_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_X, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 17444030, "TypeX_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_X, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 41226050, "TypeX_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_X_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_X, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 45683980, "TypeX_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour FEDERATION_DROPSHIP_MK_II_ARMOUR_GRADE_1 = new Armour(ShipType.FEDERATION_DROPSHIP_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Federation_Dropship_MkII_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_DROPSHIP_MK_II_ARMOUR_GRADE_2 = new Armour(ShipType.FEDERATION_DROPSHIP_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 7925680, "Federation_Dropship_MkII_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 44.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_DROPSHIP_MK_II_ARMOUR_GRADE_3 = new Armour(ShipType.FEDERATION_DROPSHIP_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 17832780, "Federation_Dropship_MkII_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_DROPSHIP_MK_II_ARMOUR_MIRRORED = new Armour(ShipType.FEDERATION_DROPSHIP_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 42144810, "Federation_Dropship_MkII_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour FEDERATION_DROPSHIP_MK_II_ARMOUR_REACTIVE = new Armour(ShipType.FEDERATION_DROPSHIP_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 46702080, "Federation_Dropship_MkII_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour EMPIRE_TRADER_ARMOUR_GRADE_1 = new Armour(ShipType.EMPIRE_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Empire_Trader_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_TRADER_ARMOUR_GRADE_2 = new Armour(ShipType.EMPIRE_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 8918340, "Empire_Trader_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 30.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_TRADER_ARMOUR_GRADE_3 = new Armour(ShipType.EMPIRE_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 20066270, "Empire_Trader_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour EMPIRE_TRADER_ARMOUR_MIRRORED = new Armour(ShipType.EMPIRE_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 47423290, "Empire_Trader_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour EMPIRE_TRADER_ARMOUR_REACTIVE = new Armour(ShipType.EMPIRE_TRADER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 52551340, "Empire_Trader_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_X_2_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_X_2, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "TypeX_2_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_2_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_X_2, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 9146540, "TypeX_2_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_2_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_X_2, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 20579710, "TypeX_2_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_2_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_X_2, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 48636710, "TypeX_2_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_X_2_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_X_2, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 53895970, "TypeX_2_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_X_3_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_X_3, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "TypeX_3_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_3_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_X_3, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 6803170, "TypeX_3_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_3_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_X_3, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 15307130, "TypeX_3_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_X_3_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_X_3, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 36175860, "TypeX_3_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_X_3_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_X_3, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 40087680, "TypeX_3_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 78.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour FEDERATION_GUNSHIP_ARMOUR_GRADE_1 = new Armour(ShipType.FEDERATION_GUNSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Federation_Gunship_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_GUNSHIP_ARMOUR_GRADE_2 = new Armour(ShipType.FEDERATION_GUNSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 14325690, "Federation_Gunship_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 44.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_GUNSHIP_ARMOUR_GRADE_3 = new Armour(ShipType.FEDERATION_GUNSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 32232790, "Federation_Gunship_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_GUNSHIP_ARMOUR_MIRRORED = new Armour(ShipType.FEDERATION_GUNSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 76176810, "Federation_Gunship_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour FEDERATION_GUNSHIP_ARMOUR_REACTIVE = new Armour(ShipType.FEDERATION_GUNSHIP, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 84414090, "Federation_Gunship_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour KRAIT_LIGHT_ARMOUR_GRADE_1 = new Armour(ShipType.KRAIT_LIGHT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Krait_Light_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour KRAIT_LIGHT_ARMOUR_GRADE_2 = new Armour(ShipType.KRAIT_LIGHT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 14988900, "Krait_Light_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 26.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour KRAIT_LIGHT_ARMOUR_GRADE_3 = new Armour(ShipType.KRAIT_LIGHT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 33725030, "Krait_Light_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 53.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour KRAIT_LIGHT_ARMOUR_MIRRORED = new Armour(ShipType.KRAIT_LIGHT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 79703480, "Krait_Light_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 53.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour KRAIT_LIGHT_ARMOUR_REACTIVE = new Armour(ShipType.KRAIT_LIGHT, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 88322100, "Krait_Light_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 53.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour KRAIT_MK_II_ARMOUR_GRADE_1 = new Armour(ShipType.KRAIT_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Krait_MkII_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour KRAIT_MK_II_ARMOUR_GRADE_2 = new Armour(ShipType.KRAIT_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 18325680, "Krait_MkII_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 36.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour KRAIT_MK_II_ARMOUR_GRADE_3 = new Armour(ShipType.KRAIT_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 41232790, "Krait_MkII_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 67.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour KRAIT_MK_II_ARMOUR_MIRRORED = new Armour(ShipType.KRAIT_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 97446810, "Krait_MkII_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 67.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour KRAIT_MK_II_ARMOUR_REACTIVE = new Armour(ShipType.KRAIT_MK_II, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 107984080, "Krait_MkII_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 67.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour ORCA_ARMOUR_GRADE_1 = new Armour(ShipType.ORCA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Orca_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ORCA_ARMOUR_GRADE_2 = new Armour(ShipType.ORCA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 19415950, "Orca_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 21.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ORCA_ARMOUR_GRADE_3 = new Armour(ShipType.ORCA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 43685900, "Orca_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ORCA_ARMOUR_MIRRORED = new Armour(ShipType.ORCA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 103244340, "Orca_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour ORCA_ARMOUR_REACTIVE = new Armour(ShipType.ORCA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 114408510, "Orca_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 87.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour FER_DE_LANCE_ARMOUR_GRADE_1 = new Armour(ShipType.FER_DE_LANCE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "FerDeLance_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FER_DE_LANCE_ARMOUR_GRADE_2 = new Armour(ShipType.FER_DE_LANCE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 20626820, "FerDeLance_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 19.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FER_DE_LANCE_ARMOUR_GRADE_3 = new Armour(ShipType.FER_DE_LANCE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 46410340, "FerDeLance_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 38.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FER_DE_LANCE_ARMOUR_MIRRORED = new Armour(ShipType.FER_DE_LANCE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 109683090, "FerDeLance_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 38.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour FER_DE_LANCE_ARMOUR_REACTIVE = new Armour(ShipType.FER_DE_LANCE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 121543510, "FerDeLance_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 38.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour MAMBA_ARMOUR_GRADE_1 = new Armour(ShipType.MAMBA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Mamba_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour MAMBA_ARMOUR_GRADE_2 = new Armour(ShipType.MAMBA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 20626820, "Mamba_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 19.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour MAMBA_ARMOUR_GRADE_3 = new Armour(ShipType.MAMBA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 46410340, "Mamba_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 38.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour MAMBA_ARMOUR_MIRRORED = new Armour(ShipType.MAMBA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 109683090, "Mamba_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 38.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour MAMBA_ARMOUR_REACTIVE = new Armour(ShipType.MAMBA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 121543510, "Mamba_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 38.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour PYTHON_ARMOUR_GRADE_1 = new Armour(ShipType.PYTHON, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Python_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour PYTHON_ARMOUR_GRADE_2 = new Armour(ShipType.PYTHON, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 22791270, "Python_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 26.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour PYTHON_ARMOUR_GRADE_3 = new Armour(ShipType.PYTHON, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 51280360, "Python_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 53.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour PYTHON_ARMOUR_MIRRORED = new Armour(ShipType.PYTHON, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 121192590, "Python_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 53.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour PYTHON_ARMOUR_REACTIVE = new Armour(ShipType.PYTHON, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 134297570, "Python_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 53.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_9_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_9, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Type9_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_9_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_9, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 30622340, "Type9_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 75.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_9_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_9, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 68900260, "Type9_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 150.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_9_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_9, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 162834280, "Type9_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 150.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_9_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_9, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 180442120, "Type9_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 150.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour BELUGA_LINER_ARMOUR_GRADE_1 = new Armour(ShipType.BELUGA_LINER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "BelugaLiner_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour BELUGA_LINER_ARMOUR_GRADE_2 = new Armour(ShipType.BELUGA_LINER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 33813120, "BelugaLiner_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 83.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour BELUGA_LINER_ARMOUR_GRADE_3 = new Armour(ShipType.BELUGA_LINER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 76079500, "BelugaLiner_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 165.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour BELUGA_LINER_ARMOUR_MIRRORED = new Armour(ShipType.BELUGA_LINER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 179801200, "BelugaLiner_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 165.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour BELUGA_LINER_ARMOUR_REACTIVE = new Armour(ShipType.BELUGA_LINER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 199243730, "BelugaLiner_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 165.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour TYPE_9_MILITARY_ARMOUR_GRADE_1 = new Armour(ShipType.TYPE_9_MILITARY, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Type9_Military_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_9_MILITARY_ARMOUR_GRADE_2 = new Armour(ShipType.TYPE_9_MILITARY, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 49902130, "Type9_Military_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 75.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_9_MILITARY_ARMOUR_GRADE_3 = new Armour(ShipType.TYPE_9_MILITARY, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 112279810, "Type9_Military_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 150.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour TYPE_9_MILITARY_ARMOUR_MIRRORED = new Armour(ShipType.TYPE_9_MILITARY, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 265354610, "Type9_Military_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 150.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour TYPE_9_MILITARY_ARMOUR_REACTIVE = new Armour(ShipType.TYPE_9_MILITARY, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 294048340, "Type9_Military_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 150.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour ANACONDA_ARMOUR_GRADE_1 = new Armour(ShipType.ANACONDA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Anaconda_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ANACONDA_ARMOUR_GRADE_2 = new Armour(ShipType.ANACONDA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 58787780, "Anaconda_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 30.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ANACONDA_ARMOUR_GRADE_3 = new Armour(ShipType.ANACONDA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 132272510, "Anaconda_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour ANACONDA_ARMOUR_MIRRORED = new Armour(ShipType.ANACONDA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 312604020, "Anaconda_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour ANACONDA_ARMOUR_REACTIVE = new Armour(ShipType.ANACONDA, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 346407000, "Anaconda_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour FEDERATION_CORVETTE_ARMOUR_GRADE_1 = new Armour(ShipType.FEDERATION_CORVETTE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Federation_Corvette_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_CORVETTE_ARMOUR_GRADE_2 = new Armour(ShipType.FEDERATION_CORVETTE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 75187790, "Federation_Corvette_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 30.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_CORVETTE_ARMOUR_GRADE_3 = new Armour(ShipType.FEDERATION_CORVETTE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 169172510, "Federation_Corvette_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour FEDERATION_CORVETTE_ARMOUR_MIRRORED = new Armour(ShipType.FEDERATION_CORVETTE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 399811020, "Federation_Corvette_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour FEDERATION_CORVETTE_ARMOUR_REACTIVE = new Armour(ShipType.FEDERATION_CORVETTE, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 443044000, "Federation_Corvette_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));
    public static final Armour CUTTER_ARMOUR_GRADE_1 = new Armour(ShipType.CUTTER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.C, 0, "Cutter_Armour_Grade1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.00), Map.entry(HorizonsModifier.HULL_BOOST, 80.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour CUTTER_ARMOUR_GRADE_2 = new Armour(ShipType.CUTTER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.B, 83587780, "Cutter_Armour_Grade2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 30.00), Map.entry(HorizonsModifier.HULL_BOOST, 152.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour CUTTER_ARMOUR_GRADE_3 = new Armour(ShipType.CUTTER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 188072500, "Cutter_Armour_Grade3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -20.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 0.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -40.0)));
    public static final Armour CUTTER_ARMOUR_MIRRORED = new Armour(ShipType.CUTTER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 444478020, "Cutter_Armour_Mirrored", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, -75.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, 50.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, -50.0)));
    public static final Armour CUTTER_ARMOUR_REACTIVE = new Armour(ShipType.CUTTER, HorizonsBlueprintName.ARMOUR, ModuleSize.SIZE_1, ModuleClass.A, 492541000, "Cutter_Armour_Reactive", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 60.00), Map.entry(HorizonsModifier.HULL_BOOST, 250.0), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 25.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -40.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 20.0)));

    public static final  List<Armour> ARMOURS = List.of(
            SIDE_WINDER_ARMOUR_GRADE_1,
            SIDE_WINDER_ARMOUR_GRADE_2,
            SIDE_WINDER_ARMOUR_GRADE_3,
            SIDE_WINDER_ARMOUR_MIRRORED,
            SIDE_WINDER_ARMOUR_REACTIVE,
            EAGLE_ARMOUR_GRADE_1,
            EAGLE_ARMOUR_GRADE_2,
            EAGLE_ARMOUR_GRADE_3,
            EAGLE_ARMOUR_MIRRORED,
            EAGLE_ARMOUR_REACTIVE,
            HAULER_ARMOUR_GRADE_1,
            HAULER_ARMOUR_GRADE_2,
            HAULER_ARMOUR_GRADE_3,
            HAULER_ARMOUR_MIRRORED,
            HAULER_ARMOUR_REACTIVE,
            ADDER_ARMOUR_GRADE_1,
            ADDER_ARMOUR_GRADE_2,
            ADDER_ARMOUR_GRADE_3,
            ADDER_ARMOUR_MIRRORED,
            ADDER_ARMOUR_REACTIVE,
            EMPIRE_EAGLE_ARMOUR_GRADE_1,
            EMPIRE_EAGLE_ARMOUR_GRADE_2,
            EMPIRE_EAGLE_ARMOUR_GRADE_3,
            EMPIRE_EAGLE_ARMOUR_MIRRORED,
            EMPIRE_EAGLE_ARMOUR_REACTIVE,
            VIPER_ARMOUR_GRADE_1,
            VIPER_ARMOUR_GRADE_2,
            VIPER_ARMOUR_GRADE_3,
            VIPER_ARMOUR_MIRRORED,
            VIPER_ARMOUR_REACTIVE,
            COBRA_MK_III_ARMOUR_GRADE_1,
            COBRA_MK_III_ARMOUR_GRADE_2,
            COBRA_MK_III_ARMOUR_GRADE_3,
            COBRA_MK_III_ARMOUR_MIRRORED,
            COBRA_MK_III_ARMOUR_REACTIVE,
            VIPER_MK_IV_ARMOUR_GRADE_1,
            VIPER_MK_IV_ARMOUR_GRADE_2,
            VIPER_MK_IV_ARMOUR_GRADE_3,
            VIPER_MK_IV_ARMOUR_MIRRORED,
            VIPER_MK_IV_ARMOUR_REACTIVE,
            DIAMOND_BACK_ARMOUR_GRADE_1,
            DIAMOND_BACK_ARMOUR_GRADE_2,
            DIAMOND_BACK_ARMOUR_GRADE_3,
            DIAMOND_BACK_ARMOUR_MIRRORED,
            DIAMOND_BACK_ARMOUR_REACTIVE,
            COBRA_MK_IV_ARMOUR_GRADE_1,
            COBRA_MK_IV_ARMOUR_GRADE_2,
            COBRA_MK_IV_ARMOUR_GRADE_3,
            COBRA_MK_IV_ARMOUR_MIRRORED,
            COBRA_MK_IV_ARMOUR_REACTIVE,
            TYPE_6_ARMOUR_GRADE_1,
            TYPE_6_ARMOUR_GRADE_2,
            TYPE_6_ARMOUR_GRADE_3,
            TYPE_6_ARMOUR_MIRRORED,
            TYPE_6_ARMOUR_REACTIVE,
            DOLPHIN_ARMOUR_GRADE_1,
            DOLPHIN_ARMOUR_GRADE_2,
            DOLPHIN_ARMOUR_GRADE_3,
            DOLPHIN_ARMOUR_MIRRORED,
            DOLPHIN_ARMOUR_REACTIVE,
            DIAMOND_BACK_XL_ARMOUR_GRADE_1,
            DIAMOND_BACK_XL_ARMOUR_GRADE_2,
            DIAMOND_BACK_XL_ARMOUR_GRADE_3,
            DIAMOND_BACK_XL_ARMOUR_MIRRORED,
            DIAMOND_BACK_XL_ARMOUR_REACTIVE,
            EMPIRE_COURIER_ARMOUR_GRADE_1,
            EMPIRE_COURIER_ARMOUR_GRADE_2,
            EMPIRE_COURIER_ARMOUR_GRADE_3,
            EMPIRE_COURIER_ARMOUR_MIRRORED,
            EMPIRE_COURIER_ARMOUR_REACTIVE,
            INDEPENDANT_TRADER_ARMOUR_GRADE_1,
            INDEPENDANT_TRADER_ARMOUR_GRADE_2,
            INDEPENDANT_TRADER_ARMOUR_GRADE_3,
            INDEPENDANT_TRADER_ARMOUR_MIRRORED,
            INDEPENDANT_TRADER_ARMOUR_REACTIVE,
            ASP_SCOUT_ARMOUR_GRADE_1,
            ASP_SCOUT_ARMOUR_GRADE_2,
            ASP_SCOUT_ARMOUR_GRADE_3,
            ASP_SCOUT_ARMOUR_MIRRORED,
            ASP_SCOUT_ARMOUR_REACTIVE,
            VULTURE_ARMOUR_GRADE_1,
            VULTURE_ARMOUR_GRADE_2,
            VULTURE_ARMOUR_GRADE_3,
            VULTURE_ARMOUR_MIRRORED,
            VULTURE_ARMOUR_REACTIVE,
            ASP_ARMOUR_GRADE_1,
            ASP_ARMOUR_GRADE_2,
            ASP_ARMOUR_GRADE_3,
            ASP_ARMOUR_MIRRORED,
            ASP_ARMOUR_REACTIVE,
            FEDERATION_DROPSHIP_ARMOUR_GRADE_1,
            FEDERATION_DROPSHIP_ARMOUR_GRADE_2,
            FEDERATION_DROPSHIP_ARMOUR_GRADE_3,
            FEDERATION_DROPSHIP_ARMOUR_MIRRORED,
            FEDERATION_DROPSHIP_ARMOUR_REACTIVE,
            TYPE_7_ARMOUR_GRADE_1,
            TYPE_7_ARMOUR_GRADE_2,
            TYPE_7_ARMOUR_GRADE_3,
            TYPE_7_ARMOUR_MIRRORED,
            TYPE_7_ARMOUR_REACTIVE,
            TYPE_X_ARMOUR_GRADE_1,
            TYPE_X_ARMOUR_GRADE_2,
            TYPE_X_ARMOUR_GRADE_3,
            TYPE_X_ARMOUR_MIRRORED,
            TYPE_X_ARMOUR_REACTIVE,
            FEDERATION_DROPSHIP_MK_II_ARMOUR_GRADE_1,
            FEDERATION_DROPSHIP_MK_II_ARMOUR_GRADE_2,
            FEDERATION_DROPSHIP_MK_II_ARMOUR_GRADE_3,
            FEDERATION_DROPSHIP_MK_II_ARMOUR_MIRRORED,
            FEDERATION_DROPSHIP_MK_II_ARMOUR_REACTIVE,
            EMPIRE_TRADER_ARMOUR_GRADE_1,
            EMPIRE_TRADER_ARMOUR_GRADE_2,
            EMPIRE_TRADER_ARMOUR_GRADE_3,
            EMPIRE_TRADER_ARMOUR_MIRRORED,
            EMPIRE_TRADER_ARMOUR_REACTIVE,
            TYPE_X_2_ARMOUR_GRADE_1,
            TYPE_X_2_ARMOUR_GRADE_2,
            TYPE_X_2_ARMOUR_GRADE_3,
            TYPE_X_2_ARMOUR_MIRRORED,
            TYPE_X_2_ARMOUR_REACTIVE,
            TYPE_X_3_ARMOUR_GRADE_1,
            TYPE_X_3_ARMOUR_GRADE_2,
            TYPE_X_3_ARMOUR_GRADE_3,
            TYPE_X_3_ARMOUR_MIRRORED,
            TYPE_X_3_ARMOUR_REACTIVE,
            FEDERATION_GUNSHIP_ARMOUR_GRADE_1,
            FEDERATION_GUNSHIP_ARMOUR_GRADE_2,
            FEDERATION_GUNSHIP_ARMOUR_GRADE_3,
            FEDERATION_GUNSHIP_ARMOUR_MIRRORED,
            FEDERATION_GUNSHIP_ARMOUR_REACTIVE,
            KRAIT_LIGHT_ARMOUR_GRADE_1,
            KRAIT_LIGHT_ARMOUR_GRADE_2,
            KRAIT_LIGHT_ARMOUR_GRADE_3,
            KRAIT_LIGHT_ARMOUR_MIRRORED,
            KRAIT_LIGHT_ARMOUR_REACTIVE,
            KRAIT_MK_II_ARMOUR_GRADE_1,
            KRAIT_MK_II_ARMOUR_GRADE_2,
            KRAIT_MK_II_ARMOUR_GRADE_3,
            KRAIT_MK_II_ARMOUR_MIRRORED,
            KRAIT_MK_II_ARMOUR_REACTIVE,
            ORCA_ARMOUR_GRADE_1,
            ORCA_ARMOUR_GRADE_2,
            ORCA_ARMOUR_GRADE_3,
            ORCA_ARMOUR_MIRRORED,
            ORCA_ARMOUR_REACTIVE,
            FER_DE_LANCE_ARMOUR_GRADE_1,
            FER_DE_LANCE_ARMOUR_GRADE_2,
            FER_DE_LANCE_ARMOUR_GRADE_3,
            FER_DE_LANCE_ARMOUR_MIRRORED,
            FER_DE_LANCE_ARMOUR_REACTIVE,
            MAMBA_ARMOUR_GRADE_1,
            MAMBA_ARMOUR_GRADE_2,
            MAMBA_ARMOUR_GRADE_3,
            MAMBA_ARMOUR_MIRRORED,
            MAMBA_ARMOUR_REACTIVE,
            PYTHON_ARMOUR_GRADE_1,
            PYTHON_ARMOUR_GRADE_2,
            PYTHON_ARMOUR_GRADE_3,
            PYTHON_ARMOUR_MIRRORED,
            PYTHON_ARMOUR_REACTIVE,
            TYPE_9_ARMOUR_GRADE_1,
            TYPE_9_ARMOUR_GRADE_2,
            TYPE_9_ARMOUR_GRADE_3,
            TYPE_9_ARMOUR_MIRRORED,
            TYPE_9_ARMOUR_REACTIVE,
            BELUGA_LINER_ARMOUR_GRADE_1,
            BELUGA_LINER_ARMOUR_GRADE_2,
            BELUGA_LINER_ARMOUR_GRADE_3,
            BELUGA_LINER_ARMOUR_MIRRORED,
            BELUGA_LINER_ARMOUR_REACTIVE,
            TYPE_9_MILITARY_ARMOUR_GRADE_1,
            TYPE_9_MILITARY_ARMOUR_GRADE_2,
            TYPE_9_MILITARY_ARMOUR_GRADE_3,
            TYPE_9_MILITARY_ARMOUR_MIRRORED,
            TYPE_9_MILITARY_ARMOUR_REACTIVE,
            ANACONDA_ARMOUR_GRADE_1,
            ANACONDA_ARMOUR_GRADE_2,
            ANACONDA_ARMOUR_GRADE_3,
            ANACONDA_ARMOUR_MIRRORED,
            ANACONDA_ARMOUR_REACTIVE,
            FEDERATION_CORVETTE_ARMOUR_GRADE_1,
            FEDERATION_CORVETTE_ARMOUR_GRADE_2,
            FEDERATION_CORVETTE_ARMOUR_GRADE_3,
            FEDERATION_CORVETTE_ARMOUR_MIRRORED,
            FEDERATION_CORVETTE_ARMOUR_REACTIVE,
            CUTTER_ARMOUR_GRADE_1,
            CUTTER_ARMOUR_GRADE_2,
            CUTTER_ARMOUR_GRADE_3,
            CUTTER_ARMOUR_MIRRORED,
            CUTTER_ARMOUR_REACTIVE
    );
    @Getter
    private final ShipType shipType;

    private Armour(final ShipType shipType, final HorizonsBlueprintName name, final ModuleSize moduleSize, final ModuleClass moduleClass, final int basePrice, final String internalName, final Map<HorizonsModifier, Object> attributes) {
        super(name, moduleSize, moduleClass, basePrice, internalName, attributes);
        this.shipType = shipType;
    }

    public Armour(final Armour armour) {
        super(armour);
        this.shipType = armour.shipType;
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return List.of(HorizonsBlueprintType.BLAST_RESISTANT,HorizonsBlueprintType.HEAVY_DUTY, HorizonsBlueprintType.KINETIC_RESISTANT, HorizonsBlueprintType.THERMAL_RESISTANT, HorizonsBlueprintType.LIGHTWEIGHT);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return List.of(HorizonsBlueprintType.ANGLED_PLATING,HorizonsBlueprintType.LAYERED_PLATING, HorizonsBlueprintType.DEEP_PLATING, HorizonsBlueprintType.REFLECTIVE_PLATING);
    }
    @Override
    public Armour Clone(){
        return new Armour(this);
    }
}
