package nl.jixxed.eliteodysseymaterials.domain.ships.core_internals;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.core_internals.FSDBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.CoreModule;
import nl.jixxed.eliteodysseymaterials.domain.ships.Modification;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleClass;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleSize;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.List;
import java.util.Map;

public class FrameShiftDrive extends CoreModule {
// 43250 : { mtype:'cfsd', cost:     1980, name:'Frame Shift Drive', class:2, rating:'E', mass:  2.50, integ: 46, pwrdraw:0.16, boottime:10, fsdoptmass:  48.0, fsdheat:10.0, maxfuel: 0.60, fuelmul:0.011, fuelpower:2.00, fdid:128064103, fdname:'Int_Hyperdrive_Size2_Class1', eddbid:961 },
// 43240 : { mtype:'cfsd', cost:     5930, name:'Frame Shift Drive', class:2, rating:'D', mass:  1.00, integ: 41, pwrdraw:0.18, boottime:10, fsdoptmass:  54.0, fsdheat:10.0, maxfuel: 0.60, fuelmul:0.010, fuelpower:2.00, fdid:128064104, fdname:'Int_Hyperdrive_Size2_Class2', eddbid:962 },
// 43230 : { mtype:'cfsd', cost:    17800, name:'Frame Shift Drive', class:2, rating:'C', mass:  2.50, integ: 51, pwrdraw:0.20, boottime:10, fsdoptmass:  60.0, fsdheat:10.0, maxfuel: 0.60, fuelmul:0.008, fuelpower:2.00, fdid:128064105, fdname:'Int_Hyperdrive_Size2_Class3', eddbid:963 },
// 43220 : { mtype:'cfsd', cost:    53410, name:'Frame Shift Drive', class:2, rating:'B', mass:  4.00, integ: 77, pwrdraw:0.25, boottime:10, fsdoptmass:  75.0, fsdheat:10.0, maxfuel: 0.80, fuelmul:0.010, fuelpower:2.00, fdid:128064106, fdname:'Int_Hyperdrive_Size2_Class4', eddbid:964 },
// 43210 : { mtype:'cfsd', cost:   160220, name:'Frame Shift Drive', class:2, rating:'A', mass:  2.50, integ: 64, pwrdraw:0.30, boottime:10, fsdoptmass:  90.0, fsdheat:10.0, maxfuel: 0.90, fuelmul:0.012, fuelpower:2.00, fdid:128064107, fdname:'Int_Hyperdrive_Size2_Class5', eddbid:965 },
// 43350 : { mtype:'cfsd', cost:     6270, name:'Frame Shift Drive', class:3, rating:'E', mass:  5.00, integ: 58, pwrdraw:0.24, boottime:10, fsdoptmass:  80.0, fsdheat:14.0, maxfuel: 1.20, fuelmul:0.011, fuelpower:2.15, fdid:128064108, fdname:'Int_Hyperdrive_Size3_Class1', eddbid:966 },
// 43340 : { mtype:'cfsd', cost:    18810, name:'Frame Shift Drive', class:3, rating:'D', mass:  2.00, integ: 51, pwrdraw:0.27, boottime:10, fsdoptmass:  90.0, fsdheat:14.0, maxfuel: 1.20, fuelmul:0.010, fuelpower:2.15, fdid:128064109, fdname:'Int_Hyperdrive_Size3_Class2', eddbid:967 },
// 43330 : { mtype:'cfsd', cost:    56440, name:'Frame Shift Drive', class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw:0.30, boottime:10, fsdoptmass: 100.0, fsdheat:14.0, maxfuel: 1.20, fuelmul:0.008, fuelpower:2.15, fdid:128064110, fdname:'Int_Hyperdrive_Size3_Class3', eddbid:968 },
// 43320 : { mtype:'cfsd', cost:   169300, name:'Frame Shift Drive', class:3, rating:'B', mass:  8.00, integ: 96, pwrdraw:0.38, boottime:10, fsdoptmass: 125.0, fsdheat:14.0, maxfuel: 1.50, fuelmul:0.010, fuelpower:2.15, fdid:128064111, fdname:'Int_Hyperdrive_Size3_Class4', eddbid:969 },
// 43310 : { mtype:'cfsd', cost:   507910, name:'Frame Shift Drive', class:3, rating:'A', mass:  5.00, integ: 80, pwrdraw:0.45, boottime:10, fsdoptmass: 150.0, fsdheat:14.0, maxfuel: 1.80, fuelmul:0.012, fuelpower:2.15, fdid:128064112, fdname:'Int_Hyperdrive_Size3_Class5', eddbid:970 },
// 43450 : { mtype:'cfsd', cost:    19880, name:'Frame Shift Drive', class:4, rating:'E', mass: 10.00, integ: 72, pwrdraw:0.24, boottime:10, fsdoptmass: 280.0, fsdheat:18.0, maxfuel: 2.00, fuelmul:0.011, fuelpower:2.30, fdid:128064113, fdname:'Int_Hyperdrive_Size4_Class1', eddbid:971 },
// 43440 : { mtype:'cfsd', cost:    59630, name:'Frame Shift Drive', class:4, rating:'D', mass:  4.00, integ: 64, pwrdraw:0.27, boottime:10, fsdoptmass: 315.0, fsdheat:18.0, maxfuel: 2.00, fuelmul:0.010, fuelpower:2.30, fdid:128064114, fdname:'Int_Hyperdrive_Size4_Class2', eddbid:972 },
// 43430 : { mtype:'cfsd', cost:   178900, name:'Frame Shift Drive', class:4, rating:'C', mass: 10.00, integ: 80, pwrdraw:0.30, boottime:10, fsdoptmass: 350.0, fsdheat:18.0, maxfuel: 2.00, fuelmul:0.008, fuelpower:2.30, fdid:128064115, fdname:'Int_Hyperdrive_Size4_Class3', eddbid:973 },
// 43420 : { mtype:'cfsd', cost:   536690, name:'Frame Shift Drive', class:4, rating:'B', mass: 16.00, integ:120, pwrdraw:0.38, boottime:10, fsdoptmass: 438.0, fsdheat:18.0, maxfuel: 2.50, fuelmul:0.010, fuelpower:2.30, fdid:128064116, fdname:'Int_Hyperdrive_Size4_Class4', eddbid:974 },
// 43410 : { mtype:'cfsd', cost:  1610080, name:'Frame Shift Drive', class:4, rating:'A', mass: 10.00, integ:100, pwrdraw:0.45, boottime:10, fsdoptmass: 525.0, fsdheat:18.0, maxfuel: 3.00, fuelmul:0.012, fuelpower:2.30, fdid:128064117, fdname:'Int_Hyperdrive_Size4_Class5', eddbid:975 },
// 43550 : { mtype:'cfsd', cost:    63010, name:'Frame Shift Drive', class:5, rating:'E', mass: 20.00, integ: 86, pwrdraw:0.32, boottime:10, fsdoptmass: 560.0, fsdheat:27.0, maxfuel: 3.30, fuelmul:0.011, fuelpower:2.45, fdid:128064118, fdname:'Int_Hyperdrive_Size5_Class1', eddbid:976 },
// 43540 : { mtype:'cfsd', cost:   189040, name:'Frame Shift Drive', class:5, rating:'D', mass:  8.00, integ: 77, pwrdraw:0.36, boottime:10, fsdoptmass: 630.0, fsdheat:27.0, maxfuel: 3.30, fuelmul:0.010, fuelpower:2.45, fdid:128064119, fdname:'Int_Hyperdrive_Size5_Class2', eddbid:977 },
// 43530 : { mtype:'cfsd', cost:   567110, name:'Frame Shift Drive', class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw:0.40, boottime:10, fsdoptmass: 700.0, fsdheat:27.0, maxfuel: 3.30, fuelmul:0.008, fuelpower:2.45, fdid:128064120, fdname:'Int_Hyperdrive_Size5_Class3', eddbid:978 },
// 43520 : { mtype:'cfsd', cost:  1701320, name:'Frame Shift Drive', class:5, rating:'B', mass: 32.00, integ:144, pwrdraw:0.50, boottime:10, fsdoptmass: 875.0, fsdheat:27.0, maxfuel: 4.10, fuelmul:0.010, fuelpower:2.45, fdid:128064121, fdname:'Int_Hyperdrive_Size5_Class4', eddbid:979 },
// 43510 : { mtype:'cfsd', cost:  5103950, name:'Frame Shift Drive', class:5, rating:'A', mass: 20.00, integ:120, pwrdraw:0.60, boottime:10, fsdoptmass:1050.0, fsdheat:27.0, maxfuel: 5.00, fuelmul:0.012, fuelpower:2.45, fdid:128064122, fdname:'Int_Hyperdrive_Size5_Class5', eddbid:980 },
// 43650 : { mtype:'cfsd', cost:   199750, name:'Frame Shift Drive', class:6, rating:'E', mass: 40.00, integ:102, pwrdraw:0.40, boottime:10, fsdoptmass: 960.0, fsdheat:37.0, maxfuel: 5.30, fuelmul:0.011, fuelpower:2.60, fdid:128064123, fdname:'Int_Hyperdrive_Size6_Class1', eddbid:981 },
// 43640 : { mtype:'cfsd', cost:   599240, name:'Frame Shift Drive', class:6, rating:'D', mass: 16.00, integ: 90, pwrdraw:0.45, boottime:10, fsdoptmass:1080.0, fsdheat:37.0, maxfuel: 5.30, fuelmul:0.010, fuelpower:2.60, fdid:128064124, fdname:'Int_Hyperdrive_Size6_Class2', eddbid:982 },
// 43630 : { mtype:'cfsd', cost:  1797730, name:'Frame Shift Drive', class:6, rating:'C', mass: 40.00, integ:113, pwrdraw:0.50, boottime:10, fsdoptmass:1200.0, fsdheat:37.0, maxfuel: 5.30, fuelmul:0.008, fuelpower:2.60, fdid:128064125, fdname:'Int_Hyperdrive_Size6_Class3', eddbid:983 },
// 43620 : { mtype:'cfsd', cost:  5393180, name:'Frame Shift Drive', class:6, rating:'B', mass: 64.00, integ:170, pwrdraw:0.63, boottime:10, fsdoptmass:1500.0, fsdheat:37.0, maxfuel: 6.60, fuelmul:0.010, fuelpower:2.60, fdid:128064126, fdname:'Int_Hyperdrive_Size6_Class4', eddbid:984 },
// 43610 : { mtype:'cfsd', cost: 16179530, name:'Frame Shift Drive', class:6, rating:'A', mass: 40.00, integ:141, pwrdraw:0.75, boottime:10, fsdoptmass:1800.0, fsdheat:37.0, maxfuel: 8.00, fuelmul:0.012, fuelpower:2.60, fdid:128064127, fdname:'Int_Hyperdrive_Size6_Class5', eddbid:985 },
// 43750 : { mtype:'cfsd', cost:   633200, name:'Frame Shift Drive', class:7, rating:'E', mass: 80.00, integ:118, pwrdraw:0.48, boottime:10, fsdoptmass:1440.0, fsdheat:43.0, maxfuel: 8.50, fuelmul:0.011, fuelpower:2.75, fdid:128064128, fdname:'Int_Hyperdrive_Size7_Class1', eddbid:986 },
// 43740 : { mtype:'cfsd', cost:  1899600, name:'Frame Shift Drive', class:7, rating:'D', mass: 32.00, integ:105, pwrdraw:0.54, boottime:10, fsdoptmass:1620.0, fsdheat:43.0, maxfuel: 8.50, fuelmul:0.010, fuelpower:2.75, fdid:128064129, fdname:'Int_Hyperdrive_Size7_Class2', eddbid:987 },
// 43730 : { mtype:'cfsd', cost:  5698790, name:'Frame Shift Drive', class:7, rating:'C', mass: 80.00, integ:131, pwrdraw:0.60, boottime:10, fsdoptmass:1800.0, fsdheat:43.0, maxfuel: 8.50, fuelmul:0.008, fuelpower:2.75, fdid:128064130, fdname:'Int_Hyperdrive_Size7_Class3', eddbid:988 },
// 43720 : { mtype:'cfsd', cost: 17096370, name:'Frame Shift Drive', class:7, rating:'B', mass:128.00, integ:197, pwrdraw:0.75, boottime:10, fsdoptmass:2250.0, fsdheat:43.0, maxfuel:10.60, fuelmul:0.010, fuelpower:2.75, fdid:128064131, fdname:'Int_Hyperdrive_Size7_Class4', eddbid:989 },
// 43710 : { mtype:'cfsd', cost: 51289110, name:'Frame Shift Drive', class:7, rating:'A', mass: 80.00, integ:164, pwrdraw:0.90, boottime:10, fsdoptmass:2700.0, fsdheat:43.0, maxfuel:12.80, fuelmul:0.012, fuelpower:2.75, fdid:128064132, fdname:'Int_Hyperdrive_Size7_Class5', eddbid:990 },

    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_2_E = new FrameShiftDrive("FRAME_SHIFT_DRIVE_2_E", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_2, ModuleClass.E, 1980, "Int_Hyperdrive_Size2_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 46.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.16), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 48.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 10.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 0.60), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.011), Map.entry(HorizonsModifier.FUEL_POWER, 2.00)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_2_D = new FrameShiftDrive("FRAME_SHIFT_DRIVE_2_D", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_2, ModuleClass.D, 5930, "Int_Hyperdrive_Size2_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.00), Map.entry(HorizonsModifier.INTEGRITY, 41.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.18), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 54.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 10.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 0.60), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.00)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_2_C = new FrameShiftDrive("FRAME_SHIFT_DRIVE_2_C", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_2, ModuleClass.C, 17800, "Int_Hyperdrive_Size2_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.20), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 60.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 10.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 0.60), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.008), Map.entry(HorizonsModifier.FUEL_POWER, 2.00)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_2_B = new FrameShiftDrive("FRAME_SHIFT_DRIVE_2_B", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_2, ModuleClass.B, 53410, "Int_Hyperdrive_Size2_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY, 77.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.25), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 75.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 10.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 0.80), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.00)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_2_A = new FrameShiftDrive("FRAME_SHIFT_DRIVE_2_A", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_2, ModuleClass.A, 160220, "Int_Hyperdrive_Size2_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.30), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 90.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 10.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 0.90), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.00)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_3_E = new FrameShiftDrive("FRAME_SHIFT_DRIVE_3_E", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_3, ModuleClass.E, 6270, "Int_Hyperdrive_Size3_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 58.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.24), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 80.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 14.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 1.20), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.011), Map.entry(HorizonsModifier.FUEL_POWER, 2.15)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_3_D = new FrameShiftDrive("FRAME_SHIFT_DRIVE_3_D", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_3, ModuleClass.D, 18810, "Int_Hyperdrive_Size3_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.27), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 90.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 14.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 1.20), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.15)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_3_C = new FrameShiftDrive("FRAME_SHIFT_DRIVE_3_C", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_3, ModuleClass.C, 56440, "Int_Hyperdrive_Size3_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.30), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 100.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 14.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 1.20), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.008), Map.entry(HorizonsModifier.FUEL_POWER, 2.15)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_3_B = new FrameShiftDrive("FRAME_SHIFT_DRIVE_3_B", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_3, ModuleClass.B, 169300, "Int_Hyperdrive_Size3_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY, 96.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.38), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 125.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 14.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 1.50), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.15)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_3_A = new FrameShiftDrive("FRAME_SHIFT_DRIVE_3_A", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_3, ModuleClass.A, 507910, "Int_Hyperdrive_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 80.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.45), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 150.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 14.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 1.80), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.15)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_4_E = new FrameShiftDrive("FRAME_SHIFT_DRIVE_4_E", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_4, ModuleClass.E, 19880, "Int_Hyperdrive_Size4_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 72.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.24), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 280.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 18.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 2.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.011), Map.entry(HorizonsModifier.FUEL_POWER, 2.30)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_4_D = new FrameShiftDrive("FRAME_SHIFT_DRIVE_4_D", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_4, ModuleClass.D, 59630, "Int_Hyperdrive_Size4_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.27), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 315.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 18.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 2.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.30)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_4_C = new FrameShiftDrive("FRAME_SHIFT_DRIVE_4_C", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_4, ModuleClass.C, 178900, "Int_Hyperdrive_Size4_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 80.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.30), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 350.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 18.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 2.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.008), Map.entry(HorizonsModifier.FUEL_POWER, 2.30)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_4_B = new FrameShiftDrive("FRAME_SHIFT_DRIVE_4_B", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_4, ModuleClass.B, 536690, "Int_Hyperdrive_Size4_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 16.00), Map.entry(HorizonsModifier.INTEGRITY, 120.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.38), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 438.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 18.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 2.50), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.30)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_4_A = new FrameShiftDrive("FRAME_SHIFT_DRIVE_4_A", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_4, ModuleClass.A, 1610080, "Int_Hyperdrive_Size4_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 100.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.45), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 525.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 18.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 3.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.30)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_5_E = new FrameShiftDrive("FRAME_SHIFT_DRIVE_5_E", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_5, ModuleClass.E, 63010, "Int_Hyperdrive_Size5_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 86.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.32), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 560.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 27.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 3.30), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.011), Map.entry(HorizonsModifier.FUEL_POWER, 2.45)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_5_D = new FrameShiftDrive("FRAME_SHIFT_DRIVE_5_D", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_5, ModuleClass.D, 189040, "Int_Hyperdrive_Size5_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY, 77.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.36), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 630.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 27.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 3.30), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.45)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_5_C = new FrameShiftDrive("FRAME_SHIFT_DRIVE_5_C", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_5, ModuleClass.C, 567110, "Int_Hyperdrive_Size5_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 96.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.40), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 700.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 27.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 3.30), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.008), Map.entry(HorizonsModifier.FUEL_POWER, 2.45)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_5_B = new FrameShiftDrive("FRAME_SHIFT_DRIVE_5_B", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_5, ModuleClass.B, 1701320, "Int_Hyperdrive_Size5_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 32.00), Map.entry(HorizonsModifier.INTEGRITY, 144.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.50), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 875.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 27.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 4.10), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.45)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_5_A = new FrameShiftDrive("FRAME_SHIFT_DRIVE_5_A", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_5, ModuleClass.A, 5103950, "Int_Hyperdrive_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 120.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.60), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1050.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 27.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 5.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.45)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_6_E = new FrameShiftDrive("FRAME_SHIFT_DRIVE_6_E", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_6, ModuleClass.E, 199750, "Int_Hyperdrive_Size6_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 102.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.40), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 960.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 37.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 5.30), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.011), Map.entry(HorizonsModifier.FUEL_POWER, 2.60)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_6_D = new FrameShiftDrive("FRAME_SHIFT_DRIVE_6_D", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_6, ModuleClass.D, 599240, "Int_Hyperdrive_Size6_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 16.00), Map.entry(HorizonsModifier.INTEGRITY, 90.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.45), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1080.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 37.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 5.30), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.60)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_6_C = new FrameShiftDrive("FRAME_SHIFT_DRIVE_6_C", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_6, ModuleClass.C, 1797730, "Int_Hyperdrive_Size6_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 113.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.50), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1200.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 37.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 5.30), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.008), Map.entry(HorizonsModifier.FUEL_POWER, 2.60)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_6_B = new FrameShiftDrive("FRAME_SHIFT_DRIVE_6_B", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_6, ModuleClass.B, 5393180, "Int_Hyperdrive_Size6_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 64.00), Map.entry(HorizonsModifier.INTEGRITY, 170.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.63), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1500.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 37.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 6.60), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.60)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_6_A = new FrameShiftDrive("FRAME_SHIFT_DRIVE_6_A", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_6, ModuleClass.A, 16179530, "Int_Hyperdrive_Size6_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 141.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.75), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1800.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 37.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 8.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.60)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_7_E = new FrameShiftDrive("FRAME_SHIFT_DRIVE_7_E", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_7, ModuleClass.E, 633200, "Int_Hyperdrive_Size7_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 118.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.48), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1440.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 43.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 8.50), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.011), Map.entry(HorizonsModifier.FUEL_POWER, 2.75)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_7_D = new FrameShiftDrive("FRAME_SHIFT_DRIVE_7_D", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_7, ModuleClass.D, 1899600, "Int_Hyperdrive_Size7_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 32.00), Map.entry(HorizonsModifier.INTEGRITY, 105.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.54), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1620.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 43.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 8.50), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.75)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_7_C = new FrameShiftDrive("FRAME_SHIFT_DRIVE_7_C", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_7, ModuleClass.C, 5698790, "Int_Hyperdrive_Size7_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 131.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.60), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1800.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 43.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 8.50), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.008), Map.entry(HorizonsModifier.FUEL_POWER, 2.75)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_7_B = new FrameShiftDrive("FRAME_SHIFT_DRIVE_7_B", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_7, ModuleClass.B, 17096370, "Int_Hyperdrive_Size7_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 128.00), Map.entry(HorizonsModifier.INTEGRITY, 197.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.75), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 2250.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 43.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 10.60), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.010), Map.entry(HorizonsModifier.FUEL_POWER, 2.75)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_7_A = new FrameShiftDrive("FRAME_SHIFT_DRIVE_7_A", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_7, ModuleClass.A, 51289110, "Int_Hyperdrive_Size7_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 164.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.90), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 2700.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 43.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 12.80), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.75)));
    public static final FrameShiftDrive FRAME_SHIFT_DRIVE_5_A_V1_PRE = new FrameShiftDrive("FRAME_SHIFT_DRIVE_5_A_V1_PRE", HorizonsBlueprintName.FRAME_SHIFT_DRIVE, ModuleSize.SIZE_5, ModuleClass.A, 5103950, "Int_Hyperdrive_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 120.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.60), Map.entry(HorizonsModifier.BOOT_TIME, 10.0), Map.entry(HorizonsModifier.FSD_OPTIMISED_MASS, 1050.0), Map.entry(HorizonsModifier.FSD_HEAT_RATE, 27.0), Map.entry(HorizonsModifier.MAX_FUEL_PER_JUMP, 5.00), Map.entry(HorizonsModifier.FUEL_MULTIPLIER, 0.012), Map.entry(HorizonsModifier.FUEL_POWER, 2.45)));

    static {
        FRAME_SHIFT_DRIVE_5_A_V1_PRE.getModifications().addAll(
            List.of(
                new Modification(HorizonsBlueprintType.FASTER_FSD_BOOT_SEQUENCE, 1.0, HorizonsBlueprintGrade.GRADE_5),
                new Modification(HorizonsBlueprintType.INCREASED_FSD_RANGE, 1.0, HorizonsBlueprintGrade.GRADE_5)
            )
        );
    }

    public static final List<FrameShiftDrive> FRAME_SHIFT_DRIVES = List.of(
            FRAME_SHIFT_DRIVE_2_E,
            FRAME_SHIFT_DRIVE_2_D,
            FRAME_SHIFT_DRIVE_2_C,
            FRAME_SHIFT_DRIVE_2_B,
            FRAME_SHIFT_DRIVE_2_A,
            FRAME_SHIFT_DRIVE_3_E,
            FRAME_SHIFT_DRIVE_3_D,
            FRAME_SHIFT_DRIVE_3_C,
            FRAME_SHIFT_DRIVE_3_B,
            FRAME_SHIFT_DRIVE_3_A,
            FRAME_SHIFT_DRIVE_4_E,
            FRAME_SHIFT_DRIVE_4_D,
            FRAME_SHIFT_DRIVE_4_C,
            FRAME_SHIFT_DRIVE_4_B,
            FRAME_SHIFT_DRIVE_4_A,
            FRAME_SHIFT_DRIVE_5_E,
            FRAME_SHIFT_DRIVE_5_D,
            FRAME_SHIFT_DRIVE_5_C,
            FRAME_SHIFT_DRIVE_5_B,
            FRAME_SHIFT_DRIVE_5_A,
            FRAME_SHIFT_DRIVE_6_E,
            FRAME_SHIFT_DRIVE_6_D,
            FRAME_SHIFT_DRIVE_6_C,
            FRAME_SHIFT_DRIVE_6_B,
            FRAME_SHIFT_DRIVE_6_A,
            FRAME_SHIFT_DRIVE_7_E,
            FRAME_SHIFT_DRIVE_7_D,
            FRAME_SHIFT_DRIVE_7_C,
            FRAME_SHIFT_DRIVE_7_B,
            FRAME_SHIFT_DRIVE_7_A,
            FRAME_SHIFT_DRIVE_5_A_V1_PRE
    );

    private FrameShiftDrive(final String id, final HorizonsBlueprintName name, final ModuleSize moduleSize, final ModuleClass moduleClass, final int basePrice, final String internalName, final Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, basePrice, internalName, attributes);
    }

    private FrameShiftDrive(final FrameShiftDrive frameShiftDrive) {
        super(frameShiftDrive);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return FSDBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return ExperimentalEffectBlueprints.FRAME_SHIFT_DRIVE.keySet().stream().toList();
    }

    @Override
    public FrameShiftDrive Clone() {
        return new FrameShiftDrive(this);
    }

    @Override
    public String getClarifier() {
        if(FRAME_SHIFT_DRIVE_5_A_V1_PRE.equals(this)){
            return " " + "Pre-engineered V1";
        }
        return super.getClarifier();
    }
    @Override
    public boolean isPreEngineered() {
        return FRAME_SHIFT_DRIVE_5_A_V1_PRE.equals(this);
    }
}
