package nl.jixxed.eliteodysseymaterials.domain.ships.core_internals;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.core_internals.PowerDistributorBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.CoreModule;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleClass;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleSize;
import nl.jixxed.eliteodysseymaterials.domain.ships.Origin;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;
import nl.jixxed.eliteodysseymaterials.service.LocaleService;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class PowerDistributor extends CoreModule {


//		      45150 : { mtype:'cpd', cost:     520, name:'Power Distributor', class:1, rating:'E', mass:  1.30, integ: 36, pwrdraw:0.32, boottime:5, wepcap:10.00, wepchg:1.20, engcap: 8.00, engchg:0.40, syscap: 8.00, syschg:0.40, fdid:128064178, fdname:'Int_PowerDistributor_Size1_Class1', eddbid:1036 },
//            45140 : { mtype:'cpd', cost:    1290, name:'Power Distributor', class:1, rating:'D', mass:  0.50, integ: 32, pwrdraw:0.36, boottime:5, wepcap:11.00, wepchg:1.40, engcap: 9.00, engchg:0.50, syscap: 9.00, syschg:0.50, fdid:128064179, fdname:'Int_PowerDistributor_Size1_Class2', eddbid:1037 },
//            45130 : { mtype:'cpd', cost:    3230, name:'Power Distributor', class:1, rating:'C', mass:  1.30, integ: 40, pwrdraw:0.40, boottime:5, wepcap:12.00, wepchg:1.50, engcap:10.00, engchg:0.50, syscap:10.00, syschg:0.50, fdid:128064180, fdname:'Int_PowerDistributor_Size1_Class3', eddbid:1038 },
//            45120 : { mtype:'cpd', cost:    8080, name:'Power Distributor', class:1, rating:'B', mass:  2.00, integ: 48, pwrdraw:0.44, boottime:5, wepcap:13.00, wepchg:1.70, engcap:11.00, engchg:0.60, syscap:11.00, syschg:0.60, fdid:128064181, fdname:'Int_PowerDistributor_Size1_Class4', eddbid:1039 },
//            45110 : { mtype:'cpd', cost:   20200, name:'Power Distributor', class:1, rating:'A', mass:  1.30, integ: 44, pwrdraw:0.48, boottime:5, wepcap:14.00, wepchg:1.80, engcap:12.00, engchg:0.60, syscap:12.00, syschg:0.60, fdid:128064182, fdname:'Int_PowerDistributor_Size1_Class5', eddbid:1040 },
//            45250 : { mtype:'cpd', cost:    1450, name:'Power Distributor', class:2, rating:'E', mass:  2.50, integ: 46, pwrdraw:0.36, boottime:5, wepcap:12.00, wepchg:1.40, engcap:10.00, engchg:0.60, syscap:10.00, syschg:0.60, fdid:128064183, fdname:'Int_PowerDistributor_Size2_Class1', eddbid:1041 },
//            45240 : { mtype:'cpd', cost:    3620, name:'Power Distributor', class:2, rating:'D', mass:  1.00, integ: 41, pwrdraw:0.41, boottime:5, wepcap:14.00, wepchg:1.60, engcap:11.00, engchg:0.60, syscap:11.00, syschg:0.60, fdid:128064184, fdname:'Int_PowerDistributor_Size2_Class2', eddbid:1042 },
//            45230 : { mtype:'cpd', cost:    9050, name:'Power Distributor', class:2, rating:'C', mass:  2.50, integ: 51, pwrdraw:0.45, boottime:5, wepcap:15.00, wepchg:1.80, engcap:12.00, engchg:0.70, syscap:12.00, syschg:0.70, fdid:128064185, fdname:'Int_PowerDistributor_Size2_Class3', eddbid:1043 },
//            45220 : { mtype:'cpd', cost:   22620, name:'Power Distributor', class:2, rating:'B', mass:  4.00, integ: 61, pwrdraw:0.50, boottime:5, wepcap:17.00, wepchg:2.00, engcap:13.00, engchg:0.80, syscap:13.00, syschg:0.80, fdid:128064186, fdname:'Int_PowerDistributor_Size2_Class4', eddbid:1044 },
//            45210 : { mtype:'cpd', cost:   56550, name:'Power Distributor', class:2, rating:'A', mass:  2.50, integ: 56, pwrdraw:0.54, boottime:5, wepcap:18.00, wepchg:2.20, engcap:14.00, engchg:0.80, syscap:14.00, syschg:0.80, fdid:128064187, fdname:'Int_PowerDistributor_Size2_Class5', eddbid:1045 },
//            45350 : { mtype:'cpd', cost:    4050, name:'Power Distributor', class:3, rating:'E', mass:  5.00, integ: 58, pwrdraw:0.40, boottime:5, wepcap:16.00, wepchg:1.80, engcap:12.00, engchg:0.90, syscap:12.00, syschg:0.90, fdid:128064188, fdname:'Int_PowerDistributor_Size3_Class1', eddbid:1046 },
//            45340 : { mtype:'cpd', cost:   10130, name:'Power Distributor', class:3, rating:'D', mass:  2.00, integ: 51, pwrdraw:0.45, boottime:5, wepcap:18.00, wepchg:2.10, engcap:14.00, engchg:1.00, syscap:14.00, syschg:1.00, fdid:128064189, fdname:'Int_PowerDistributor_Size3_Class2', eddbid:1047 },
//            45330 : { mtype:'cpd', cost:   25330, name:'Power Distributor', class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw:0.50, boottime:5, wepcap:20.00, wepchg:2.30, engcap:15.00, engchg:1.10, syscap:15.00, syschg:1.10, fdid:128064190, fdname:'Int_PowerDistributor_Size3_Class3', eddbid:1048 },
//            45320 : { mtype:'cpd', cost:   63330, name:'Power Distributor', class:3, rating:'B', mass:  8.00, integ: 77, pwrdraw:0.55, boottime:5, wepcap:22.00, wepchg:2.50, engcap:17.00, engchg:1.20, syscap:17.00, syschg:1.20, fdid:128064191, fdname:'Int_PowerDistributor_Size3_Class4', eddbid:1049 },
//            45310 : { mtype:'cpd', cost:  158330, name:'Power Distributor', class:3, rating:'A', mass:  5.00, integ: 70, pwrdraw:0.60, boottime:5, wepcap:24.00, wepchg:2.80, engcap:18.00, engchg:1.30, syscap:18.00, syschg:1.30, fdid:128064192, fdname:'Int_PowerDistributor_Size3_Class5', eddbid:1050 },
//            45450 : { mtype:'cpd', cost:   11350, name:'Power Distributor', class:4, rating:'E', mass: 10.00, integ: 72, pwrdraw:0.45, boottime:5, wepcap:22.00, wepchg:2.30, engcap:15.00, engchg:1.30, syscap:15.00, syschg:1.30, fdid:128064193, fdname:'Int_PowerDistributor_Size4_Class1', eddbid:1051 },
//            45440 : { mtype:'cpd', cost:   28370, name:'Power Distributor', class:4, rating:'D', mass:  4.00, integ: 64, pwrdraw:0.50, boottime:5, wepcap:24.00, wepchg:2.60, engcap:17.00, engchg:1.40, syscap:17.00, syschg:1.40, fdid:128064194, fdname:'Int_PowerDistributor_Size4_Class2', eddbid:1052 },
//            45430 : { mtype:'cpd', cost:   70930, name:'Power Distributor', class:4, rating:'C', mass: 10.00, integ: 80, pwrdraw:0.56, boottime:5, wepcap:27.00, wepchg:2.90, engcap:19.00, engchg:1.60, syscap:19.00, syschg:1.60, fdid:128064195, fdname:'Int_PowerDistributor_Size4_Class3', eddbid:1053 },
//            45420 : { mtype:'cpd', cost:  177330, name:'Power Distributor', class:4, rating:'B', mass: 16.00, integ: 96, pwrdraw:0.62, boottime:5, wepcap:30.00, wepchg:3.20, engcap:21.00, engchg:1.80, syscap:21.00, syschg:1.80, fdid:128064196, fdname:'Int_PowerDistributor_Size4_Class4', eddbid:1054 },
//            45410 : { mtype:'cpd', cost:  443330, name:'Power Distributor', class:4, rating:'A', mass: 10.00, integ: 88, pwrdraw:0.67, boottime:5, wepcap:32.00, wepchg:3.50, engcap:23.00, engchg:1.90, syscap:23.00, syschg:1.90, fdid:128064197, fdname:'Int_PowerDistributor_Size4_Class5', eddbid:1055 },
//            45550 : { mtype:'cpd', cost:   31780, name:'Power Distributor', class:5, rating:'E', mass: 20.00, integ: 86, pwrdraw:0.50, boottime:5, wepcap:27.00, wepchg:2.90, engcap:19.00, engchg:1.70, syscap:19.00, syschg:1.70, fdid:128064198, fdname:'Int_PowerDistributor_Size5_Class1', eddbid:1056 },
//            45540 : { mtype:'cpd', cost:   79440, name:'Power Distributor', class:5, rating:'D', mass:  8.00, integ: 77, pwrdraw:0.56, boottime:5, wepcap:31.00, wepchg:3.20, engcap:22.00, engchg:1.90, syscap:22.00, syschg:1.90, fdid:128064199, fdname:'Int_PowerDistributor_Size5_Class2', eddbid:1057 },
//            45530 : { mtype:'cpd', cost:  198610, name:'Power Distributor', class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw:0.62, boottime:5, wepcap:34.00, wepchg:3.60, engcap:24.00, engchg:2.10, syscap:24.00, syschg:2.10, fdid:128064200, fdname:'Int_PowerDistributor_Size5_Class3', eddbid:1058 },
//            45520 : { mtype:'cpd', cost:  496530, name:'Power Distributor', class:5, rating:'B', mass: 32.00, integ:115, pwrdraw:0.68, boottime:5, wepcap:37.00, wepchg:4.00, engcap:26.00, engchg:2.30, syscap:26.00, syschg:2.30, fdid:128064201, fdname:'Int_PowerDistributor_Size5_Class4', eddbid:1059 },
//            45510 : { mtype:'cpd', cost: 1241320, name:'Power Distributor', class:5, rating:'A', mass: 20.00, integ:106, pwrdraw:0.74, boottime:5, wepcap:41.00, wepchg:4.30, engcap:29.00, engchg:2.50, syscap:29.00, syschg:2.50, fdid:128064202, fdname:'Int_PowerDistributor_Size5_Class5', eddbid:1060 },
//            45650 : { mtype:'cpd', cost:   88980, name:'Power Distributor', class:6, rating:'E', mass: 40.00, integ:102, pwrdraw:0.54, boottime:5, wepcap:34.00, wepchg:3.40, engcap:23.00, engchg:2.20, syscap:23.00, syschg:2.20, fdid:128064203, fdname:'Int_PowerDistributor_Size6_Class1', eddbid:1061 },
//            45640 : { mtype:'cpd', cost:  222440, name:'Power Distributor', class:6, rating:'D', mass: 16.00, integ: 90, pwrdraw:0.61, boottime:5, wepcap:38.00, wepchg:3.90, engcap:26.00, engchg:2.40, syscap:26.00, syschg:2.40, fdid:128064204, fdname:'Int_PowerDistributor_Size6_Class2', eddbid:1062 },
//            45630 : { mtype:'cpd', cost:  556110, name:'Power Distributor', class:6, rating:'C', mass: 40.00, integ:113, pwrdraw:0.68, boottime:5, wepcap:42.00, wepchg:4.30, engcap:29.00, engchg:2.70, syscap:29.00, syschg:2.70, fdid:128064205, fdname:'Int_PowerDistributor_Size6_Class3', eddbid:1063 },
//            45620 : { mtype:'cpd', cost: 1390280, name:'Power Distributor', class:6, rating:'B', mass: 64.00, integ:136, pwrdraw:0.75, boottime:5, wepcap:46.00, wepchg:4.70, engcap:32.00, engchg:3.00, syscap:32.00, syschg:3.00, fdid:128064206, fdname:'Int_PowerDistributor_Size6_Class4', eddbid:1064 },
//            45610 : { mtype:'cpd', cost: 3475690, name:'Power Distributor', class:6, rating:'A', mass: 40.00, integ:124, pwrdraw:0.82, boottime:5, wepcap:50.00, wepchg:5.20, engcap:35.00, engchg:3.20, syscap:35.00, syschg:3.20, fdid:128064207, fdname:'Int_PowerDistributor_Size6_Class5', eddbid:1065 },
//            45750 : { mtype:'cpd', cost:  249140, name:'Power Distributor', class:7, rating:'E', mass: 80.00, integ:118, pwrdraw:0.59, boottime:5, wepcap:41.00, wepchg:4.10, engcap:27.00, engchg:2.60, syscap:27.00, syschg:2.60, fdid:128064208, fdname:'Int_PowerDistributor_Size7_Class1', eddbid:1066 },
//            45740 : { mtype:'cpd', cost:  622840, name:'Power Distributor', class:7, rating:'D', mass: 32.00, integ:105, pwrdraw:0.67, boottime:5, wepcap:46.00, wepchg:4.60, engcap:31.00, engchg:3.00, syscap:31.00, syschg:3.00, fdid:128064209, fdname:'Int_PowerDistributor_Size7_Class2', eddbid:1067 },
//            45730 : { mtype:'cpd', cost: 1557110, name:'Power Distributor', class:7, rating:'C', mass: 80.00, integ:131, pwrdraw:0.74, boottime:5, wepcap:51.00, wepchg:5.10, engcap:34.00, engchg:3.30, syscap:34.00, syschg:3.30, fdid:128064210, fdname:'Int_PowerDistributor_Size7_Class3', eddbid:1068 },
//            45720 : { mtype:'cpd', cost: 3892770, name:'Power Distributor', class:7, rating:'B', mass:128.00, integ:157, pwrdraw:0.81, boottime:5, wepcap:56.00, wepchg:5.60, engcap:37.00, engchg:3.60, syscap:37.00, syschg:3.60, fdid:128064211, fdname:'Int_PowerDistributor_Size7_Class4', eddbid:1069 },
//            45710 : { mtype:'cpd', cost: 9731930, name:'Power Distributor', class:7, rating:'A', mass: 80.00, integ:144, pwrdraw:0.89, boottime:5, wepcap:61.00, wepchg:6.10, engcap:41.00, engchg:4.00, syscap:41.00, syschg:4.00, fdid:128064212, fdname:'Int_PowerDistributor_Size7_Class5', eddbid:1070 },
//            45850 : { mtype:'cpd', cost:  697580, name:'Power Distributor', class:8, rating:'E', mass:160.00, integ:135, pwrdraw:0.64, boottime:5, wepcap:48.00, wepchg:4.80, engcap:32.00, engchg:3.20, syscap:32.00, syschg:3.20, fdid:128064213, fdname:'Int_PowerDistributor_Size8_Class1', eddbid:1071 },
//            45840 : { mtype:'cpd', cost: 1743960, name:'Power Distributor', class:8, rating:'D', mass: 64.00, integ:120, pwrdraw:0.72, boottime:5, wepcap:54.00, wepchg:5.40, engcap:36.00, engchg:3.60, syscap:36.00, syschg:3.60, fdid:128064214, fdname:'Int_PowerDistributor_Size8_Class2', eddbid:1072 },
//            45830 : { mtype:'cpd', cost: 4359900, name:'Power Distributor', class:8, rating:'C', mass:160.00, integ:150, pwrdraw:0.80, boottime:5, wepcap:60.00, wepchg:6.00, engcap:40.00, engchg:4.00, syscap:40.00, syschg:4.00, fdid:128064215, fdname:'Int_PowerDistributor_Size8_Class3', eddbid:1073 },
//            45820 : { mtype:'cpd', cost:10899760, name:'Power Distributor', class:8, rating:'B', mass:256.00, integ:180, pwrdraw:0.88, boottime:5, wepcap:66.00, wepchg:6.60, engcap:44.00, engchg:4.40, syscap:44.00, syschg:4.40, fdid:128064216, fdname:'Int_PowerDistributor_Size8_Class4', eddbid:1074 },
//            45810 : { mtype:'cpd', cost:27249390, name:'Power Distributor', class:8, rating:'A', mass:160.00, integ:165, pwrdraw:0.96, boottime:5, wepcap:72.00, wepchg:7.20, engcap:48.00, engchg:4.80, syscap:48.00, syschg:4.80, fdid:128064217, fdname:'Int_PowerDistributor_Size8_Class5', eddbid:1075 },
//

    public static final PowerDistributor POWER_DISTRIBUTOR_1_E = new PowerDistributor("POWER_DISTRIBUTOR_1_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_1, ModuleClass.E,      520, "Int_PowerDistributor_Size1_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   1.30), Map.entry(HorizonsModifier.INTEGRITY,  36.0), Map.entry(HorizonsModifier.POWER_DRAW,0.32), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,10.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.20), Map.entry(HorizonsModifier.ENGINES_CAPACITY, 8.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.40), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY, 8.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.40)));
    public static final PowerDistributor POWER_DISTRIBUTOR_1_D = new PowerDistributor("POWER_DISTRIBUTOR_1_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_1, ModuleClass.D,     1290, "Int_PowerDistributor_Size1_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   0.50), Map.entry(HorizonsModifier.INTEGRITY,  32.0), Map.entry(HorizonsModifier.POWER_DRAW,0.36), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,11.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.40), Map.entry(HorizonsModifier.ENGINES_CAPACITY, 9.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.50), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY, 9.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.50)));
    public static final PowerDistributor POWER_DISTRIBUTOR_1_C = new PowerDistributor("POWER_DISTRIBUTOR_1_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_1, ModuleClass.C,     3230, "Int_PowerDistributor_Size1_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   1.30), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,0.40), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,12.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.50), Map.entry(HorizonsModifier.ENGINES_CAPACITY,10.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.50), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,10.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.50)));
    public static final PowerDistributor POWER_DISTRIBUTOR_1_B = new PowerDistributor("POWER_DISTRIBUTOR_1_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_1, ModuleClass.B,     8080, "Int_PowerDistributor_Size1_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.00), Map.entry(HorizonsModifier.INTEGRITY,  48.0), Map.entry(HorizonsModifier.POWER_DRAW,0.44), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,13.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.70), Map.entry(HorizonsModifier.ENGINES_CAPACITY,11.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,11.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_1_A = new PowerDistributor("POWER_DISTRIBUTOR_1_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_1, ModuleClass.A,    20200, "Int_PowerDistributor_Size1_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   1.30), Map.entry(HorizonsModifier.INTEGRITY,  44.0), Map.entry(HorizonsModifier.POWER_DRAW,0.48), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,14.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.80), Map.entry(HorizonsModifier.ENGINES_CAPACITY,12.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,12.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_2_E = new PowerDistributor("POWER_DISTRIBUTOR_2_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_2, ModuleClass.E,     1450, "Int_PowerDistributor_Size2_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  46.0), Map.entry(HorizonsModifier.POWER_DRAW,0.36), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,12.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.40), Map.entry(HorizonsModifier.ENGINES_CAPACITY,10.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,10.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_2_D = new PowerDistributor("POWER_DISTRIBUTOR_2_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_2, ModuleClass.D,     3620, "Int_PowerDistributor_Size2_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   1.00), Map.entry(HorizonsModifier.INTEGRITY,  41.0), Map.entry(HorizonsModifier.POWER_DRAW,0.41), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,14.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.60), Map.entry(HorizonsModifier.ENGINES_CAPACITY,11.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,11.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_2_C = new PowerDistributor("POWER_DISTRIBUTOR_2_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_2, ModuleClass.C,     9050, "Int_PowerDistributor_Size2_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.45), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,15.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.80), Map.entry(HorizonsModifier.ENGINES_CAPACITY,12.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.70), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,12.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.70)));
    public static final PowerDistributor POWER_DISTRIBUTOR_2_B = new PowerDistributor("POWER_DISTRIBUTOR_2_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_2, ModuleClass.B,    22620, "Int_PowerDistributor_Size2_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   4.00), Map.entry(HorizonsModifier.INTEGRITY,  61.0), Map.entry(HorizonsModifier.POWER_DRAW,0.50), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,17.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.00), Map.entry(HorizonsModifier.ENGINES_CAPACITY,13.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.80), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,13.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.80)));
    public static final PowerDistributor POWER_DISTRIBUTOR_2_A = new PowerDistributor("POWER_DISTRIBUTOR_2_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_2, ModuleClass.A,    56550, "Int_PowerDistributor_Size2_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  56.0), Map.entry(HorizonsModifier.POWER_DRAW,0.54), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,18.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.20), Map.entry(HorizonsModifier.ENGINES_CAPACITY,14.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.80), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,14.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.80)));
    public static final PowerDistributor POWER_DISTRIBUTOR_3_E = new PowerDistributor("POWER_DISTRIBUTOR_3_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_3, ModuleClass.E,     4050, "Int_PowerDistributor_Size3_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  58.0), Map.entry(HorizonsModifier.POWER_DRAW,0.40), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,16.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,1.80), Map.entry(HorizonsModifier.ENGINES_CAPACITY,12.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.90), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,12.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.90)));
    public static final PowerDistributor POWER_DISTRIBUTOR_3_D = new PowerDistributor("POWER_DISTRIBUTOR_3_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_3, ModuleClass.D,    10130, "Int_PowerDistributor_Size3_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.00), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.45), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,18.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.10), Map.entry(HorizonsModifier.ENGINES_CAPACITY,14.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.00), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,14.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.00)));
    public static final PowerDistributor POWER_DISTRIBUTOR_3_C = new PowerDistributor("POWER_DISTRIBUTOR_3_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_3, ModuleClass.C,    25330, "Int_PowerDistributor_Size3_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.50), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,20.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.30), Map.entry(HorizonsModifier.ENGINES_CAPACITY,15.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.10), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,15.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.10)));
    public static final PowerDistributor POWER_DISTRIBUTOR_3_B = new PowerDistributor("POWER_DISTRIBUTOR_3_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_3, ModuleClass.B,    63330, "Int_PowerDistributor_Size3_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   8.00), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,0.55), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,22.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.50), Map.entry(HorizonsModifier.ENGINES_CAPACITY,17.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,17.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.20)));
    public static final PowerDistributor POWER_DISTRIBUTOR_3_A = new PowerDistributor("POWER_DISTRIBUTOR_3_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_3, ModuleClass.A,   158330, "Int_PowerDistributor_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  70.0), Map.entry(HorizonsModifier.POWER_DRAW,0.60), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,24.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.80), Map.entry(HorizonsModifier.ENGINES_CAPACITY,18.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.30), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,18.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.30)));
    public static final PowerDistributor POWER_DISTRIBUTOR_4_E = new PowerDistributor("POWER_DISTRIBUTOR_4_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_4, ModuleClass.E,    11350, "Int_PowerDistributor_Size4_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.00), Map.entry(HorizonsModifier.INTEGRITY,  72.0), Map.entry(HorizonsModifier.POWER_DRAW,0.45), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,22.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.30), Map.entry(HorizonsModifier.ENGINES_CAPACITY,15.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.30), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,15.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.30)));
    public static final PowerDistributor POWER_DISTRIBUTOR_4_D = new PowerDistributor("POWER_DISTRIBUTOR_4_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_4, ModuleClass.D,    28370, "Int_PowerDistributor_Size4_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   4.00), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.50), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,24.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.60), Map.entry(HorizonsModifier.ENGINES_CAPACITY,17.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.40), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,17.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.40)));
    public static final PowerDistributor POWER_DISTRIBUTOR_4_C = new PowerDistributor("POWER_DISTRIBUTOR_4_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_4, ModuleClass.C,    70930, "Int_PowerDistributor_Size4_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.00), Map.entry(HorizonsModifier.INTEGRITY,  80.0), Map.entry(HorizonsModifier.POWER_DRAW,0.56), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,27.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.90), Map.entry(HorizonsModifier.ENGINES_CAPACITY,19.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,19.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_4_B = new PowerDistributor("POWER_DISTRIBUTOR_4_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_4, ModuleClass.B,   177330, "Int_PowerDistributor_Size4_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  16.00), Map.entry(HorizonsModifier.INTEGRITY,  96.0), Map.entry(HorizonsModifier.POWER_DRAW,0.62), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,30.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,3.20), Map.entry(HorizonsModifier.ENGINES_CAPACITY,21.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.80), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,21.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.80)));
    public static final PowerDistributor POWER_DISTRIBUTOR_4_A = new PowerDistributor("POWER_DISTRIBUTOR_4_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_4, ModuleClass.A,   443330, "Int_PowerDistributor_Size4_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.00), Map.entry(HorizonsModifier.INTEGRITY,  88.0), Map.entry(HorizonsModifier.POWER_DRAW,0.67), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,32.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,3.50), Map.entry(HorizonsModifier.ENGINES_CAPACITY,23.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.90), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,23.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.90)));
    public static final PowerDistributor POWER_DISTRIBUTOR_5_E = new PowerDistributor("POWER_DISTRIBUTOR_5_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_5, ModuleClass.E,    31780, "Int_PowerDistributor_Size5_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.00), Map.entry(HorizonsModifier.INTEGRITY,  86.0), Map.entry(HorizonsModifier.POWER_DRAW,0.50), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,27.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,2.90), Map.entry(HorizonsModifier.ENGINES_CAPACITY,19.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.70), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,19.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.70)));
    public static final PowerDistributor POWER_DISTRIBUTOR_5_D = new PowerDistributor("POWER_DISTRIBUTOR_5_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_5, ModuleClass.D,    79440, "Int_PowerDistributor_Size5_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   8.00), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,0.56), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,31.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,3.20), Map.entry(HorizonsModifier.ENGINES_CAPACITY,22.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.90), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,22.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.90)));
    public static final PowerDistributor POWER_DISTRIBUTOR_5_C = new PowerDistributor("POWER_DISTRIBUTOR_5_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_5, ModuleClass.C,   198610, "Int_PowerDistributor_Size5_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.00), Map.entry(HorizonsModifier.INTEGRITY,  96.0), Map.entry(HorizonsModifier.POWER_DRAW,0.62), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,34.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,3.60), Map.entry(HorizonsModifier.ENGINES_CAPACITY,24.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.10), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,24.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.10)));
    public static final PowerDistributor POWER_DISTRIBUTOR_5_B = new PowerDistributor("POWER_DISTRIBUTOR_5_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_5, ModuleClass.B,   496530, "Int_PowerDistributor_Size5_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.00), Map.entry(HorizonsModifier.INTEGRITY, 115.0), Map.entry(HorizonsModifier.POWER_DRAW,0.68), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,37.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.00), Map.entry(HorizonsModifier.ENGINES_CAPACITY,26.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.30), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,26.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.30)));
    public static final PowerDistributor POWER_DISTRIBUTOR_5_A = new PowerDistributor("POWER_DISTRIBUTOR_5_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_5, ModuleClass.A,  1241320, "Int_PowerDistributor_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.00), Map.entry(HorizonsModifier.INTEGRITY, 106.0), Map.entry(HorizonsModifier.POWER_DRAW,0.74), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,41.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.30), Map.entry(HorizonsModifier.ENGINES_CAPACITY,29.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.50), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,29.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.50)));
    public static final PowerDistributor POWER_DISTRIBUTOR_6_E = new PowerDistributor("POWER_DISTRIBUTOR_6_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_6, ModuleClass.E,    88980, "Int_PowerDistributor_Size6_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  40.00), Map.entry(HorizonsModifier.INTEGRITY, 102.0), Map.entry(HorizonsModifier.POWER_DRAW,0.54), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,34.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,3.40), Map.entry(HorizonsModifier.ENGINES_CAPACITY,23.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,23.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.20)));
    public static final PowerDistributor POWER_DISTRIBUTOR_6_D = new PowerDistributor("POWER_DISTRIBUTOR_6_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_6, ModuleClass.D,   222440, "Int_PowerDistributor_Size6_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  16.00), Map.entry(HorizonsModifier.INTEGRITY,  90.0), Map.entry(HorizonsModifier.POWER_DRAW,0.61), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,38.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,3.90), Map.entry(HorizonsModifier.ENGINES_CAPACITY,26.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.40), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,26.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.40)));
    public static final PowerDistributor POWER_DISTRIBUTOR_6_C = new PowerDistributor("POWER_DISTRIBUTOR_6_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_6, ModuleClass.C,   556110, "Int_PowerDistributor_Size6_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  40.00), Map.entry(HorizonsModifier.INTEGRITY, 113.0), Map.entry(HorizonsModifier.POWER_DRAW,0.68), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,42.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.30), Map.entry(HorizonsModifier.ENGINES_CAPACITY,29.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.70), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,29.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.70)));
    public static final PowerDistributor POWER_DISTRIBUTOR_6_B = new PowerDistributor("POWER_DISTRIBUTOR_6_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_6, ModuleClass.B,  1390280, "Int_PowerDistributor_Size6_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  64.00), Map.entry(HorizonsModifier.INTEGRITY, 136.0), Map.entry(HorizonsModifier.POWER_DRAW,0.75), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,46.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.70), Map.entry(HorizonsModifier.ENGINES_CAPACITY,32.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.00), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,32.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.00)));
    public static final PowerDistributor POWER_DISTRIBUTOR_6_A = new PowerDistributor("POWER_DISTRIBUTOR_6_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_6, ModuleClass.A,  3475690, "Int_PowerDistributor_Size6_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  40.00), Map.entry(HorizonsModifier.INTEGRITY, 124.0), Map.entry(HorizonsModifier.POWER_DRAW,0.82), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,50.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,5.20), Map.entry(HorizonsModifier.ENGINES_CAPACITY,35.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,35.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.20)));
    public static final PowerDistributor POWER_DISTRIBUTOR_7_E = new PowerDistributor("POWER_DISTRIBUTOR_7_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_7, ModuleClass.E,   249140, "Int_PowerDistributor_Size7_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.00), Map.entry(HorizonsModifier.INTEGRITY, 118.0), Map.entry(HorizonsModifier.POWER_DRAW,0.59), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,41.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.10), Map.entry(HorizonsModifier.ENGINES_CAPACITY,27.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,27.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_7_D = new PowerDistributor("POWER_DISTRIBUTOR_7_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_7, ModuleClass.D,   622840, "Int_PowerDistributor_Size7_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.00), Map.entry(HorizonsModifier.INTEGRITY, 105.0), Map.entry(HorizonsModifier.POWER_DRAW,0.67), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,46.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.60), Map.entry(HorizonsModifier.ENGINES_CAPACITY,31.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.00), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,31.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.00)));
    public static final PowerDistributor POWER_DISTRIBUTOR_7_C = new PowerDistributor("POWER_DISTRIBUTOR_7_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_7, ModuleClass.C,  1557110, "Int_PowerDistributor_Size7_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.00), Map.entry(HorizonsModifier.INTEGRITY, 131.0), Map.entry(HorizonsModifier.POWER_DRAW,0.74), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,51.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,5.10), Map.entry(HorizonsModifier.ENGINES_CAPACITY,34.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.30), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,34.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.30)));
    public static final PowerDistributor POWER_DISTRIBUTOR_7_B = new PowerDistributor("POWER_DISTRIBUTOR_7_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_7, ModuleClass.B,  3892770, "Int_PowerDistributor_Size7_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 128.00), Map.entry(HorizonsModifier.INTEGRITY, 157.0), Map.entry(HorizonsModifier.POWER_DRAW,0.81), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,56.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,5.60), Map.entry(HorizonsModifier.ENGINES_CAPACITY,37.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,37.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_7_A = new PowerDistributor("POWER_DISTRIBUTOR_7_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_7, ModuleClass.A,  9731930, "Int_PowerDistributor_Size7_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.00), Map.entry(HorizonsModifier.INTEGRITY, 144.0), Map.entry(HorizonsModifier.POWER_DRAW,0.89), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,61.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,6.10), Map.entry(HorizonsModifier.ENGINES_CAPACITY,41.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,4.00), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,41.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,4.00)));
    public static final PowerDistributor POWER_DISTRIBUTOR_8_E = new PowerDistributor("POWER_DISTRIBUTOR_8_E", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_8, ModuleClass.E,   697580, "Int_PowerDistributor_Size8_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 135.0), Map.entry(HorizonsModifier.POWER_DRAW,0.64), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,48.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,4.80), Map.entry(HorizonsModifier.ENGINES_CAPACITY,32.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,32.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.20)));
    public static final PowerDistributor POWER_DISTRIBUTOR_8_D = new PowerDistributor("POWER_DISTRIBUTOR_8_D", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_8, ModuleClass.D,  1743960, "Int_PowerDistributor_Size8_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  64.00), Map.entry(HorizonsModifier.INTEGRITY, 120.0), Map.entry(HorizonsModifier.POWER_DRAW,0.72), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,54.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,5.40), Map.entry(HorizonsModifier.ENGINES_CAPACITY,36.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.60), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,36.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.60)));
    public static final PowerDistributor POWER_DISTRIBUTOR_8_C = new PowerDistributor("POWER_DISTRIBUTOR_8_C", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_8, ModuleClass.C,  4359900, "Int_PowerDistributor_Size8_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 150.0), Map.entry(HorizonsModifier.POWER_DRAW,0.80), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,60.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,6.00), Map.entry(HorizonsModifier.ENGINES_CAPACITY,40.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,4.00), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,40.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,4.00)));
    public static final PowerDistributor POWER_DISTRIBUTOR_8_B = new PowerDistributor("POWER_DISTRIBUTOR_8_B", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_8, ModuleClass.B, 10899760, "Int_PowerDistributor_Size8_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 256.00), Map.entry(HorizonsModifier.INTEGRITY, 180.0), Map.entry(HorizonsModifier.POWER_DRAW,0.88), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,66.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,6.60), Map.entry(HorizonsModifier.ENGINES_CAPACITY,44.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,4.40), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,44.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,4.40)));
    public static final PowerDistributor POWER_DISTRIBUTOR_8_A = new PowerDistributor("POWER_DISTRIBUTOR_8_A", HorizonsBlueprintName.POWER_DISTRIBUTOR, ModuleSize.SIZE_8, ModuleClass.A, 27249390, "Int_PowerDistributor_Size8_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 165.0), Map.entry(HorizonsModifier.POWER_DRAW,0.96), Map.entry(HorizonsModifier.POWER_BOOST,0.0), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,72.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,7.20), Map.entry(HorizonsModifier.ENGINES_CAPACITY,48.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,4.80), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,48.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,4.80)));

    //            45111 : { mtype:'cpd', cost:   40960, name:'Guardian Hybrid Power Distributor', tag:'G', class:1, rating:'A', mass:  1.40, integ: 35, pwrdraw:0.62, boottime:5, pwrbst:4, wepcap:10.00, wepchg: 2.50, engcap: 9.00, engchg:0.80, syscap:10.00, syschg:0.80, noblueprints:{'*':1}, fdid:128833980, fdname:'Int_GuardianPowerDistributor_Size1', eddbid:1735 }, // guardian tech broker
    //            45211 : { mtype:'cpd', cost:  111600, name:'Guardian Hybrid Power Distributor', tag:'G', class:2, rating:'A', mass:  2.60, integ: 45, pwrdraw:0.73, boottime:5, pwrbst:4, wepcap:13.00, wepchg: 3.10, engcap:11.00, engchg:1.00, syscap:11.00, syschg:1.00, noblueprints:{'*':1}, fdid:128833981, fdname:'Int_GuardianPowerDistributor_Size2', eddbid:1736 }, // guardian tech broker
    //            45311 : { mtype:'cpd', cost:  311370, name:'Guardian Hybrid Power Distributor', tag:'G', class:3, rating:'A', mass:  5.25, integ: 56, pwrdraw:0.78, boottime:5, pwrbst:4, wepcap:17.00, wepchg: 3.90, engcap:14.00, engchg:1.70, syscap:14.00, syschg:1.70, noblueprints:{'*':1}, fdid:128833982, fdname:'Int_GuardianPowerDistributor_Size3', eddbid:1737 }, // guardian tech broker
    //            45411 : { mtype:'cpd', cost:  868710, name:'Guardian Hybrid Power Distributor', tag:'G', class:4, rating:'A', mass: 10.50, integ: 70, pwrdraw:0.87, boottime:5, pwrbst:4, wepcap:22.00, wepchg: 4.90, engcap:17.00, engchg:2.50, syscap:17.00, syschg:2.50, noblueprints:{'*':1}, fdid:128833983, fdname:'Int_GuardianPowerDistributor_Size4', eddbid:1738 }, // guardian tech broker
    //            45511 : { mtype:'cpd', cost: 2423690, name:'Guardian Hybrid Power Distributor', tag:'G', class:5, rating:'A', mass: 21.00, integ: 99, pwrdraw:0.96, boottime:5, pwrbst:4, wepcap:29.00, wepchg: 6.00, engcap:22.00, engchg:3.30, syscap:22.00, syschg:3.30, noblueprints:{'*':1}, fdid:128833984, fdname:'Int_GuardianPowerDistributor_Size5', eddbid:1739 }, // guardian tech broker
    //            45611 : { mtype:'cpd', cost: 6762090, name:'Guardian Hybrid Power Distributor', tag:'G', class:6, rating:'A', mass: 42.00, integ: 99, pwrdraw:1.07, boottime:5, pwrbst:4, wepcap:35.00, wepchg: 7.30, engcap:26.00, engchg:4.20, syscap:26.00, syschg:4.20, noblueprints:{'*':1}, fdid:128833985, fdname:'Int_GuardianPowerDistributor_Size6', eddbid:1740 }, // guardian tech broker
    //            45711 : { mtype:'cpd', cost:18866230, name:'Guardian Hybrid Power Distributor', tag:'G', class:7, rating:'A', mass: 84.00, integ:115, pwrdraw:1.16, boottime:5, pwrbst:4, wepcap:43.00, wepchg: 8.50, engcap:31.00, engchg:5.20, syscap:31.00, syschg:5.20, noblueprints:{'*':1}, fdid:128833986, fdname:'Int_GuardianPowerDistributor_Size7', eddbid:1741 }, // guardian tech broker
    //            45811 : { mtype:'cpd', cost:52636790, name:'Guardian Hybrid Power Distributor', tag:'G', class:8, rating:'A', mass:168.00, integ:132, pwrdraw:1.25, boottime:5, pwrbst:4, wepcap:50.00, wepchg:10.10, engcap:36.00, engchg:6.20, syscap:36.00, syschg:6.20, noblueprints:{'*':1}, fdid:128833987, fdname:'Int_GuardianPowerDistributor_Size8', eddbid:1742 }, // guardian tech broker
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_1_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_1_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_1, ModuleClass.A, Origin.GUARDIAN,    40960, "Int_GuardianPowerDistributor_Size1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   1.40), Map.entry(HorizonsModifier.INTEGRITY,  35.0), Map.entry(HorizonsModifier.POWER_DRAW,0.62), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,10.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 2.50), Map.entry(HorizonsModifier.ENGINES_CAPACITY, 9.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,0.80), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,10.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,0.80)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_2_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_2_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_2, ModuleClass.A, Origin.GUARDIAN,   111600, "Int_GuardianPowerDistributor_Size2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.60), Map.entry(HorizonsModifier.INTEGRITY,  45.0), Map.entry(HorizonsModifier.POWER_DRAW,0.73), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,13.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 3.10), Map.entry(HorizonsModifier.ENGINES_CAPACITY,11.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.00), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,11.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.00)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_3_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_3_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_3, ModuleClass.A, Origin.GUARDIAN,   311370, "Int_GuardianPowerDistributor_Size3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.25), Map.entry(HorizonsModifier.INTEGRITY,  56.0), Map.entry(HorizonsModifier.POWER_DRAW,0.78), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,17.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 3.90), Map.entry(HorizonsModifier.ENGINES_CAPACITY,14.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,1.70), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,14.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,1.70)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_4_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_4_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_4, ModuleClass.A, Origin.GUARDIAN,   868710, "Int_GuardianPowerDistributor_Size4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.50), Map.entry(HorizonsModifier.INTEGRITY,  70.0), Map.entry(HorizonsModifier.POWER_DRAW,0.87), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,22.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 4.90), Map.entry(HorizonsModifier.ENGINES_CAPACITY,17.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,2.50), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,17.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,2.50)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_5_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_5_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_5, ModuleClass.A, Origin.GUARDIAN,  2423690, "Int_GuardianPowerDistributor_Size5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  21.00), Map.entry(HorizonsModifier.INTEGRITY,  99.0), Map.entry(HorizonsModifier.POWER_DRAW,0.96), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,29.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 6.00), Map.entry(HorizonsModifier.ENGINES_CAPACITY,22.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,3.30), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,22.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,3.30)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_6_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_6_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_6, ModuleClass.A, Origin.GUARDIAN,  6762090, "Int_GuardianPowerDistributor_Size6", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  42.00), Map.entry(HorizonsModifier.INTEGRITY,  99.0), Map.entry(HorizonsModifier.POWER_DRAW,1.07), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,35.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 7.30), Map.entry(HorizonsModifier.ENGINES_CAPACITY,26.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,4.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,26.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,4.20)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_7_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_7_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_7, ModuleClass.A, Origin.GUARDIAN, 18866230, "Int_GuardianPowerDistributor_Size7", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  84.00), Map.entry(HorizonsModifier.INTEGRITY, 115.0), Map.entry(HorizonsModifier.POWER_DRAW,1.16), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,43.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE, 8.50), Map.entry(HorizonsModifier.ENGINES_CAPACITY,31.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,5.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,31.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,5.20)));
    public static final PowerDistributor GUARDIAN_HYBRID_POWER_DISTRIBUTOR_8_A = new PowerDistributor("GUARDIAN_HYBRID_POWER_DISTRIBUTOR_8_A", HorizonsBlueprintName.GUARDIAN_POWER_DISTRIBUTOR, ModuleSize.SIZE_8, ModuleClass.A, Origin.GUARDIAN, 52636790, "Int_GuardianPowerDistributor_Size8", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 168.00), Map.entry(HorizonsModifier.INTEGRITY, 132.0), Map.entry(HorizonsModifier.POWER_DRAW,1.25), Map.entry(HorizonsModifier.POWER_BOOST,0.04), Map.entry(HorizonsModifier.BOOT_TIME,5.0), Map.entry(HorizonsModifier.WEAPONS_CAPACITY,50.00), Map.entry(HorizonsModifier.WEAPONS_RECHARGE,10.10), Map.entry(HorizonsModifier.ENGINES_CAPACITY,36.00), Map.entry(HorizonsModifier.ENGINES_RECHARGE,6.20), Map.entry(HorizonsModifier.SYSTEMS_CAPACITY,36.00), Map.entry(HorizonsModifier.SYSTEMS_RECHARGE,6.20)));

    public static final List<PowerDistributor> POWER_DISTRIBUTORS = List.of(
            POWER_DISTRIBUTOR_1_E,
            POWER_DISTRIBUTOR_1_D,
            POWER_DISTRIBUTOR_1_C,
            POWER_DISTRIBUTOR_1_B,
            POWER_DISTRIBUTOR_1_A,
            POWER_DISTRIBUTOR_2_E,
            POWER_DISTRIBUTOR_2_D,
            POWER_DISTRIBUTOR_2_C,
            POWER_DISTRIBUTOR_2_B,
            POWER_DISTRIBUTOR_2_A,
            POWER_DISTRIBUTOR_3_E,
            POWER_DISTRIBUTOR_3_D,
            POWER_DISTRIBUTOR_3_C,
            POWER_DISTRIBUTOR_3_B,
            POWER_DISTRIBUTOR_3_A,
            POWER_DISTRIBUTOR_4_E,
            POWER_DISTRIBUTOR_4_D,
            POWER_DISTRIBUTOR_4_C,
            POWER_DISTRIBUTOR_4_B,
            POWER_DISTRIBUTOR_4_A,
            POWER_DISTRIBUTOR_5_E,
            POWER_DISTRIBUTOR_5_D,
            POWER_DISTRIBUTOR_5_C,
            POWER_DISTRIBUTOR_5_B,
            POWER_DISTRIBUTOR_5_A,
            POWER_DISTRIBUTOR_6_E,
            POWER_DISTRIBUTOR_6_D,
            POWER_DISTRIBUTOR_6_C,
            POWER_DISTRIBUTOR_6_B,
            POWER_DISTRIBUTOR_6_A,
            POWER_DISTRIBUTOR_7_E,
            POWER_DISTRIBUTOR_7_D,
            POWER_DISTRIBUTOR_7_C,
            POWER_DISTRIBUTOR_7_B,
            POWER_DISTRIBUTOR_7_A,
            POWER_DISTRIBUTOR_8_E,
            POWER_DISTRIBUTOR_8_D,
            POWER_DISTRIBUTOR_8_C,
            POWER_DISTRIBUTOR_8_B,
            POWER_DISTRIBUTOR_8_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_1_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_2_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_3_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_4_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_5_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_6_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_7_A,
            GUARDIAN_HYBRID_POWER_DISTRIBUTOR_8_A
    );
    private PowerDistributor(final String id, final HorizonsBlueprintName name, final ModuleSize moduleSize, final ModuleClass moduleClass, final int basePrice, final String internalName, final Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, basePrice, internalName, attributes);
    }
    private PowerDistributor(final String id, final HorizonsBlueprintName name, final ModuleSize moduleSize, final ModuleClass moduleClass, final Origin origin, final int basePrice, final String internalName, final Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin,basePrice, internalName, attributes);
    }

    private PowerDistributor(final PowerDistributor powerDistributor) {
        super(powerDistributor);
    }


    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        if (this.getOrigin() == Origin.GUARDIAN) {
            return Collections.emptyList();
        }
        return PowerDistributorBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        if (this.getOrigin() == Origin.GUARDIAN) {
            return Collections.emptyList();
        }
        return ExperimentalEffectBlueprints.POWER_DISTRIBUTOR.keySet().stream().toList();
    }
    @Override
    public PowerDistributor Clone() {
        return new PowerDistributor(this);
    }
    @Override
    public String getClarifier() {
        return this.getOrigin() == Origin.GUARDIAN ? " " + LocaleService.getLocalizedStringForCurrentLocale("blueprint.horizons.name.guardian_power_distributor") : "";
    }
}
