package nl.jixxed.eliteodysseymaterials.domain.ships.core_internals;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.core_internals.ThrusterBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.CoreModule;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleClass;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleSize;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;
import nl.jixxed.eliteodysseymaterials.service.LocaleService;

import java.util.List;
import java.util.Map;

public class Thrusters extends CoreModule {

//            42250 : { mtype:'ct', cost:     1980, name:'Thrusters', class:2, rating:'E', mass:  2.50, integ: 46, pwrdraw: 2.00, boottime:0, engminmass:  24, engoptmass:  48, engmaxmass:  72, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064068, fdname:'Int_Engine_Size2_Class1', eddbid:926 },
//            42240 : { mtype:'ct', cost:     5930, name:'Thrusters', class:2, rating:'D', mass:  1.00, integ: 41, pwrdraw: 2.25, boottime:0, engminmass:  27, engoptmass:  54, engmaxmass:  81, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064069, fdname:'Int_Engine_Size2_Class2', eddbid:927 },
//            42230 : { mtype:'ct', cost:    17800, name:'Thrusters', class:2, rating:'C', mass:  2.50, integ: 51, pwrdraw: 2.50, boottime:0, engminmass:  30, engoptmass:  60, engmaxmass:  90, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064070, fdname:'Int_Engine_Size2_Class3', eddbid:928 },
//            42220 : { mtype:'ct', cost:    53410, name:'Thrusters', class:2, rating:'B', mass:  4.00, integ: 61, pwrdraw: 2.75, boottime:0, engminmass:  33, engoptmass:  66, engmaxmass:  99, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064071, fdname:'Int_Engine_Size2_Class4', eddbid:929 },
//            42210 : { mtype:'ct', cost:   160220, name:'Thrusters', class:2, rating:'A', mass:  2.50, integ: 56, pwrdraw: 3.00, boottime:0, engminmass:  36, engoptmass:  72, engmaxmass: 108, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064072, fdname:'Int_Engine_Size2_Class5', eddbid:930 },
//            42350 : { mtype:'ct', cost:     6270, name:'Thrusters', class:3, rating:'E', mass:  5.00, integ: 58, pwrdraw: 2.48, boottime:0, engminmass:  40, engoptmass:  80, engmaxmass: 120, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064073, fdname:'Int_Engine_Size3_Class1', eddbid:931 },
//            42340 : { mtype:'ct', cost:    18810, name:'Thrusters', class:3, rating:'D', mass:  2.00, integ: 51, pwrdraw: 2.79, boottime:0, engminmass:  45, engoptmass:  90, engmaxmass: 135, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064074, fdname:'Int_Engine_Size3_Class2', eddbid:932 },
//            42330 : { mtype:'ct', cost:    56440, name:'Thrusters', class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw: 3.10, boottime:0, engminmass:  50, engoptmass: 100, engmaxmass: 150, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064075, fdname:'Int_Engine_Size3_Class3', eddbid:933 },
//            42320 : { mtype:'ct', cost:   169300, name:'Thrusters', class:3, rating:'B', mass:  8.00, integ: 77, pwrdraw: 3.41, boottime:0, engminmass:  55, engoptmass: 110, engmaxmass: 165, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064076, fdname:'Int_Engine_Size3_Class4', eddbid:934 },
//            42310 : { mtype:'ct', cost:   507910, name:'Thrusters', class:3, rating:'A', mass:  5.00, integ: 70, pwrdraw: 3.72, boottime:0, engminmass:  60, engoptmass: 120, engmaxmass: 180, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064077, fdname:'Int_Engine_Size3_Class5', eddbid:935 },
//            42450 : { mtype:'ct', cost:    19880, name:'Thrusters', class:4, rating:'E', mass: 10.00, integ: 72, pwrdraw: 3.28, boottime:0, engminmass: 140, engoptmass: 280, engmaxmass: 420, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064078, fdname:'Int_Engine_Size4_Class1', eddbid:936 },
//            42440 : { mtype:'ct', cost:    59630, name:'Thrusters', class:4, rating:'D', mass:  4.00, integ: 64, pwrdraw: 3.69, boottime:0, engminmass: 158, engoptmass: 315, engmaxmass: 473, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064079, fdname:'Int_Engine_Size4_Class2', eddbid:937 },
//            42430 : { mtype:'ct', cost:   178900, name:'Thrusters', class:4, rating:'C', mass: 10.00, integ: 80, pwrdraw: 4.10, boottime:0, engminmass: 175, engoptmass: 350, engmaxmass: 525, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064080, fdname:'Int_Engine_Size4_Class3', eddbid:938 },
//            42420 : { mtype:'ct', cost:   536690, name:'Thrusters', class:4, rating:'B', mass: 16.00, integ: 96, pwrdraw: 4.51, boottime:0, engminmass: 193, engoptmass: 385, engmaxmass: 578, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064081, fdname:'Int_Engine_Size4_Class4', eddbid:939 },
//            42410 : { mtype:'ct', cost:  1610080, name:'Thrusters', class:4, rating:'A', mass: 10.00, integ: 88, pwrdraw: 4.92, boottime:0, engminmass: 210, engoptmass: 420, engmaxmass: 630, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064082, fdname:'Int_Engine_Size4_Class5', eddbid:940 },
//            42550 : { mtype:'ct', cost:    63010, name:'Thrusters', class:5, rating:'E', mass: 20.00, integ: 86, pwrdraw: 4.08, boottime:0, engminmass: 280, engoptmass: 560, engmaxmass: 840, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064083, fdname:'Int_Engine_Size5_Class1', eddbid:941 },
//            42540 : { mtype:'ct', cost:   189040, name:'Thrusters', class:5, rating:'D', mass:  8.00, integ: 77, pwrdraw: 4.59, boottime:0, engminmass: 315, engoptmass: 630, engmaxmass: 945, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064084, fdname:'Int_Engine_Size5_Class2', eddbid:942 },
//            42530 : { mtype:'ct', cost:   567110, name:'Thrusters', class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw: 5.10, boottime:0, engminmass: 350, engoptmass: 700, engmaxmass:1050, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064085, fdname:'Int_Engine_Size5_Class3', eddbid:943 },
//            42520 : { mtype:'ct', cost:  1701320, name:'Thrusters', class:5, rating:'B', mass: 32.00, integ:115, pwrdraw: 5.61, boottime:0, engminmass: 385, engoptmass: 770, engmaxmass:1155, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064086, fdname:'Int_Engine_Size5_Class4', eddbid:944 },
//            42510 : { mtype:'ct', cost:  5103950, name:'Thrusters', class:5, rating:'A', mass: 20.00, integ:106, pwrdraw: 6.12, boottime:0, engminmass: 420, engoptmass: 840, engmaxmass:1260, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064087, fdname:'Int_Engine_Size5_Class5', eddbid:945 },
//            42650 : { mtype:'ct', cost:   199750, name:'Thrusters', class:6, rating:'E', mass: 40.00, integ:102, pwrdraw: 5.04, boottime:0, engminmass: 480, engoptmass: 960, engmaxmass:1440, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064088, fdname:'Int_Engine_Size6_Class1', eddbid:946 },
//            42640 : { mtype:'ct', cost:   599240, name:'Thrusters', class:6, rating:'D', mass: 16.00, integ: 90, pwrdraw: 5.67, boottime:0, engminmass: 540, engoptmass:1080, engmaxmass:1620, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064089, fdname:'Int_Engine_Size6_Class2', eddbid:947 },
//            42630 : { mtype:'ct', cost:  1797730, name:'Thrusters', class:6, rating:'C', mass: 40.00, integ:113, pwrdraw: 6.30, boottime:0, engminmass: 600, engoptmass:1200, engmaxmass:1800, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064090, fdname:'Int_Engine_Size6_Class3', eddbid:948 },
//            42620 : { mtype:'ct', cost:  5393180, name:'Thrusters', class:6, rating:'B', mass: 64.00, integ:136, pwrdraw: 6.93, boottime:0, engminmass: 660, engoptmass:1320, engmaxmass:1980, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064091, fdname:'Int_Engine_Size6_Class4', eddbid:949 },
//            42610 : { mtype:'ct', cost: 16179530, name:'Thrusters', class:6, rating:'A', mass: 40.00, integ:124, pwrdraw: 7.56, boottime:0, engminmass: 720, engoptmass:1440, engmaxmass:2160, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064092, fdname:'Int_Engine_Size6_Class5', eddbid:950 },
//            42750 : { mtype:'ct', cost:   633200, name:'Thrusters', class:7, rating:'E', mass: 80.00, integ:118, pwrdraw: 6.08, boottime:0, engminmass: 720, engoptmass:1440, engmaxmass:2160, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064093, fdname:'Int_Engine_Size7_Class1', eddbid:951 },
//            42740 : { mtype:'ct', cost:  1899600, name:'Thrusters', class:7, rating:'D', mass: 32.00, integ:105, pwrdraw: 6.84, boottime:0, engminmass: 810, engoptmass:1620, engmaxmass:2430, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064094, fdname:'Int_Engine_Size7_Class2', eddbid:952 },
//            42730 : { mtype:'ct', cost:  5698790, name:'Thrusters', class:7, rating:'C', mass: 80.00, integ:131, pwrdraw: 7.60, boottime:0, engminmass: 900, engoptmass:1800, engmaxmass:2700, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064095, fdname:'Int_Engine_Size7_Class3', eddbid:953 },
//            42720 : { mtype:'ct', cost: 17096370, name:'Thrusters', class:7, rating:'B', mass:128.00, integ:157, pwrdraw: 8.36, boottime:0, engminmass: 990, engoptmass:1980, engmaxmass:2970, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064096, fdname:'Int_Engine_Size7_Class4', eddbid:954 },
//            42710 : { mtype:'ct', cost: 51289110, name:'Thrusters', class:7, rating:'A', mass: 80.00, integ:144, pwrdraw: 9.12, boottime:0, engminmass:1080, engoptmass:2160, engmaxmass:3240, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064097, fdname:'Int_Engine_Size7_Class5', eddbid:955 },
//            42850 : { mtype:'ct', cost:  2007240, name:'Thrusters', class:8, rating:'E', mass:160.00, integ:135, pwrdraw: 7.20, boottime:0, engminmass:1120, engoptmass:2240, engmaxmass:3360, engminmul:83, engoptmul:100, engmaxmul:103, engheat:1.3, fdid:128064098, fdname:'Int_Engine_Size8_Class1', eddbid:956 },
//            42840 : { mtype:'ct', cost:  6021720, name:'Thrusters', class:8, rating:'D', mass: 64.00, integ:120, pwrdraw: 8.10, boottime:0, engminmass:1260, engoptmass:2520, engmaxmass:3780, engminmul:86, engoptmul:100, engmaxmul:106, engheat:1.3, fdid:128064099, fdname:'Int_Engine_Size8_Class2', eddbid:957 },
//            42830 : { mtype:'ct', cost: 18065170, name:'Thrusters', class:8, rating:'C', mass:160.00, integ:150, pwrdraw: 9.00, boottime:0, engminmass:1400, engoptmass:2800, engmaxmass:4200, engminmul:90, engoptmul:100, engmaxmul:110, engheat:1.3, fdid:128064100, fdname:'Int_Engine_Size8_Class3', eddbid:958 },
//            42820 : { mtype:'ct', cost: 54195500, name:'Thrusters', class:8, rating:'B', mass:256.00, integ:180, pwrdraw: 9.90, boottime:0, engminmass:1540, engoptmass:3080, engmaxmass:4620, engminmul:93, engoptmul:100, engmaxmul:113, engheat:1.3, fdid:128064101, fdname:'Int_Engine_Size8_Class4', eddbid:959 },
//            42810 : { mtype:'ct', cost:162586490, name:'Thrusters', class:8, rating:'A', mass:160.00, integ:165, pwrdraw:10.80, boottime:0, engminmass:1680, engoptmass:3360, engmaxmass:5040, engminmul:96, engoptmul:100, engmaxmul:116, engheat:1.3, fdid:128064102, fdname:'Int_Engine_Size8_Class5', eddbid:960 },
    //https://forums.frontier.co.uk/threads/the-one-formula-to-rule-them-all-the-mechanics-of-shield-and-thruster-mass-curves.300225/
//            42211 : { mtype:'ct', cost:  1610080, name:'Thrusters', class:2, rating:'A', mass:  2.50, integ: 40, pwrdraw: 4.00, boottime:0, engminmass:  50, engoptmass:  60, engmaxmass: 120, engminmul:90, engoptmul:115, engmaxmul:137, engheat:2.0, fdid:128682014, fdname:'Int_Engine_Size2_Class5_Fast',  minmulspd:90, optmulspd:125, maxmulspd:160, minmulacc:90, optmulacc:110, maxmulacc:120, minmulrot:90, optmulrot:110, maxmulrot:130, eddbid:1547 },
//            42311 : { mtype:'ct', cost:  5103950, name:'Thrusters', class:3, rating:'A', mass:  5.00, integ: 55, pwrdraw: 5.00, boottime:0, engminmass:  70, engoptmass:  90, engmaxmass: 200, engminmul:90, engoptmul:115, engmaxmul:137, engheat:1.3, fdid:128682013, fdname:'Int_Engine_Size3_Class5_Fast',  minmulspd:90, optmulspd:125, maxmulspd:160, minmulacc:90, optmulacc:110, maxmulacc:120, minmulrot:90, optmulrot:110, maxmulrot:130, eddbid:1548 },

public static final Thrusters THRUSTERS_2_E = new Thrusters("THRUSTERS_2_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_2, ModuleClass.E,      1980, "Int_Engine_Size2_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  46.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.00), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   24.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   48.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,   72.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_2_D = new Thrusters("THRUSTERS_2_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_2, ModuleClass.D,      5930, "Int_Engine_Size2_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   1.00), Map.entry(HorizonsModifier.INTEGRITY,  41.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.25), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   27.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   54.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,   81.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_2_C = new Thrusters("THRUSTERS_2_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_2, ModuleClass.C,     17800, "Int_Engine_Size2_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.50), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   30.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   60.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,   90.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_2_B = new Thrusters("THRUSTERS_2_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_2, ModuleClass.B,     53410, "Int_Engine_Size2_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   4.00), Map.entry(HorizonsModifier.INTEGRITY,  61.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.75), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   33.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   66.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,   99.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_2_A = new Thrusters("THRUSTERS_2_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_2, ModuleClass.A,    160220, "Int_Engine_Size2_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  56.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.00), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   36.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   72.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  108.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_3_E = new Thrusters("THRUSTERS_3_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_3, ModuleClass.E,      6270, "Int_Engine_Size3_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  58.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.48), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   40.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   80.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  120.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_3_D = new Thrusters("THRUSTERS_3_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_3, ModuleClass.D,     18810, "Int_Engine_Size3_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.00), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.79), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   45.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   90.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  135.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_3_C = new Thrusters("THRUSTERS_3_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_3, ModuleClass.C,     56440, "Int_Engine_Size3_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.10), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   50.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  100.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  150.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_3_B = new Thrusters("THRUSTERS_3_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_3, ModuleClass.B,    169300, "Int_Engine_Size3_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   8.00), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.41), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   55.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  110.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  165.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_3_A = new Thrusters("THRUSTERS_3_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_3, ModuleClass.A,    507910, "Int_Engine_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  70.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.72), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   60.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  120.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  180.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_4_E = new Thrusters("THRUSTERS_4_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_4, ModuleClass.E,     19880, "Int_Engine_Size4_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.00), Map.entry(HorizonsModifier.INTEGRITY,  72.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.28), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  140.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  280.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  420.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_4_D = new Thrusters("THRUSTERS_4_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_4, ModuleClass.D,     59630, "Int_Engine_Size4_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   4.00), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.69), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  158.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  315.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  473.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_4_C = new Thrusters("THRUSTERS_4_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_4, ModuleClass.C,    178900, "Int_Engine_Size4_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.00), Map.entry(HorizonsModifier.INTEGRITY,  80.0), Map.entry(HorizonsModifier.POWER_DRAW,  4.10), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  175.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  350.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  525.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_4_B = new Thrusters("THRUSTERS_4_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_4, ModuleClass.B,    536690, "Int_Engine_Size4_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  16.00), Map.entry(HorizonsModifier.INTEGRITY,  96.0), Map.entry(HorizonsModifier.POWER_DRAW,  4.51), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  193.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  385.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  578.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_4_A = new Thrusters("THRUSTERS_4_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_4, ModuleClass.A,   1610080, "Int_Engine_Size4_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  10.00), Map.entry(HorizonsModifier.INTEGRITY,  88.0), Map.entry(HorizonsModifier.POWER_DRAW,  4.92), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  210.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  420.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  630.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_5_E = new Thrusters("THRUSTERS_5_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_5, ModuleClass.E,     63010, "Int_Engine_Size5_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.00), Map.entry(HorizonsModifier.INTEGRITY,  86.0), Map.entry(HorizonsModifier.POWER_DRAW,  4.08), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  280.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  560.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  840.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_5_D = new Thrusters("THRUSTERS_5_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_5, ModuleClass.D,    189040, "Int_Engine_Size5_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   8.00), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,  4.59), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  315.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  630.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  945.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_5_C = new Thrusters("THRUSTERS_5_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_5, ModuleClass.C,    567110, "Int_Engine_Size5_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.00), Map.entry(HorizonsModifier.INTEGRITY,  96.0), Map.entry(HorizonsModifier.POWER_DRAW,  5.10), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  350.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  700.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1050.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_5_B = new Thrusters("THRUSTERS_5_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_5, ModuleClass.B,   1701320, "Int_Engine_Size5_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.00), Map.entry(HorizonsModifier.INTEGRITY, 115.0), Map.entry(HorizonsModifier.POWER_DRAW,  5.61), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  385.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  770.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1155.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_5_A = new Thrusters("THRUSTERS_5_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_5, ModuleClass.A,   5103950, "Int_Engine_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.00), Map.entry(HorizonsModifier.INTEGRITY, 106.0), Map.entry(HorizonsModifier.POWER_DRAW,  6.12), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  420.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  840.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1260.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_6_E = new Thrusters("THRUSTERS_6_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_6, ModuleClass.E,    199750, "Int_Engine_Size6_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  40.00), Map.entry(HorizonsModifier.INTEGRITY, 102.0), Map.entry(HorizonsModifier.POWER_DRAW,  5.04), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  480.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,  960.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1440.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_6_D = new Thrusters("THRUSTERS_6_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_6, ModuleClass.D,    599240, "Int_Engine_Size6_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  16.00), Map.entry(HorizonsModifier.INTEGRITY,  90.0), Map.entry(HorizonsModifier.POWER_DRAW,  5.67), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  540.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1080.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1620.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_6_C = new Thrusters("THRUSTERS_6_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_6, ModuleClass.C,   1797730, "Int_Engine_Size6_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  40.00), Map.entry(HorizonsModifier.INTEGRITY, 113.0), Map.entry(HorizonsModifier.POWER_DRAW,  6.30), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  600.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1200.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1800.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_6_B = new Thrusters("THRUSTERS_6_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_6, ModuleClass.B,   5393180, "Int_Engine_Size6_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  64.00), Map.entry(HorizonsModifier.INTEGRITY, 136.0), Map.entry(HorizonsModifier.POWER_DRAW,  6.93), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  660.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1320.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 1980.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_6_A = new Thrusters("THRUSTERS_6_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_6, ModuleClass.A,  16179530, "Int_Engine_Size6_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  40.00), Map.entry(HorizonsModifier.INTEGRITY, 124.0), Map.entry(HorizonsModifier.POWER_DRAW,  7.56), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  720.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1440.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 2160.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_7_E = new Thrusters("THRUSTERS_7_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_7, ModuleClass.E,    633200, "Int_Engine_Size7_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.00), Map.entry(HorizonsModifier.INTEGRITY, 118.0), Map.entry(HorizonsModifier.POWER_DRAW,  6.08), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  720.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1440.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 2160.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_7_D = new Thrusters("THRUSTERS_7_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_7, ModuleClass.D,   1899600, "Int_Engine_Size7_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.00), Map.entry(HorizonsModifier.INTEGRITY, 105.0), Map.entry(HorizonsModifier.POWER_DRAW,  6.84), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  810.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1620.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 2430.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_7_C = new Thrusters("THRUSTERS_7_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_7, ModuleClass.C,   5698790, "Int_Engine_Size7_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.00), Map.entry(HorizonsModifier.INTEGRITY, 131.0), Map.entry(HorizonsModifier.POWER_DRAW,  7.60), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  900.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 2700.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_7_B = new Thrusters("THRUSTERS_7_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_7, ModuleClass.B,  17096370, "Int_Engine_Size7_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 128.00), Map.entry(HorizonsModifier.INTEGRITY, 157.0), Map.entry(HorizonsModifier.POWER_DRAW,  8.36), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,  990.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 1980.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 2970.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_7_A = new Thrusters("THRUSTERS_7_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_7, ModuleClass.A,  51289110, "Int_Engine_Size7_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.00), Map.entry(HorizonsModifier.INTEGRITY, 144.0), Map.entry(HorizonsModifier.POWER_DRAW,  9.12), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS, 1080.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 2160.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 3240.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_8_E = new Thrusters("THRUSTERS_8_E", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_8, ModuleClass.E,   2007240, "Int_Engine_Size8_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 135.0), Map.entry(HorizonsModifier.POWER_DRAW,  7.20), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS, 1120.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 2240.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 3360.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 83.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 103.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_8_D = new Thrusters("THRUSTERS_8_D", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_8, ModuleClass.D,   6021720, "Int_Engine_Size8_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  64.00), Map.entry(HorizonsModifier.INTEGRITY, 120.0), Map.entry(HorizonsModifier.POWER_DRAW,  8.10), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS, 1260.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 2520.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 3780.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 86.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 106.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_8_C = new Thrusters("THRUSTERS_8_C", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_8, ModuleClass.C,  18065170, "Int_Engine_Size8_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 150.0), Map.entry(HorizonsModifier.POWER_DRAW,  9.00), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS, 1400.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 2800.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 4200.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 110.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_8_B = new Thrusters("THRUSTERS_8_B", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_8, ModuleClass.B,  54195500, "Int_Engine_Size8_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 256.00), Map.entry(HorizonsModifier.INTEGRITY, 180.0), Map.entry(HorizonsModifier.POWER_DRAW,  9.90), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS, 1540.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 3080.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 4620.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 93.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 113.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters THRUSTERS_8_A = new Thrusters("THRUSTERS_8_A", HorizonsBlueprintName.THRUSTERS, ModuleSize.SIZE_8, ModuleClass.A, 162586490, "Int_Engine_Size8_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 165.0), Map.entry(HorizonsModifier.POWER_DRAW, 10.80), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS, 1680.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS, 3360.0), Map.entry(HorizonsModifier.MAXIMUM_MASS, 5040.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 96.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 100.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 116.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3)));
public static final Thrusters ENHANCED_THRUSTERS_2_A = new Thrusters("ENHANCED_THRUSTERS_2_A", HorizonsBlueprintName.ENHANCED_THRUSTERS, ModuleSize.SIZE_2, ModuleClass.A,   1610080, "Int_Engine_Size2_Class5_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   2.50), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  4.00), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   50.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   60.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  120.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 115.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 137.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 2.0),  Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER_SPEED,90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER_SPEED,125.0), Map.entry(HorizonsModifier.MAXIMUM_MULTIPLIER_SPEED,160.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER_ACCELERATION,90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER_ACCELERATION,110.0), Map.entry(HorizonsModifier.MAXIMUM_MULTIPLIER_ACCELERATION,120.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER_ROTATION,90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER_ROTATION,110.0), Map.entry(HorizonsModifier.MAXIMUM_MULTIPLIER_ROTATION,130.0)));
public static final Thrusters ENHANCED_THRUSTERS_3_A = new Thrusters("ENHANCED_THRUSTERS_3_A", HorizonsBlueprintName.ENHANCED_THRUSTERS, ModuleSize.SIZE_3, ModuleClass.A,   5103950, "Int_Engine_Size3_Class5_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS,   5.00), Map.entry(HorizonsModifier.INTEGRITY,  55.0), Map.entry(HorizonsModifier.POWER_DRAW,  5.00), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.ENGINE_MINIMUM_MASS,   70.0), Map.entry(HorizonsModifier.ENGINE_OPTIMAL_MASS,   90.0), Map.entry(HorizonsModifier.MAXIMUM_MASS,  200.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER, 90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER, 115.0), Map.entry(HorizonsModifier.MAXIMUM_MULIPLIER, 137.0), Map.entry(HorizonsModifier.ENGINE_THERMAL_LOAD, 1.3),  Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER_SPEED,90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER_SPEED,125.0), Map.entry(HorizonsModifier.MAXIMUM_MULTIPLIER_SPEED,160.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER_ACCELERATION,90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER_ACCELERATION,110.0), Map.entry(HorizonsModifier.MAXIMUM_MULTIPLIER_ACCELERATION,120.0), Map.entry(HorizonsModifier.MINIMUM_MULTIPLIER_ROTATION,90.0), Map.entry(HorizonsModifier.OPTIMAL_MULTIPLIER_ROTATION,110.0), Map.entry(HorizonsModifier.MAXIMUM_MULTIPLIER_ROTATION,130.0)));

public static final List<Thrusters> THRUSTERS = List.of(
        THRUSTERS_2_E,
        THRUSTERS_2_D,
        THRUSTERS_2_C,
        THRUSTERS_2_B,
        THRUSTERS_2_A,
        THRUSTERS_3_E,
        THRUSTERS_3_D,
        THRUSTERS_3_C,
        THRUSTERS_3_B,
        THRUSTERS_3_A,
        THRUSTERS_4_E,
        THRUSTERS_4_D,
        THRUSTERS_4_C,
        THRUSTERS_4_B,
        THRUSTERS_4_A,
        THRUSTERS_5_E,
        THRUSTERS_5_D,
        THRUSTERS_5_C,
        THRUSTERS_5_B,
        THRUSTERS_5_A,
        THRUSTERS_6_E,
        THRUSTERS_6_D,
        THRUSTERS_6_C,
        THRUSTERS_6_B,
        THRUSTERS_6_A,
        THRUSTERS_7_E,
        THRUSTERS_7_D,
        THRUSTERS_7_C,
        THRUSTERS_7_B,
        THRUSTERS_7_A,
        THRUSTERS_8_E,
        THRUSTERS_8_D,
        THRUSTERS_8_C,
        THRUSTERS_8_B,
        THRUSTERS_8_A,
        ENHANCED_THRUSTERS_2_A,
        ENHANCED_THRUSTERS_3_A
);
    private Thrusters(final String id, final HorizonsBlueprintName name, final ModuleSize moduleSize, final ModuleClass moduleClass, final int basePrice, final String internalName, final Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, basePrice, internalName, attributes);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return ThrusterBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return ExperimentalEffectBlueprints.THRUSTERS.keySet().stream().toList();
    }

    public Thrusters(final Thrusters thrusters) {
        super(thrusters);
    }
    @Override
    public Thrusters Clone(){
        return new Thrusters(this);
    }

    @Override
    public String getClarifier() {
        return this== ENHANCED_THRUSTERS_2_A || this== ENHANCED_THRUSTERS_3_A ? " " + LocaleService.getLocalizedStringForCurrentLocale("blueprint.horizons.name.enhanced_thrusters") : "";
    }
}
