package nl.jixxed.eliteodysseymaterials.domain.ships.optional_internals;

import nl.jixxed.eliteodysseymaterials.constants.horizons.optional_internals.FuelTransferLimpetControllerBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleClass;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleSize;
import nl.jixxed.eliteodysseymaterials.domain.ships.OptionalModule;
import nl.jixxed.eliteodysseymaterials.domain.ships.Origin;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class FuelTransferLimpetController extends OptionalModule {

//		23150 : { mtype:'iftlc', cost:    600, name:'Fuel Transfer Limpet Controller', class:1, rating:'E', mass:  1.30, integ: 24, pwrdraw:0.18, boottime:10, maxlimpet: 1, lpactrng: 600, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671249, fdname:'Int_DroneControl_FuelTransfer_Size1_Class1', eddbid:1414 },
//            23140 : { mtype:'iftlc', cost:   1200, name:'Fuel Transfer Limpet Controller', class:1, rating:'D', mass:  0.50, integ: 32, pwrdraw:0.14, boottime:10, maxlimpet: 1, lpactrng: 800, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671250, fdname:'Int_DroneControl_FuelTransfer_Size1_Class2', eddbid:1415 },
//            23130 : { mtype:'iftlc', cost:   2400, name:'Fuel Transfer Limpet Controller', class:1, rating:'C', mass:  1.30, integ: 40, pwrdraw:0.23, boottime:10, maxlimpet: 1, lpactrng:1000, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671251, fdname:'Int_DroneControl_FuelTransfer_Size1_Class3', eddbid:1416 },
//            23120 : { mtype:'iftlc', cost:   4800, name:'Fuel Transfer Limpet Controller', class:1, rating:'B', mass:  2.00, integ: 48, pwrdraw:0.32, boottime:10, maxlimpet: 1, lpactrng:1200, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671252, fdname:'Int_DroneControl_FuelTransfer_Size1_Class4', eddbid:1417 },
//            23110 : { mtype:'iftlc', cost:   9600, name:'Fuel Transfer Limpet Controller', class:1, rating:'A', mass:  1.30, integ: 56, pwrdraw:0.28, boottime:10, maxlimpet: 1, lpactrng:1400, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671253, fdname:'Int_DroneControl_FuelTransfer_Size1_Class5', eddbid:1418 },
//
//            23350 : { mtype:'iftlc', cost:   5400, name:'Fuel Transfer Limpet Controller', class:3, rating:'E', mass:  5.00, integ: 38, pwrdraw:0.27, boottime:10, maxlimpet: 2, lpactrng: 660, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671254, fdname:'Int_DroneControl_FuelTransfer_Size3_Class1', eddbid:1419 },
//            23340 : { mtype:'iftlc', cost:  10800, name:'Fuel Transfer Limpet Controller', class:3, rating:'D', mass:  2.00, integ: 51, pwrdraw:0.20, boottime:10, maxlimpet: 2, lpactrng: 880, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671255, fdname:'Int_DroneControl_FuelTransfer_Size3_Class2', eddbid:1420 },
//            23330 : { mtype:'iftlc', cost:  21600, name:'Fuel Transfer Limpet Controller', class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw:0.34, boottime:10, maxlimpet: 2, lpactrng:1100, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671256, fdname:'Int_DroneControl_FuelTransfer_Size3_Class3', eddbid:1421 },
//            23320 : { mtype:'iftlc', cost:  43200, name:'Fuel Transfer Limpet Controller', class:3, rating:'B', mass:  8.00, integ: 77, pwrdraw:0.48, boottime:10, maxlimpet: 2, lpactrng:1320, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671257, fdname:'Int_DroneControl_FuelTransfer_Size3_Class4', eddbid:1422 },
//            23310 : { mtype:'iftlc', cost:  86400, name:'Fuel Transfer Limpet Controller', class:3, rating:'A', mass:  5.00, integ: 90, pwrdraw:0.41, boottime:10, maxlimpet: 2, lpactrng:1540, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671258, fdname:'Int_DroneControl_FuelTransfer_Size3_Class5', eddbid:1423 },
//
//            23550 : { mtype:'iftlc', cost:  48600, name:'Fuel Transfer Limpet Controller', class:5, rating:'E', mass: 20.00, integ: 58, pwrdraw:0.40, boottime:10, maxlimpet: 4, lpactrng: 780, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671259, fdname:'Int_DroneControl_FuelTransfer_Size5_Class1', eddbid:1424 },
//            23540 : { mtype:'iftlc', cost:  97200, name:'Fuel Transfer Limpet Controller', class:5, rating:'D', mass:  8.00, integ: 77, pwrdraw:0.30, boottime:10, maxlimpet: 4, lpactrng:1040, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671260, fdname:'Int_DroneControl_FuelTransfer_Size5_Class2', eddbid:1425 },
//            23530 : { mtype:'iftlc', cost: 194400, name:'Fuel Transfer Limpet Controller', class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw:0.50, boottime:10, maxlimpet: 4, lpactrng:1300, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671261, fdname:'Int_DroneControl_FuelTransfer_Size5_Class3', eddbid:1426 },
//            23520 : { mtype:'iftlc', cost: 388800, name:'Fuel Transfer Limpet Controller', class:5, rating:'B', mass: 32.00, integ:115, pwrdraw:0.72, boottime:10, maxlimpet: 4, lpactrng:1560, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671262, fdname:'Int_DroneControl_FuelTransfer_Size5_Class4', eddbid:1427 },
//            23510 : { mtype:'iftlc', cost: 777600, name:'Fuel Transfer Limpet Controller', class:5, rating:'A', mass: 20.00, integ:134, pwrdraw:0.60, boottime:10, maxlimpet: 4, lpactrng:1820, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671263, fdname:'Int_DroneControl_FuelTransfer_Size5_Class5', eddbid:1428 },
//
//            23750 : { mtype:'iftlc', cost: 437400, name:'Fuel Transfer Limpet Controller', class:7, rating:'E', mass: 80.00, integ: 79, pwrdraw:0.55, boottime:10, maxlimpet: 8, lpactrng:1020, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671264, fdname:'Int_DroneControl_FuelTransfer_Size7_Class1', eddbid:1429 },
//            23740 : { mtype:'iftlc', cost: 874800, name:'Fuel Transfer Limpet Controller', class:7, rating:'D', mass: 32.00, integ:105, pwrdraw:0.41, boottime:10, maxlimpet: 8, lpactrng:1360, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671265, fdname:'Int_DroneControl_FuelTransfer_Size7_Class2', eddbid:1430 },
//            23730 : { mtype:'iftlc', cost:1749600, name:'Fuel Transfer Limpet Controller', class:7, rating:'C', mass: 80.00, integ:131, pwrdraw:0.69, boottime:10, maxlimpet: 8, lpactrng:1700, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671266, fdname:'Int_DroneControl_FuelTransfer_Size7_Class3', eddbid:1431 },
//            23720 : { mtype:'iftlc', cost:3499200, name:'Fuel Transfer Limpet Controller', class:7, rating:'B', mass:128.00, integ:157, pwrdraw:0.97, boottime:10, maxlimpet: 8, lpactrng:2040, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671267, fdname:'Int_DroneControl_FuelTransfer_Size7_Class4', eddbid:1432 },
//            23710 : { mtype:'iftlc', cost:6998400, name:'Fuel Transfer Limpet Controller', class:7, rating:'A', mass: 80.00, integ:183, pwrdraw:0.83, boottime:10, maxlimpet: 8, lpactrng:2380, limpettime: 60, maxspd:200, fuelxfer:1.0, fdid:128671268, fdname:'Int_DroneControl_FuelTransfer_Size7_Class5', eddbid:1433 },
//
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_1_E = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_1_E", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.E, true, 600, "Int_DroneControl_FuelTransfer_Size1_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  1.3), Map.entry(HorizonsModifier.INTEGRITY,  24.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.18), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  600.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_1_D = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_1_D", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.D, true, 1200, "Int_DroneControl_FuelTransfer_Size1_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  0.5), Map.entry(HorizonsModifier.INTEGRITY,  32.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.14), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  800.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_1_C = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_1_C", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.C, true, 2400, "Int_DroneControl_FuelTransfer_Size1_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  1.3), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.23), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1000.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_1_B = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_1_B", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.B, true, 4800, "Int_DroneControl_FuelTransfer_Size1_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  48.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.32), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1200.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_1_A = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_1_A", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.A, true, 9600, "Int_DroneControl_FuelTransfer_Size1_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  1.3), Map.entry(HorizonsModifier.INTEGRITY,  56.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.28), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1400.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_3_E = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_3_E", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.E, true, 5400, "Int_DroneControl_FuelTransfer_Size3_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  5.0), Map.entry(HorizonsModifier.INTEGRITY,  38.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.27), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  660.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_3_D = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_3_D", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.D, true, 10800, "Int_DroneControl_FuelTransfer_Size3_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.2), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  880.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_3_C = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_3_C", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.C, true, 21600, "Int_DroneControl_FuelTransfer_Size3_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  5.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.34), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1100.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_3_B = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_3_B", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.B, true, 43200, "Int_DroneControl_FuelTransfer_Size3_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.48), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1320.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_3_A = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_3_A", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.A, true, 86400, "Int_DroneControl_FuelTransfer_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  5.0), Map.entry(HorizonsModifier.INTEGRITY,  90.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.41), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1540.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_5_E = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_5_E", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.E, true, 48600, "Int_DroneControl_FuelTransfer_Size5_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.0), Map.entry(HorizonsModifier.INTEGRITY,  58.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.4), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  780.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_5_D = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_5_D", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.D, true, 97200, "Int_DroneControl_FuelTransfer_Size5_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.3), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1040.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_5_C = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_5_C", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.C, true, 194400, "Int_DroneControl_FuelTransfer_Size5_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.0), Map.entry(HorizonsModifier.INTEGRITY,  96.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.5), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1300.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_5_B = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_5_B", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.B, true, 388800, "Int_DroneControl_FuelTransfer_Size5_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.0), Map.entry(HorizonsModifier.INTEGRITY,  115.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.72), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1560.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_5_A = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_5_A", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.A, true, 777600, "Int_DroneControl_FuelTransfer_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.0), Map.entry(HorizonsModifier.INTEGRITY,  134.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.6), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1820.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_7_E = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_7_E", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.E, true, 437400, "Int_DroneControl_FuelTransfer_Size7_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.0), Map.entry(HorizonsModifier.INTEGRITY,  79.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.55), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  8.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1020.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_7_D = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_7_D", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.D, true, 874800, "Int_DroneControl_FuelTransfer_Size7_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.0), Map.entry(HorizonsModifier.INTEGRITY,  105.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.41), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  8.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1360.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_7_C = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_7_C", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.C, true, 1749600, "Int_DroneControl_FuelTransfer_Size7_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.0), Map.entry(HorizonsModifier.INTEGRITY,  131.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.69), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  8.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1700.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_7_B = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_7_B", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.B, true, 3499200, "Int_DroneControl_FuelTransfer_Size7_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  128.0), Map.entry(HorizonsModifier.INTEGRITY,  157.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.97), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  8.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2040.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));
    public static final FuelTransferLimpetController FUEL_TRANSFER_LIMPET_CONTROLLER_7_A = new FuelTransferLimpetController("FUEL_TRANSFER_LIMPET_CONTROLLER_7_A", HorizonsBlueprintName.FUEL_TRANSFER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.A, true, 6998400, "Int_DroneControl_FuelTransfer_Size7_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.0), Map.entry(HorizonsModifier.INTEGRITY,  183.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.83), Map.entry(HorizonsModifier.BOOT_TIME,  10.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  8.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2380.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  60.0), Map.entry(HorizonsModifier.DRONE_SPEED,  200.0), Map.entry(HorizonsModifier.DRONE_FUEL_CAPACITY,  1.0)));

    public static final List<FuelTransferLimpetController> FUEL_TRANSFER_LIMPET_CONTROLLERS = List.of(
            FUEL_TRANSFER_LIMPET_CONTROLLER_1_E,
            FUEL_TRANSFER_LIMPET_CONTROLLER_1_D,
            FUEL_TRANSFER_LIMPET_CONTROLLER_1_C,
            FUEL_TRANSFER_LIMPET_CONTROLLER_1_B,
            FUEL_TRANSFER_LIMPET_CONTROLLER_1_A,
            FUEL_TRANSFER_LIMPET_CONTROLLER_3_E,
            FUEL_TRANSFER_LIMPET_CONTROLLER_3_D,
            FUEL_TRANSFER_LIMPET_CONTROLLER_3_C,
            FUEL_TRANSFER_LIMPET_CONTROLLER_3_B,
            FUEL_TRANSFER_LIMPET_CONTROLLER_3_A,
            FUEL_TRANSFER_LIMPET_CONTROLLER_5_E,
            FUEL_TRANSFER_LIMPET_CONTROLLER_5_D,
            FUEL_TRANSFER_LIMPET_CONTROLLER_5_C,
            FUEL_TRANSFER_LIMPET_CONTROLLER_5_B,
            FUEL_TRANSFER_LIMPET_CONTROLLER_5_A,
            FUEL_TRANSFER_LIMPET_CONTROLLER_7_E,
            FUEL_TRANSFER_LIMPET_CONTROLLER_7_D,
            FUEL_TRANSFER_LIMPET_CONTROLLER_7_C,
            FUEL_TRANSFER_LIMPET_CONTROLLER_7_B,
            FUEL_TRANSFER_LIMPET_CONTROLLER_7_A
    );
    public FuelTransferLimpetController(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, basePrice, internalName, attributes);
    }

    public FuelTransferLimpetController(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, basePrice, internalName, attributes);
    }

    public FuelTransferLimpetController(FuelTransferLimpetController fuelTransferLimpetController) {
        super(fuelTransferLimpetController);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return FuelTransferLimpetControllerBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public FuelTransferLimpetController Clone() {
        return new FuelTransferLimpetController(this);
    }
}
