package nl.jixxed.eliteodysseymaterials.domain.ships.optional_internals;

import nl.jixxed.eliteodysseymaterials.constants.horizons.optional_internals.HatchBreakerLimpetControllerBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleClass;
import nl.jixxed.eliteodysseymaterials.domain.ships.ModuleSize;
import nl.jixxed.eliteodysseymaterials.domain.ships.OptionalModule;
import nl.jixxed.eliteodysseymaterials.domain.ships.Origin;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class HatchBreakerLimpetController extends OptionalModule {
//    26150 : { mtype:'ihblc', cost:    600, name:'Hatch Breaker Limpet Controller', class:1, rating:'E', mass:  1.30, integ: 32, pwrdraw:0.12, boottime:3, maxlimpet: 2, targetrng:1500, lpactrng:1600, limpettime:120, maxspd:500, hacktime:22, mincargo:1, maxcargo: 6, fdid:128066532, fdname:'Int_DroneControl_ResourceSiphon_Size1_Class1', eddbid:1207 },
//            26140 : { mtype:'ihblc', cost:   1200, name:'Hatch Breaker Limpet Controller', class:1, rating:'D', mass:  0.50, integ: 24, pwrdraw:0.16, boottime:3, maxlimpet: 1, targetrng:2000, lpactrng:2100, limpettime:120, maxspd:500, hacktime:19, mincargo:2, maxcargo: 7, fdid:128066533, fdname:'Int_DroneControl_ResourceSiphon_Size1_Class2', eddbid:1208 },
//            26130 : { mtype:'ihblc', cost:   2400, name:'Hatch Breaker Limpet Controller', class:1, rating:'C', mass:  1.30, integ: 40, pwrdraw:0.20, boottime:3, maxlimpet: 1, targetrng:2500, lpactrng:2600, limpettime:120, maxspd:500, hacktime:16, mincargo:3, maxcargo: 8, fdid:128066534, fdname:'Int_DroneControl_ResourceSiphon_Size1_Class3', eddbid:1209 },
//            26120 : { mtype:'ihblc', cost:   4800, name:'Hatch Breaker Limpet Controller', class:1, rating:'B', mass:  2.00, integ: 56, pwrdraw:0.24, boottime:3, maxlimpet: 2, targetrng:3000, lpactrng:3100, limpettime:120, maxspd:500, hacktime:13, mincargo:4, maxcargo: 9, fdid:128066535, fdname:'Int_DroneControl_ResourceSiphon_Size1_Class4', eddbid:1210 },
//            26110 : { mtype:'ihblc', cost:   9600, name:'Hatch Breaker Limpet Controller', class:1, rating:'A', mass:  1.30, integ: 48, pwrdraw:0.28, boottime:3, maxlimpet: 1, targetrng:3500, lpactrng:3600, limpettime:120, maxspd:500, hacktime:10, mincargo:5, maxcargo:10, fdid:128066536, fdname:'Int_DroneControl_ResourceSiphon_Size1_Class5', eddbid:1211 },
//
//            26350 : { mtype:'ihblc', cost:   5400, name:'Hatch Breaker Limpet Controller', class:3, rating:'E', mass:  5.00, integ: 51, pwrdraw:0.18, boottime:3, maxlimpet: 4, targetrng:1620, lpactrng:1720, limpettime:120, maxspd:500, hacktime:17, mincargo:1, maxcargo: 6, fdid:128066537, fdname:'Int_DroneControl_ResourceSiphon_Size3_Class1', eddbid:1212 },
//            26340 : { mtype:'ihblc', cost:  10800, name:'Hatch Breaker Limpet Controller', class:3, rating:'D', mass:  2.00, integ: 38, pwrdraw:0.24, boottime:3, maxlimpet: 3, targetrng:2160, lpactrng:2260, limpettime:120, maxspd:500, hacktime:14, mincargo:2, maxcargo: 7, fdid:128066538, fdname:'Int_DroneControl_ResourceSiphon_Size3_Class2', eddbid:1213 },
//            26330 : { mtype:'ihblc', cost:  21600, name:'Hatch Breaker Limpet Controller', class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw:0.30, boottime:3, maxlimpet: 3, targetrng:2700, lpactrng:2800, limpettime:120, maxspd:500, hacktime:12, mincargo:3, maxcargo: 8, fdid:128066539, fdname:'Int_DroneControl_ResourceSiphon_Size3_Class3', eddbid:1214 },
//            26320 : { mtype:'ihblc', cost:  43200, name:'Hatch Breaker Limpet Controller', class:3, rating:'B', mass:  8.00, integ: 90, pwrdraw:0.36, boottime:3, maxlimpet: 4, targetrng:3240, lpactrng:3340, limpettime:120, maxspd:500, hacktime:10, mincargo:4, maxcargo: 9, fdid:128066540, fdname:'Int_DroneControl_ResourceSiphon_Size3_Class4', eddbid:1215 },
//            26310 : { mtype:'ihblc', cost:  86400, name:'Hatch Breaker Limpet Controller', class:3, rating:'A', mass:  5.00, integ: 77, pwrdraw:0.42, boottime:3, maxlimpet: 3, targetrng:3780, lpactrng:3870, limpettime:120, maxspd:500, hacktime: 7, mincargo:5, maxcargo:10, fdid:128066541, fdname:'Int_DroneControl_ResourceSiphon_Size3_Class5', eddbid:1216 },
//
//            26550 : { mtype:'ihblc', cost:  48600, name:'Hatch Breaker Limpet Controller', class:5, rating:'E', mass: 20.00, integ: 77, pwrdraw:0.30, boottime:3, maxlimpet: 9, targetrng:1980, lpactrng:2080, limpettime:120, maxspd:500, hacktime:11, mincargo:1, maxcargo: 6, fdid:128066542, fdname:'Int_DroneControl_ResourceSiphon_Size5_Class1', eddbid:1217 },
//            26540 : { mtype:'ihblc', cost:  97200, name:'Hatch Breaker Limpet Controller', class:5, rating:'D', mass:  8.00, integ: 58, pwrdraw:0.40, boottime:3, maxlimpet: 6, targetrng:2640, lpactrng:2740, limpettime:120, maxspd:500, hacktime:10, mincargo:2, maxcargo: 7, fdid:128066543, fdname:'Int_DroneControl_ResourceSiphon_Size5_Class2', eddbid:1218 },
//            26530 : { mtype:'ihblc', cost: 194400, name:'Hatch Breaker Limpet Controller', class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw:0.50, boottime:3, maxlimpet: 7, targetrng:3300, lpactrng:3400, limpettime:120, maxspd:500, hacktime: 8, mincargo:3, maxcargo: 8, fdid:128066544, fdname:'Int_DroneControl_ResourceSiphon_Size5_Class3', eddbid:1219 },
//            26520 : { mtype:'ihblc', cost: 388800, name:'Hatch Breaker Limpet Controller', class:5, rating:'B', mass: 32.00, integ:134, pwrdraw:0.60, boottime:3, maxlimpet: 9, targetrng:3960, lpactrng:4060, limpettime:120, maxspd:500, hacktime: 6, mincargo:4, maxcargo: 9, fdid:128066545, fdname:'Int_DroneControl_ResourceSiphon_Size5_Class4', eddbid:1220 },
//            26510 : { mtype:'ihblc', cost: 777600, name:'Hatch Breaker Limpet Controller', class:5, rating:'A', mass: 20.00, integ:115, pwrdraw:0.70, boottime:3, maxlimpet: 6, targetrng:4620, lpactrng:4720, limpettime:120, maxspd:500, hacktime: 5, mincargo:5, maxcargo:10, fdid:128066546, fdname:'Int_DroneControl_ResourceSiphon_Size5_Class5', eddbid:1221 },
//
//            26750 : { mtype:'ihblc', cost: 437400, name:'Hatch Breaker Limpet Controller', class:7, rating:'E', mass: 80.00, integ:105, pwrdraw:0.42, boottime:3, maxlimpet:18, targetrng:2580, lpactrng:2680, limpettime:120, maxspd:500, hacktime: 6, mincargo:1, maxcargo: 6, fdid:128066547, fdname:'Int_DroneControl_ResourceSiphon_Size7_Class1', eddbid:1222 },
//            26740 : { mtype:'ihblc', cost: 874800, name:'Hatch Breaker Limpet Controller', class:7, rating:'D', mass: 32.00, integ: 79, pwrdraw:0.56, boottime:3, maxlimpet:12, targetrng:3440, lpactrng:3540, limpettime:120, maxspd:500, hacktime: 5, mincargo:2, maxcargo: 7, fdid:128066548, fdname:'Int_DroneControl_ResourceSiphon_Size7_Class2', eddbid:1223 },
//            26730 : { mtype:'ihblc', cost:1749600, name:'Hatch Breaker Limpet Controller', class:7, rating:'C', mass: 80.00, integ:131, pwrdraw:0.70, boottime:3, maxlimpet:15, targetrng:4300, lpactrng:4400, limpettime:120, maxspd:500, hacktime: 4, mincargo:3, maxcargo: 8, fdid:128066549, fdname:'Int_DroneControl_ResourceSiphon_Size7_Class3', eddbid:1224 },
//            26720 : { mtype:'ihblc', cost:3499200, name:'Hatch Breaker Limpet Controller', class:7, rating:'B', mass:128.00, integ:183, pwrdraw:0.84, boottime:3, maxlimpet:18, targetrng:5160, lpactrng:5260, limpettime:120, maxspd:500, hacktime: 3, mincargo:4, maxcargo: 9, fdid:128066550, fdname:'Int_DroneControl_ResourceSiphon_Size7_Class4', eddbid:1225 },
//            26710 : { mtype:'ihblc', cost:6998400, name:'Hatch Breaker Limpet Controller', class:7, rating:'A', mass: 80.00, integ:157, pwrdraw:0.98, boottime:3, maxlimpet:12, targetrng:6020, lpactrng:6120, limpettime:120, maxspd:500, hacktime: 2, mincargo:5, maxcargo:10, fdid:128066551, fdname:'Int_DroneControl_ResourceSiphon_Size7_Class5', eddbid:1226 },
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_1_E = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_1_E", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.E, true, 600, "Int_DroneControl_ResourceSiphon_Size1_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  1.3), Map.entry(HorizonsModifier.INTEGRITY,  32.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.12), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  1500.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1600.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  22.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  1.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  6.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_1_D = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_1_D", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.D, true, 1200, "Int_DroneControl_ResourceSiphon_Size1_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  0.5), Map.entry(HorizonsModifier.INTEGRITY,  24.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.16), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  2000.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2100.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  19.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  2.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  7.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_1_C = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_1_C", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.C, true, 2400, "Int_DroneControl_ResourceSiphon_Size1_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  1.3), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.2), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  2500.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2600.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  16.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  3.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  8.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_1_B = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_1_B", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.B, true, 4800, "Int_DroneControl_ResourceSiphon_Size1_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  56.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.24), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  2.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3000.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  3100.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  13.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  4.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  9.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_1_A = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_1_A", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_1, ModuleClass.A, true, 9600, "Int_DroneControl_ResourceSiphon_Size1_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  1.3), Map.entry(HorizonsModifier.INTEGRITY,  48.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.28), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  1.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3500.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  3600.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  10.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  5.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  10.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_3_E = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_3_E", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.E, true, 5400, "Int_DroneControl_ResourceSiphon_Size3_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  5.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.18), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  1620.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  1720.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  17.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  1.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  6.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_3_D = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_3_D", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.D, true, 10800, "Int_DroneControl_ResourceSiphon_Size3_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  38.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.24), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  3.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  2160.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2260.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  14.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  2.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  7.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_3_C = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_3_C", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.C, true, 21600, "Int_DroneControl_ResourceSiphon_Size3_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  5.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.3), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  3.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  2700.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2800.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  12.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  3.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  8.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_3_B = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_3_B", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.B, true, 43200, "Int_DroneControl_ResourceSiphon_Size3_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  90.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.36), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  4.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3240.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  3340.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  10.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  4.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  9.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_3_A = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_3_A", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_3, ModuleClass.A, true, 86400, "Int_DroneControl_ResourceSiphon_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  5.0), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.42), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  3.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3780.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  3870.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  7.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  5.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  10.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_5_E = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_5_E", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.E, true, 48600, "Int_DroneControl_ResourceSiphon_Size5_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.0), Map.entry(HorizonsModifier.INTEGRITY,  77.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.3), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  9.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  1980.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2080.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  11.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  1.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  6.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_5_D = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_5_D", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.D, true, 97200, "Int_DroneControl_ResourceSiphon_Size5_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  58.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.4), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  6.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  2640.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2740.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  10.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  2.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  7.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_5_C = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_5_C", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.C, true, 194400, "Int_DroneControl_ResourceSiphon_Size5_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.0), Map.entry(HorizonsModifier.INTEGRITY,  96.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.5), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  7.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3300.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  3400.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  8.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  3.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  8.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_5_B = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_5_B", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.B, true, 388800, "Int_DroneControl_ResourceSiphon_Size5_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.0), Map.entry(HorizonsModifier.INTEGRITY,  134.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.6), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  9.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3960.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  4060.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  6.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  4.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  9.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_5_A = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_5_A", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_5, ModuleClass.A, true, 777600, "Int_DroneControl_ResourceSiphon_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  20.0), Map.entry(HorizonsModifier.INTEGRITY,  115.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.7), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  6.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  4620.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  4720.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  5.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  5.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  10.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_7_E = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_7_E", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.E, true, 437400, "Int_DroneControl_ResourceSiphon_Size7_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.0), Map.entry(HorizonsModifier.INTEGRITY,  105.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.42), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  18.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  2580.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  2680.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  6.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  1.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  6.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_7_D = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_7_D", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.D, true, 874800, "Int_DroneControl_ResourceSiphon_Size7_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  32.0), Map.entry(HorizonsModifier.INTEGRITY,  79.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.56), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  12.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  3440.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  3540.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  5.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  2.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  7.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_7_C = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_7_C", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.C, true, 1749600, "Int_DroneControl_ResourceSiphon_Size7_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.0), Map.entry(HorizonsModifier.INTEGRITY,  131.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.7), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  15.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  4300.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  4400.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  4.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  3.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  8.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_7_B = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_7_B", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.B, true, 3499200, "Int_DroneControl_ResourceSiphon_Size7_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  128.0), Map.entry(HorizonsModifier.INTEGRITY,  183.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.84), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  18.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  5160.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  5260.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  3.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  4.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  9.0)));
    public static final HatchBreakerLimpetController HATCH_BREAKER_LIMPET_CONTROLLER_7_A = new HatchBreakerLimpetController("HATCH_BREAKER_LIMPET_CONTROLLER_7_A", HorizonsBlueprintName.HATCH_BREAKER_LIMPET_CONTROLLER, ModuleSize.SIZE_7, ModuleClass.A, true, 6998400, "Int_DroneControl_ResourceSiphon_Size7_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  80.0), Map.entry(HorizonsModifier.INTEGRITY,  157.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.98), Map.entry(HorizonsModifier.BOOT_TIME,  3.0), Map.entry(HorizonsModifier.MAX_ACTIVE_LIMPETS,  12.0), Map.entry(HorizonsModifier.DRONE_TARGET_RANGE,  6020.0), Map.entry(HorizonsModifier.DRONE_ACTIVE_RANGE,  6120.0), Map.entry(HorizonsModifier.DRONE_LIFE_TIME,  120.0), Map.entry(HorizonsModifier.DRONE_SPEED,  500.0), Map.entry(HorizonsModifier.DRONE_HACKING_TIME,  2.0), Map.entry(HorizonsModifier.DRONE_MIN_JETTISONED_CARGO,  5.0), Map.entry(HorizonsModifier.DRONE_MAX_JETTISONED_CARGO,  10.0)));

    public static final List<HatchBreakerLimpetController> HATCH_BREAKER_LIMPET_CONTROLLERS = List.of(
            HATCH_BREAKER_LIMPET_CONTROLLER_1_E,
            HATCH_BREAKER_LIMPET_CONTROLLER_1_D,
            HATCH_BREAKER_LIMPET_CONTROLLER_1_C,
            HATCH_BREAKER_LIMPET_CONTROLLER_1_B,
            HATCH_BREAKER_LIMPET_CONTROLLER_1_A,
            HATCH_BREAKER_LIMPET_CONTROLLER_3_E,
            HATCH_BREAKER_LIMPET_CONTROLLER_3_D,
            HATCH_BREAKER_LIMPET_CONTROLLER_3_C,
            HATCH_BREAKER_LIMPET_CONTROLLER_3_B,
            HATCH_BREAKER_LIMPET_CONTROLLER_3_A,
            HATCH_BREAKER_LIMPET_CONTROLLER_5_E,
            HATCH_BREAKER_LIMPET_CONTROLLER_5_D,
            HATCH_BREAKER_LIMPET_CONTROLLER_5_C,
            HATCH_BREAKER_LIMPET_CONTROLLER_5_B,
            HATCH_BREAKER_LIMPET_CONTROLLER_5_A,
            HATCH_BREAKER_LIMPET_CONTROLLER_7_E,
            HATCH_BREAKER_LIMPET_CONTROLLER_7_D,
            HATCH_BREAKER_LIMPET_CONTROLLER_7_C,
            HATCH_BREAKER_LIMPET_CONTROLLER_7_B,
            HATCH_BREAKER_LIMPET_CONTROLLER_7_A
    );
    public HatchBreakerLimpetController(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, basePrice, internalName, attributes);
    }

    public HatchBreakerLimpetController(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, basePrice, internalName, attributes);
    }

    public HatchBreakerLimpetController(HatchBreakerLimpetController hatchBreakerLimpetController) {
        super(hatchBreakerLimpetController);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return HatchBreakerLimpetControllerBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public HatchBreakerLimpetController Clone() {
        return new HatchBreakerLimpetController(this);
    }
}
