package nl.jixxed.eliteodysseymaterials.domain.ships.optional_internals;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.optional_internals.ShieldGeneratorBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;
import nl.jixxed.eliteodysseymaterials.service.LocaleService;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class ShieldGenerator extends OptionalModule {

    //		      30150 : { mtype:'isg', cost:      300, name:'Shield Generator', class:1, rating:'E', mass:  1.30, integ: 32, pwrdraw:0.72, boottime:1, genminmass: 13.0, genoptmass:  25.0, genmaxmass:  63.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064258, fdname:'Int_ShieldGenerator_Size1_Class1', eddbid:1804 },
//            30140 : { mtype:'isg', cost:     1240, name:'Shield Generator', class:1, rating:'D', mass:  0.50, integ: 24, pwrdraw:0.96, boottime:1, genminmass: 13.0, genoptmass:  25.0, genmaxmass:  63.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064259, fdname:'Int_ShieldGenerator_Size1_Class2', eddbid:1805 },
//            30130 : { mtype:'isg', cost:     5140, name:'Shield Generator', class:1, rating:'C', mass:  1.30, integ: 40, pwrdraw:1.20, boottime:1, genminmass: 13.0, genoptmass:  25.0, genmaxmass:  63.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064260, fdname:'Int_ShieldGenerator_Size1_Class3', eddbid:1806 },
//            30110 : { mtype:'isg', cost:    88075, name:'Shield Generator', class:1, rating:'A', mass:  1.30, integ: 48, pwrdraw:1.68, boottime:1, genminmass: 13.0, genoptmass:  25.0, genmaxmass:  63.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064262, fdname:'Int_ShieldGenerator_Size1_Class5', eddbid:1551 },
//            30250 : { mtype:'isg', cost:     1980, name:'Shield Generator', class:2, rating:'E', mass:  2.50, integ: 41, pwrdraw:0.90, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064263, fdname:'Int_ShieldGenerator_Size2_Class1', eddbid:1116 },
//            30240 : { mtype:'isg', cost:     5930, name:'Shield Generator', class:2, rating:'D', mass:  1.00, integ: 31, pwrdraw:1.20, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064264, fdname:'Int_ShieldGenerator_Size2_Class2', eddbid:1117 },
//            30230 : { mtype:'isg', cost:    17800, name:'Shield Generator', class:2, rating:'C', mass:  2.50, integ: 51, pwrdraw:1.50, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064265, fdname:'Int_ShieldGenerator_Size2_Class3', eddbid:1118 },
//            30220 : { mtype:'isg', cost:    53410, name:'Shield Generator', class:2, rating:'B', mass:  4.00, integ: 71, pwrdraw:1.80, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064266, fdname:'Int_ShieldGenerator_Size2_Class4', eddbid:1119 },
//            30210 : { mtype:'isg', cost:   160220, name:'Shield Generator', class:2, rating:'A', mass:  2.50, integ: 61, pwrdraw:2.10, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.0, bgenrate:1.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064267, fdname:'Int_ShieldGenerator_Size2_Class5', eddbid:1120 },
//            30350 : { mtype:'isg', cost:     6270, name:'Shield Generator', class:3, rating:'E', mass:  5.00, integ: 51, pwrdraw:1.08, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.0, bgenrate:1.87, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064268, fdname:'Int_ShieldGenerator_Size3_Class1', eddbid:1121 },
//            30340 : { mtype:'isg', cost:    18810, name:'Shield Generator', class:3, rating:'D', mass:  2.00, integ: 38, pwrdraw:1.44, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.0, bgenrate:1.87, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064269, fdname:'Int_ShieldGenerator_Size3_Class2', eddbid:1122 },
//            30330 : { mtype:'isg', cost:    56440, name:'Shield Generator', class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw:1.80, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.0, bgenrate:1.87, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064270, fdname:'Int_ShieldGenerator_Size3_Class3', eddbid:1123 },
//            30320 : { mtype:'isg', cost:   169300, name:'Shield Generator', class:3, rating:'B', mass:  8.00, integ: 90, pwrdraw:2.16, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:1.0, bgenrate:1.87, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064271, fdname:'Int_ShieldGenerator_Size3_Class4', eddbid:1124 },
//            30310 : { mtype:'isg', cost:   507910, name:'Shield Generator', class:3, rating:'A', mass:  5.00, integ: 77, pwrdraw:2.52, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.0, bgenrate:1.87, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064272, fdname:'Int_ShieldGenerator_Size3_Class5', eddbid:1125 },
//            30450 : { mtype:'isg', cost:    19880, name:'Shield Generator', class:4, rating:'E', mass: 10.00, integ: 64, pwrdraw:1.32, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.0, bgenrate:2.53, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064273, fdname:'Int_ShieldGenerator_Size4_Class1', eddbid:1126 },
//            30440 : { mtype:'isg', cost:    59630, name:'Shield Generator', class:4, rating:'D', mass:  4.00, integ: 48, pwrdraw:1.76, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.0, bgenrate:2.53, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064274, fdname:'Int_ShieldGenerator_Size4_Class2', eddbid:1127 },
//            30430 : { mtype:'isg', cost:   178900, name:'Shield Generator', class:4, rating:'C', mass: 10.00, integ: 80, pwrdraw:2.20, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.0, bgenrate:2.53, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064275, fdname:'Int_ShieldGenerator_Size4_Class3', eddbid:1128 },
//            30420 : { mtype:'isg', cost:   536690, name:'Shield Generator', class:4, rating:'B', mass: 16.00, integ:112, pwrdraw:2.64, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:1.0, bgenrate:2.53, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064276, fdname:'Int_ShieldGenerator_Size4_Class4', eddbid:1129 },
//            30410 : { mtype:'isg', cost:  1610080, name:'Shield Generator', class:4, rating:'A', mass: 10.00, integ: 96, pwrdraw:3.08, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.0, bgenrate:2.53, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064277, fdname:'Int_ShieldGenerator_Size4_Class5', eddbid:1130 },
//            30550 : { mtype:'isg', cost:    63010, name:'Shield Generator', class:5, rating:'E', mass: 20.00, integ: 77, pwrdraw:1.56, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.0, bgenrate:3.75, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064278, fdname:'Int_ShieldGenerator_Size5_Class1', eddbid:1131 },
//            30540 : { mtype:'isg', cost:   189040, name:'Shield Generator', class:5, rating:'D', mass:  8.00, integ: 58, pwrdraw:2.08, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.0, bgenrate:3.75, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064279, fdname:'Int_ShieldGenerator_Size5_Class2', eddbid:1132 },
//            30530 : { mtype:'isg', cost:   567110, name:'Shield Generator', class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw:2.60, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.0, bgenrate:3.75, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064280, fdname:'Int_ShieldGenerator_Size5_Class3', eddbid:1133 },
//            30520 : { mtype:'isg', cost:  1701320, name:'Shield Generator', class:5, rating:'B', mass: 32.00, integ:134, pwrdraw:3.12, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:1.0, bgenrate:3.75, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064281, fdname:'Int_ShieldGenerator_Size5_Class4', eddbid:1134 },
//            30510 : { mtype:'isg', cost:  5103950, name:'Shield Generator', class:5, rating:'A', mass: 20.00, integ:115, pwrdraw:3.64, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.0, bgenrate:3.75, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064282, fdname:'Int_ShieldGenerator_Size5_Class5', eddbid:1135 },
//            30650 : { mtype:'isg', cost:   199750, name:'Shield Generator', class:6, rating:'E', mass: 40.00, integ: 90, pwrdraw:1.86, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.3, bgenrate:5.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064283, fdname:'Int_ShieldGenerator_Size6_Class1', eddbid:1136 },
//            30640 : { mtype:'isg', cost:   599240, name:'Shield Generator', class:6, rating:'D', mass: 16.00, integ: 68, pwrdraw:2.48, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.3, bgenrate:5.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064284, fdname:'Int_ShieldGenerator_Size6_Class2', eddbid:1137 },
//            30630 : { mtype:'isg', cost:  1797730, name:'Shield Generator', class:6, rating:'C', mass: 40.00, integ:113, pwrdraw:3.10, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.3, bgenrate:5.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064285, fdname:'Int_ShieldGenerator_Size6_Class3', eddbid:1138 },
//            30620 : { mtype:'isg', cost:  5393180, name:'Shield Generator', class:6, rating:'B', mass: 64.00, integ:158, pwrdraw:3.72, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:1.3, bgenrate:5.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064286, fdname:'Int_ShieldGenerator_Size6_Class4', eddbid:1139 },
//            30610 : { mtype:'isg', cost: 16179530, name:'Shield Generator', class:6, rating:'A', mass: 40.00, integ:136, pwrdraw:4.34, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.3, bgenrate:5.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064287, fdname:'Int_ShieldGenerator_Size6_Class5', eddbid:1140 },
//            30750 : { mtype:'isg', cost:   633200, name:'Shield Generator', class:7, rating:'E', mass: 80.00, integ:105, pwrdraw:2.10, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:1.8, bgenrate:7.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064288, fdname:'Int_ShieldGenerator_Size7_Class1', eddbid:1141 },
//            30740 : { mtype:'isg', cost:  1899600, name:'Shield Generator', class:7, rating:'D', mass: 32.00, integ: 79, pwrdraw:2.80, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:1.8, bgenrate:7.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064289, fdname:'Int_ShieldGenerator_Size7_Class2', eddbid:1142 },
//            30730 : { mtype:'isg', cost:  5698790, name:'Shield Generator', class:7, rating:'C', mass: 80.00, integ:131, pwrdraw:3.50, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:1.8, bgenrate:7.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064290, fdname:'Int_ShieldGenerator_Size7_Class3', eddbid:1143 },
//            30720 : { mtype:'isg', cost: 17096370, name:'Shield Generator', class:7, rating:'B', mass:128.00, integ:183, pwrdraw:4.20, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:1.8, bgenrate:7.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064291, fdname:'Int_ShieldGenerator_Size7_Class4', eddbid:1144 },
//            30710 : { mtype:'isg', cost: 51289110, name:'Shield Generator', class:7, rating:'A', mass: 80.00, integ:157, pwrdraw:4.90, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:1.8, bgenrate:7.33, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064292, fdname:'Int_ShieldGenerator_Size7_Class5', eddbid:1145 },
//            30850 : { mtype:'isg', cost:  2007240, name:'Shield Generator', class:8, rating:'E', mass:160.00, integ:120, pwrdraw:2.40, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul:30, genoptmul: 80, genmaxmul:130, genrate:2.4, bgenrate:9.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064293, fdname:'Int_ShieldGenerator_Size8_Class1', eddbid:1146 },
//            30840 : { mtype:'isg', cost:  6021720, name:'Shield Generator', class:8, rating:'D', mass: 64.00, integ: 90, pwrdraw:3.20, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul:40, genoptmul: 90, genmaxmul:140, genrate:2.4, bgenrate:9.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064294, fdname:'Int_ShieldGenerator_Size8_Class2', eddbid:1147 },
//            30830 : { mtype:'isg', cost: 18065170, name:'Shield Generator', class:8, rating:'C', mass:160.00, integ:150, pwrdraw:4.00, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul:50, genoptmul:100, genmaxmul:150, genrate:2.4, bgenrate:9.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064295, fdname:'Int_ShieldGenerator_Size8_Class3', eddbid:1148 },
//            30820 : { mtype:'isg', cost: 54195500, name:'Shield Generator', class:8, rating:'B', mass:256.00, integ:210, pwrdraw:4.80, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul:60, genoptmul:110, genmaxmul:160, genrate:2.4, bgenrate:9.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064296, fdname:'Int_ShieldGenerator_Size8_Class4', eddbid:1149 },
//            30810 : { mtype:'isg', cost:162586490, name:'Shield Generator', class:8, rating:'A', mass:160.00, integ:180, pwrdraw:5.60, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul:70, genoptmul:120, genmaxmul:170, genrate:2.4, bgenrate:9.60, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128064297, fdname:'Int_ShieldGenerator_Size8_Class5', eddbid:1150 },
//    		  30132 : { mtype:'isg', cost:     7710, name:'Bi-Weave Shield Generator',  class:1, rating:'C', mass:  1.30, integ: 40, pwrdraw:1.20, boottime:1, genminmass: 13.0, genoptmass:  25.0, genmaxmass:  63.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 1.8, bgenrate: 2.40, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671331, fdname:'Int_ShieldGenerator_Size1_Class3_Fast', eddbid:1530 },
//            30232 : { mtype:'isg', cost:    26710, name:'Bi-Weave Shield Generator',  class:2, rating:'C', mass:  2.50, integ: 51, pwrdraw:1.50, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 1.8, bgenrate: 2.40, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671332, fdname:'Int_ShieldGenerator_Size2_Class3_Fast', eddbid:1531 },
//            30332 : { mtype:'isg', cost:    84650, name:'Bi-Weave Shield Generator',  class:3, rating:'C', mass:  5.00, integ: 64, pwrdraw:1.80, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 1.8, bgenrate: 2.80, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671333, fdname:'Int_ShieldGenerator_Size3_Class3_Fast', eddbid:1532 },
//            30432 : { mtype:'isg', cost:   268350, name:'Bi-Weave Shield Generator',  class:4, rating:'C', mass: 10.00, integ: 80, pwrdraw:2.20, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 1.8, bgenrate: 3.80, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671334, fdname:'Int_ShieldGenerator_Size4_Class3_Fast', eddbid:1533 },
//            30532 : { mtype:'isg', cost:   850660, name:'Bi-Weave Shield Generator',  class:5, rating:'C', mass: 20.00, integ: 96, pwrdraw:2.60, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 2.2, bgenrate: 5.63, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671335, fdname:'Int_ShieldGenerator_Size5_Class3_Fast', eddbid:1534 },
//            30632 : { mtype:'isg', cost:  2696590, name:'Bi-Weave Shield Generator',  class:6, rating:'C', mass: 40.00, integ:113, pwrdraw:3.10, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 3.2, bgenrate: 8.00, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671336, fdname:'Int_ShieldGenerator_Size6_Class3_Fast', eddbid:1535 },
//            30732 : { mtype:'isg', cost:  8548190, name:'Bi-Weave Shield Generator',  class:7, rating:'C', mass: 80.00, integ:131, pwrdraw:3.50, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 4.4, bgenrate:11.00, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671337, fdname:'Int_ShieldGenerator_Size7_Class3_Fast', eddbid:1536 },
//            30832 : { mtype:'isg', cost: 27097750, name:'Bi-Weave Shield Generator',  class:8, rating:'C', mass:160.00, integ:150, pwrdraw:4.00, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul: 40, genoptmul: 90, genmaxmul:140, genrate: 5.8, bgenrate:14.40, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671338, fdname:'Int_ShieldGenerator_Size8_Class3_Fast', eddbid:1537 },
//		      30111 : { mtype:'isg', cost:   132200, name:'Prismatic Shield Generator', tag:'P', class:1, rating:'A', mass:  2.60, integ: 48, pwrdraw:2.52, boottime:1, genminmass: 13.0, genoptmass:  25.0, genmaxmass:  63.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.0, bgenrate: 1.20, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671323, fdname:'Int_ShieldGenerator_Size1_Class5_Strong', eddbid:1485 }, // powerplay
//            30211 : { mtype:'isg', cost:   240340, name:'Prismatic Shield Generator', tag:'P', class:2, rating:'A', mass:  5.00, integ: 61, pwrdraw:3.15, boottime:1, genminmass: 28.0, genoptmass:  55.0, genmaxmass: 138.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.0, bgenrate: 1.20, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671324, fdname:'Int_ShieldGenerator_Size2_Class5_Strong', eddbid:1486 }, // powerplay
//            30311 : { mtype:'isg', cost:   761870, name:'Prismatic Shield Generator', tag:'P', class:3, rating:'A', mass: 10.00, integ: 77, pwrdraw:3.78, boottime:1, genminmass: 83.0, genoptmass: 165.0, genmaxmass: 413.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.0, bgenrate: 1.30, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671325, fdname:'Int_ShieldGenerator_Size3_Class5_Strong', eddbid:1487 }, // powerplay
//            30411 : { mtype:'isg', cost:  2415120, name:'Prismatic Shield Generator', tag:'P', class:4, rating:'A', mass: 20.00, integ: 96, pwrdraw:4.62, boottime:1, genminmass:143.0, genoptmass: 285.0, genmaxmass: 713.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.0, bgenrate: 1.66, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671326, fdname:'Int_ShieldGenerator_Size4_Class5_Strong', eddbid:1488 }, // powerplay
//            30511 : { mtype:'isg', cost:  7655930, name:'Prismatic Shield Generator', tag:'P', class:5, rating:'A', mass: 40.00, integ:115, pwrdraw:5.46, boottime:1, genminmass:203.0, genoptmass: 405.0, genmaxmass:1013.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.0, bgenrate: 2.34, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671327, fdname:'Int_ShieldGenerator_Size5_Class5_Strong', eddbid:1489 }, // powerplay
//            30611 : { mtype:'isg', cost: 24269300, name:'Prismatic Shield Generator', tag:'P', class:6, rating:'A', mass: 80.00, integ:136, pwrdraw:6.51, boottime:1, genminmass:270.0, genoptmass: 540.0, genmaxmass:1350.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.0, bgenrate: 3.20, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671328, fdname:'Int_ShieldGenerator_Size6_Class5_Strong', eddbid:1490 }, // powerplay
//            30711 : { mtype:'isg', cost: 76933670, name:'Prismatic Shield Generator', tag:'P', class:7, rating:'A', mass:160.00, integ:157, pwrdraw:7.35, boottime:1, genminmass:530.0, genoptmass:1060.0, genmaxmass:2650.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.1, bgenrate: 4.25, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671329, fdname:'Int_ShieldGenerator_Size7_Class5_Strong', eddbid:1491 }, // powerplay
//            30811 : { mtype:'isg', cost:243879730, name:'Prismatic Shield Generator', tag:'P', class:8, rating:'A', mass:320.00, integ:180, pwrdraw:8.40, boottime:1, genminmass:900.0, genoptmass:1800.0, genmaxmass:4500.0, genminmul:100, genoptmul:150, genmaxmul:200, genrate: 1.4, bgenrate: 5.40, /*thmload:1.2,*/ genpwr:0.6, kinres:40.0, thmres:-20.0, expres:50.0, axeres:95.0, limit:'isg', fdid:128671330, fdname:'Int_ShieldGenerator_Size8_Class5_Strong', eddbid:1492 }, // powerplay
//
    public static final ShieldGenerator SHIELD_GENERATOR_1_E = new ShieldGenerator("SHIELD_GENERATOR_1_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_1, ModuleClass.E, false, 300, "Int_ShieldGenerator_Size1_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.30), Map.entry(HorizonsModifier.INTEGRITY, 32.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.72), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 13.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 25.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 63.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_1_D = new ShieldGenerator("SHIELD_GENERATOR_1_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_1, ModuleClass.D, false, 1240, "Int_ShieldGenerator_Size1_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 0.50), Map.entry(HorizonsModifier.INTEGRITY, 24.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.96), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 13.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 25.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 63.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_1_C = new ShieldGenerator("SHIELD_GENERATOR_1_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_1, ModuleClass.C, false, 5140, "Int_ShieldGenerator_Size1_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.30), Map.entry(HorizonsModifier.INTEGRITY, 40.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 13.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 25.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 63.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_1_A = new ShieldGenerator("SHIELD_GENERATOR_1_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_1, ModuleClass.A, false, 88075, "Int_ShieldGenerator_Size1_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.30), Map.entry(HorizonsModifier.INTEGRITY, 48.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.68), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 13.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 25.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 63.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_2_E = new ShieldGenerator("SHIELD_GENERATOR_2_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.E, false, 1980, "Int_ShieldGenerator_Size2_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 41.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.90), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_2_D = new ShieldGenerator("SHIELD_GENERATOR_2_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.D, false, 5930, "Int_ShieldGenerator_Size2_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.00), Map.entry(HorizonsModifier.INTEGRITY, 31.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_2_C = new ShieldGenerator("SHIELD_GENERATOR_2_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.C, false, 17800, "Int_ShieldGenerator_Size2_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.50), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_2_B = new ShieldGenerator("SHIELD_GENERATOR_2_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.B, false, 53410, "Int_ShieldGenerator_Size2_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY, 71.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.80), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_2_A = new ShieldGenerator("SHIELD_GENERATOR_2_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.A, false, 160220, "Int_ShieldGenerator_Size2_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 61.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.10), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_3_E = new ShieldGenerator("SHIELD_GENERATOR_3_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.E, false, 6270, "Int_ShieldGenerator_Size3_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.08), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.87), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_3_D = new ShieldGenerator("SHIELD_GENERATOR_3_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.D, false, 18810, "Int_ShieldGenerator_Size3_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.INTEGRITY, 38.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.44), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.87), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_3_C = new ShieldGenerator("SHIELD_GENERATOR_3_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.C, false, 56440, "Int_ShieldGenerator_Size3_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.80), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.87), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_3_B = new ShieldGenerator("SHIELD_GENERATOR_3_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.B, false, 169300, "Int_ShieldGenerator_Size3_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY, 90.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.16), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.87), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_3_A = new ShieldGenerator("SHIELD_GENERATOR_3_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.A, false, 507910, "Int_ShieldGenerator_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 77.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.52), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.87), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_4_E = new ShieldGenerator("SHIELD_GENERATOR_4_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.E, false, 19880, "Int_ShieldGenerator_Size4_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.32), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.53), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_4_D = new ShieldGenerator("SHIELD_GENERATOR_4_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.D, false, 59630, "Int_ShieldGenerator_Size4_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY, 48.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.76), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.53), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_4_C = new ShieldGenerator("SHIELD_GENERATOR_4_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.C, false, 178900, "Int_ShieldGenerator_Size4_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 80.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.53), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_4_B = new ShieldGenerator("SHIELD_GENERATOR_4_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.B, false, 536690, "Int_ShieldGenerator_Size4_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 16.00), Map.entry(HorizonsModifier.INTEGRITY, 112.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.64), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.53), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_4_A = new ShieldGenerator("SHIELD_GENERATOR_4_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.A, false, 1610080, "Int_ShieldGenerator_Size4_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 96.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.08), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.53), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_5_E = new ShieldGenerator("SHIELD_GENERATOR_5_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.E, false, 63010, "Int_ShieldGenerator_Size5_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 77.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.56), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.75), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_5_D = new ShieldGenerator("SHIELD_GENERATOR_5_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.D, false, 189040, "Int_ShieldGenerator_Size5_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY, 58.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.08), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.75), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_5_C = new ShieldGenerator("SHIELD_GENERATOR_5_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.C, false, 567110, "Int_ShieldGenerator_Size5_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 96.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.60), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.75), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_5_B = new ShieldGenerator("SHIELD_GENERATOR_5_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.B, false, 1701320, "Int_ShieldGenerator_Size5_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 32.00), Map.entry(HorizonsModifier.INTEGRITY, 134.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.12), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.75), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_5_A = new ShieldGenerator("SHIELD_GENERATOR_5_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.A, false, 5103950, "Int_ShieldGenerator_Size5_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 115.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.64), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.75), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_6_E = new ShieldGenerator("SHIELD_GENERATOR_6_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.E, false, 199750, "Int_ShieldGenerator_Size6_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 90.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.86), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.3), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_6_D = new ShieldGenerator("SHIELD_GENERATOR_6_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.D, false, 599240, "Int_ShieldGenerator_Size6_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 16.00), Map.entry(HorizonsModifier.INTEGRITY, 68.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.48), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.3), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_6_C = new ShieldGenerator("SHIELD_GENERATOR_6_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.C, false, 1797730, "Int_ShieldGenerator_Size6_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 113.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.10), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.3), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_6_B = new ShieldGenerator("SHIELD_GENERATOR_6_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.B, false, 5393180, "Int_ShieldGenerator_Size6_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 64.00), Map.entry(HorizonsModifier.INTEGRITY, 158.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.72), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.3), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_6_A = new ShieldGenerator("SHIELD_GENERATOR_6_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.A, false, 16179530, "Int_ShieldGenerator_Size6_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 136.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.34), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.3), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_7_E = new ShieldGenerator("SHIELD_GENERATOR_7_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.E, false, 633200, "Int_ShieldGenerator_Size7_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 105.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.10), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 7.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_7_D = new ShieldGenerator("SHIELD_GENERATOR_7_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.D, false, 1899600, "Int_ShieldGenerator_Size7_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 32.00), Map.entry(HorizonsModifier.INTEGRITY, 79.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.80), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 7.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_7_C = new ShieldGenerator("SHIELD_GENERATOR_7_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.C, false, 5698790, "Int_ShieldGenerator_Size7_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 131.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.50), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 7.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_7_B = new ShieldGenerator("SHIELD_GENERATOR_7_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.B, false, 17096370, "Int_ShieldGenerator_Size7_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 128.00), Map.entry(HorizonsModifier.INTEGRITY, 183.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 7.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_7_A = new ShieldGenerator("SHIELD_GENERATOR_7_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.A, false, 51289110, "Int_ShieldGenerator_Size7_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 157.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.90), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 7.33), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_8_E = new ShieldGenerator("SHIELD_GENERATOR_8_E", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.E, false, 2007240, "Int_ShieldGenerator_Size8_Class1", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 120.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.40), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 30.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 80.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 130.0), Map.entry(HorizonsModifier.REGEN_RATE, 2.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 9.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_8_D = new ShieldGenerator("SHIELD_GENERATOR_8_D", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.D, false, 6021720, "Int_ShieldGenerator_Size8_Class2", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 64.00), Map.entry(HorizonsModifier.INTEGRITY, 90.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 2.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 9.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_8_C = new ShieldGenerator("SHIELD_GENERATOR_8_C", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.C, false, 18065170, "Int_ShieldGenerator_Size8_Class3", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 150.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.00), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 50.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 150.0), Map.entry(HorizonsModifier.REGEN_RATE, 2.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 9.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_8_B = new ShieldGenerator("SHIELD_GENERATOR_8_B", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.B, false, 54195500, "Int_ShieldGenerator_Size8_Class4", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 256.00), Map.entry(HorizonsModifier.INTEGRITY, 210.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.80), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 60.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 110.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 160.0), Map.entry(HorizonsModifier.REGEN_RATE, 2.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 9.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator SHIELD_GENERATOR_8_A = new ShieldGenerator("SHIELD_GENERATOR_8_A", HorizonsBlueprintName.SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.A, false, 162586490, "Int_ShieldGenerator_Size8_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 180.0), Map.entry(HorizonsModifier.POWER_DRAW, 5.60), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 2.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 9.60), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_1_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_1_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_1, ModuleClass.C, false, 7710, "Int_ShieldGenerator_Size1_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 1.30), Map.entry(HorizonsModifier.INTEGRITY, 40.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 13.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 25.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 63.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.40),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_2_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_2_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.C, false, 26710, "Int_ShieldGenerator_Size2_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.50), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.50), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.40),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_3_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_3_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.C, false, 84650, "Int_ShieldGenerator_Size3_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.80), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.80),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_4_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_4_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.C, false, 268350, "Int_ShieldGenerator_Size4_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 80.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.20), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.80),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_5_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_5_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.C, false, 850660, "Int_ShieldGenerator_Size5_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 96.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.60), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 2.2), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.63),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_6_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_6_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.C, false, 2696590, "Int_ShieldGenerator_Size6_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 113.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.10), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 3.2), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 8.00),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_7_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_7_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.C, false, 8548190, "Int_ShieldGenerator_Size7_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 131.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.50), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 4.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 11.00),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator BI_WEAVE_SHIELD_GENERATOR_8_C = new ShieldGenerator("BI_WEAVE_SHIELD_GENERATOR_8_C", HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.C, false, 27097750, "Int_ShieldGenerator_Size8_Class3_Fast", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 150.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.00), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 40.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 90.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 140.0), Map.entry(HorizonsModifier.REGEN_RATE, 5.8), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 14.40),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_1_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_1_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_1, ModuleClass.A, Origin.POWERPLAY, false, 132200, "Int_ShieldGenerator_Size1_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.60), Map.entry(HorizonsModifier.INTEGRITY, 48.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.52), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 13.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 25.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 63.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.20),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_2_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_2_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_2, ModuleClass.A, Origin.POWERPLAY, false, 240340, "Int_ShieldGenerator_Size2_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 61.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.15), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 28.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 55.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 138.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.20),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_3_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_3_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_3, ModuleClass.A, Origin.POWERPLAY, false, 761870, "Int_ShieldGenerator_Size3_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 10.00), Map.entry(HorizonsModifier.INTEGRITY, 77.0), Map.entry(HorizonsModifier.POWER_DRAW, 3.78), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.30),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_4_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_4_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_4, ModuleClass.A, Origin.POWERPLAY, false, 2415120, "Int_ShieldGenerator_Size4_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 20.00), Map.entry(HorizonsModifier.INTEGRITY, 96.0), Map.entry(HorizonsModifier.POWER_DRAW, 4.62), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 143.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 285.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 713.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.66),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_5_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_5_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_5, ModuleClass.A, Origin.POWERPLAY, false, 7655930, "Int_ShieldGenerator_Size5_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 40.00), Map.entry(HorizonsModifier.INTEGRITY, 115.0), Map.entry(HorizonsModifier.POWER_DRAW, 5.46), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 203.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 405.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1013.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 2.34),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_6_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_6_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_6, ModuleClass.A, Origin.POWERPLAY, false, 24269300, "Int_ShieldGenerator_Size6_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 80.00), Map.entry(HorizonsModifier.INTEGRITY, 136.0), Map.entry(HorizonsModifier.POWER_DRAW, 6.51), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 270.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 540.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 1350.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 3.20),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_7_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_7_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_7, ModuleClass.A, Origin.POWERPLAY, false, 76933670, "Int_ShieldGenerator_Size7_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 160.00), Map.entry(HorizonsModifier.INTEGRITY, 157.0), Map.entry(HorizonsModifier.POWER_DRAW, 7.35), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 530.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1060.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 2650.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.1), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 4.25),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    public static final ShieldGenerator PRISMATIC_SHIELD_GENERATOR_8_A = new ShieldGenerator("PRISMATIC_SHIELD_GENERATOR_8_A", HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR, ModuleSize.SIZE_8, ModuleClass.A, Origin.POWERPLAY, false, 243879730, "Int_ShieldGenerator_Size8_Class5_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 320.00), Map.entry(HorizonsModifier.INTEGRITY, 180.0), Map.entry(HorizonsModifier.POWER_DRAW, 8.40), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 900.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 1800.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 4500.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 100.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 150.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 200.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.4), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 5.40),/*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));

    public static final ShieldGenerator SHIELD_GENERATOR_3_A_PRE = new ShieldGenerator("SHIELD_GENERATOR_3_A_PRE", HorizonsBlueprintName.SHIELD_GENERATOR_PRE, ModuleSize.SIZE_3, ModuleClass.A, false, 507910, "Int_ShieldGenerator_Size3_Class5", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 5.00), Map.entry(HorizonsModifier.INTEGRITY, 77.0), Map.entry(HorizonsModifier.POWER_DRAW, 2.52), Map.entry(HorizonsModifier.BOOT_TIME, 1.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_MASS, 83.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_MASS, 165.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_MASS, 413.0), Map.entry(HorizonsModifier.SHIELDGEN_MINIMUM_STRENGTH, 70.0), Map.entry(HorizonsModifier.SHIELDGEN_OPTIMAL_STRENGTH, 120.0), Map.entry(HorizonsModifier.SHIELDGEN_MAXIMUM_STRENGTH, 170.0), Map.entry(HorizonsModifier.REGEN_RATE, 1.0), Map.entry(HorizonsModifier.BROKEN_REGEN_RATE, 1.87), /*thmload,1.2,*/ Map.entry(HorizonsModifier.ENERGY_PER_REGEN, 0.6), Map.entry(HorizonsModifier.KINETIC_RESISTANCE, 40.0), Map.entry(HorizonsModifier.THERMAL_RESISTANCE, -20.0), Map.entry(HorizonsModifier.EXPLOSIVE_RESISTANCE, 50.0), Map.entry(HorizonsModifier.CAUSTIC_RESISTANCE, 95.0)));
    static {
        SHIELD_GENERATOR_3_A_PRE.getModifications().addAll(
                List.of(
                        new Modification(HorizonsBlueprintType.THERMAL_RESISTANT_SHIELDS_KINETIC_RESISTANT_SHIELDS, 1.0, HorizonsBlueprintGrade.GRADE_5)
                )
        );
    }
    public static final List<ShieldGenerator> SHIELD_GENERATORS = List.of(
            SHIELD_GENERATOR_1_E,
            SHIELD_GENERATOR_1_D,
            SHIELD_GENERATOR_1_C,
            SHIELD_GENERATOR_1_A,
            SHIELD_GENERATOR_2_E,
            SHIELD_GENERATOR_2_D,
            SHIELD_GENERATOR_2_C,
            SHIELD_GENERATOR_2_B,
            SHIELD_GENERATOR_2_A,
            SHIELD_GENERATOR_3_E,
            SHIELD_GENERATOR_3_D,
            SHIELD_GENERATOR_3_C,
            SHIELD_GENERATOR_3_B,
            SHIELD_GENERATOR_3_A,
            SHIELD_GENERATOR_4_E,
            SHIELD_GENERATOR_4_D,
            SHIELD_GENERATOR_4_C,
            SHIELD_GENERATOR_4_B,
            SHIELD_GENERATOR_4_A,
            SHIELD_GENERATOR_5_E,
            SHIELD_GENERATOR_5_D,
            SHIELD_GENERATOR_5_C,
            SHIELD_GENERATOR_5_B,
            SHIELD_GENERATOR_5_A,
            SHIELD_GENERATOR_6_E,
            SHIELD_GENERATOR_6_D,
            SHIELD_GENERATOR_6_C,
            SHIELD_GENERATOR_6_B,
            SHIELD_GENERATOR_6_A,
            SHIELD_GENERATOR_7_E,
            SHIELD_GENERATOR_7_D,
            SHIELD_GENERATOR_7_C,
            SHIELD_GENERATOR_7_B,
            SHIELD_GENERATOR_7_A,
            SHIELD_GENERATOR_8_E,
            SHIELD_GENERATOR_8_D,
            SHIELD_GENERATOR_8_C,
            SHIELD_GENERATOR_8_B,
            SHIELD_GENERATOR_8_A,
            BI_WEAVE_SHIELD_GENERATOR_1_C,
            BI_WEAVE_SHIELD_GENERATOR_2_C,
            BI_WEAVE_SHIELD_GENERATOR_3_C,
            BI_WEAVE_SHIELD_GENERATOR_4_C,
            BI_WEAVE_SHIELD_GENERATOR_5_C,
            BI_WEAVE_SHIELD_GENERATOR_6_C,
            BI_WEAVE_SHIELD_GENERATOR_7_C,
            BI_WEAVE_SHIELD_GENERATOR_8_C,
            PRISMATIC_SHIELD_GENERATOR_1_A,
            PRISMATIC_SHIELD_GENERATOR_2_A,
            PRISMATIC_SHIELD_GENERATOR_3_A,
            PRISMATIC_SHIELD_GENERATOR_4_A,
            PRISMATIC_SHIELD_GENERATOR_5_A,
            PRISMATIC_SHIELD_GENERATOR_6_A,
            PRISMATIC_SHIELD_GENERATOR_7_A,
            PRISMATIC_SHIELD_GENERATOR_8_A,
            SHIELD_GENERATOR_3_A_PRE
    );
    public ShieldGenerator(final String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, basePrice, internalName, attributes);
    }

    public ShieldGenerator(final String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, basePrice, internalName, attributes);
    }

    public ShieldGenerator(ShieldGenerator shieldGenerator) {
        super(shieldGenerator);
    }
//    Enhanced low power
//    Kinetic resistant
//    Reinforced
//    Thermal resistant
//    Experimental Effects
//    Fast Charge
//    Multi-Weave
//    Hi-Cap
//    Lo-Draw
//    Thermo Block
//    Force Block
//    Double Braced
//    Stripped Down
    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        if(isPreEngineered()){
            return Collections.emptyList();
        }
        return ShieldGeneratorBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        if(isPreEngineered()){
            return Collections.emptyList();
        }
        return ExperimentalEffectBlueprints.SHIELD_GENERATOR.keySet().stream().toList();
    }

    @Override
    public ShieldGenerator Clone() {
        return new ShieldGenerator(this);
    }

    @Override
    public String getClarifier() {
        if (isPreEngineered() || HorizonsBlueprintName.BI_WEAVE_SHIELD_GENERATOR.equals(getName()) || HorizonsBlueprintName.PRISMATIC_SHIELD_GENERATOR.equals(getName())) {
            return " " + LocaleService.getLocalizedStringForCurrentLocale(this.getName().getLocalizationKey());
        }
        return "";

    }
    @Override
    public boolean isPreEngineered() {
        return SHIELD_GENERATOR_3_A_PRE.equals(this);
    }
    @Override
    public boolean isCGExclusive() {
        return isPreEngineered();
    }
}
