package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.constants.horizons.hardpoints.AXMissileRackBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class AXMissileRack extends HardpointModule {
    //    		  86250 : {mtype:'hexxm',cost:  540900, name:'AX Missile Rack',             mount:'F', missile:'D', class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:1.20, boottime:0, dps:35    , damage:70    , distdraw:0.140, thmload:2.40, pierce: 60,                  shotspd: 750, rof:0.500, bstint:2.000,                      ammoclip: 8, ammomax:  64,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:43   /.70   , expwgt:27  /.70   ,               ammocost:235, limit:'hex',                       fdid:128788699, fdname:'Hpt_ATDumbfireMissile_Fixed_Medium', eddbid:1614 }, // TODO: exact damage
    //            86262 : {mtype:'hexxm',cost: 2022700, name:'AX Missile Rack',             mount:'T', missile:'D', class:2, rating:'F', mass: 4.00, integ:51, pwrdraw:1.20, boottime:0, dps:28.5  , damage:57    , distdraw:0.080, thmload:1.50, pierce: 60, maximumrng:5000, shotspd: 750, rof:0.500, bstint:2.000,                      ammoclip: 8, ammomax:  64,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:37   /.57   , expwgt:20  /.57   ,               ammocost:235, limit:'hex', noblueprints:{'*':1}, fdid:128788704, fdname:'Hpt_ATDumbfireMissile_Turret_Medium', eddbid:1615 }, // TODO: exact damage
    //            86330 : {mtype:'hexxm',cost: 1352250, name:'AX Missile Rack',             mount:'F', missile:'D', class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:1.62, boottime:0, dps:35    , damage:70    , distdraw:0.240, thmload:3.60, pierce: 60,                  shotspd: 750, rof:0.500, bstint:2.000,                      ammoclip:12, ammomax: 128,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:43   /.70   , expwgt:27  /.70   ,               ammocost:235, limit:'hex',                       fdid:128788700, fdname:'Hpt_ATDumbfireMissile_Fixed_Large', eddbid:1623 }, // TODO: exact damage
    //            86352 : {mtype:'hexxm',cost: 4056750, name:'AX Missile Rack',             mount:'T', missile:'D', class:3, rating:'E', mass: 8.00, integ:64, pwrdraw:1.75, boottime:0, dps:28.5  , damage:57    , distdraw:0.140, thmload:1.90, pierce: 60, maximumrng:5000, shotspd: 750, rof:0.500, bstint:2.000,                      ammoclip:12, ammomax: 128,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:37   /.57   , expwgt:20  /.57   ,               ammocost:235, limit:'hex', noblueprints:{'*':1}, fdid:128788705, fdname:'Hpt_ATDumbfireMissile_Turret_Large', eddbid:1624 }, // TODO: exact damage
    //            86241 : {mtype:'hexxm',cost:  681530, name:'Enhanced AX Missile Rack',    mount:'F', missile:'D', class:2, rating:'D', mass: 4.00, integ:51, pwrdraw:1.30, boottime:0, dps:38.5  , damage:77    , distdraw:0.14 , thmload:2.4 , pierce: 60,                  shotspd:1250, rof:0.5  , bstint:2    ,                      ammoclip: 8, ammomax:  64,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:50   /.77   , expwgt:27  /.77   ,               ammocost:235, limit:'hex', noblueprints:{'*':1}, fdid:129022081, fdname:'Hpt_ATDumbfireMissile_Fixed_Medium_V2', eddbid:1833 }, // TODO: exact damage
    //            86259 : {mtype:'hexxm',cost: 2666290, name:'Enhanced AX Missile Rack',    mount:'T', missile:'D', class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:1.30, boottime:0, dps:32    , damage:64    , distdraw:0.08 , thmload:1.5 , pierce: 60, maximumrng:5000, shotspd:1250, rof:0.5  , bstint:2    ,                      ammoclip: 8, ammomax:  64,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:44   /.64   , expwgt:20  /.64   ,               ammocost:235, limit:'hex', noblueprints:{'*':1}, fdid:129022083, fdname:'Hpt_ATDumbfireMissile_Turret_Medium_V2', eddbid:1830 }, // TODO: exact stats
    //            86321 : {mtype:'hexxm',cost: 1703830, name:'Enhanced AX Missile Rack',    mount:'F', missile:'D', class:3, rating:'B', mass: 8.00, integ:64, pwrdraw:1.72, boottime:0, dps:38.5  , damage:77    , distdraw:0.24 , thmload:3.6 , pierce: 60,                  shotspd:1250, rof:0.5  , bstint:2    ,                      ammoclip:12, ammomax: 128,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:50   /.77   , expwgt:27  /.77   ,               ammocost:235, limit:'hex', noblueprints:{'*':1}, fdid:129022079, fdname:'Hpt_ATDumbfireMissile_Fixed_Large_V2', eddbid:1832 }, // TODO: exact damage
    //            86349 : {mtype:'hexxm',cost: 5347530, name:'Enhanced AX Missile Rack',    mount:'T', missile:'D', class:3, rating:'D', mass: 8.00, integ:64, pwrdraw:1.85, boottime:0, dps:32    , damage:64    , distdraw:0.14 , thmload:1.9 , pierce: 60, maximumrng:5000, shotspd:1250, rof:0.5  , bstint:2    ,                      ammoclip:12, ammomax: 128,            rldtime:5.0, brcdmg: 0.0, minbrc:80,maxbrc:100,             axewgt:44   /.64   , expwgt:20  /.64   ,               ammocost:235, limit:'hex', noblueprints:{'*':1}, fdid:129022082, fdname:'Hpt_ATDumbfireMissile_Turret_Large_V2', eddbid:1829 }, // TODO: exact stats

    public static final AXMissileRack AX_MISSILE_RACK_2_E_F          = new AXMissileRack("AX_MISSILE_RACK_2_E_F"         , HorizonsBlueprintName.AX_MISSILE_RACK, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED   ,  540900, "Hpt_ATDumbfireMissile_Fixed_Medium"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.0), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,1.20), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,35.0), Map.entry(HorizonsModifier.DAMAGE,70.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.14), Map.entry(HorizonsModifier.THERMAL_LOAD,2.4), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0),                                                      Map.entry(HorizonsModifier.SHOT_SPEED, 750.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE, 8.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  64.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6143), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3857), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack AX_MISSILE_RACK_2_F_T          = new AXMissileRack("AX_MISSILE_RACK_2_F_T"         , HorizonsBlueprintName.AX_MISSILE_RACK, ModuleSize.SIZE_2, ModuleClass.F, true , Mounting.TURRETED, 2022700, "Hpt_ATDumbfireMissile_Turret_Medium"     , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.0), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,1.20), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,28.5), Map.entry(HorizonsModifier.DAMAGE,57.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.08), Map.entry(HorizonsModifier.THERMAL_LOAD,1.5), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,5000.0), Map.entry(HorizonsModifier.SHOT_SPEED, 750.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE, 8.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  64.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6491), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3509), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack AX_MISSILE_RACK_3_C_F          = new AXMissileRack("AX_MISSILE_RACK_3_C_F"         , HorizonsBlueprintName.AX_MISSILE_RACK, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED   , 1352250, "Hpt_ATDumbfireMissile_Fixed_Large"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.0), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.62), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,35.0), Map.entry(HorizonsModifier.DAMAGE,70.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.24), Map.entry(HorizonsModifier.THERMAL_LOAD,3.6), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0),                                                      Map.entry(HorizonsModifier.SHOT_SPEED, 750.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,12.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM, 128.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6143), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3857), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack AX_MISSILE_RACK_3_E_T          = new AXMissileRack("AX_MISSILE_RACK_3_E_T"         , HorizonsBlueprintName.AX_MISSILE_RACK, ModuleSize.SIZE_3, ModuleClass.E, true , Mounting.TURRETED, 4056750, "Hpt_ATDumbfireMissile_Turret_Large"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.0), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.75), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,28.5), Map.entry(HorizonsModifier.DAMAGE,57.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.14), Map.entry(HorizonsModifier.THERMAL_LOAD,1.9), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,5000.0), Map.entry(HorizonsModifier.SHOT_SPEED, 750.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,12.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM, 128.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6491), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3509), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack ENHANCED_AX_MISSILE_RACK_2_D_F = new AXMissileRack("ENHANCED_AX_MISSILE_RACK_2_D_F", HorizonsBlueprintName.ENHANCED_AX_MISSILE_RACK, ModuleSize.SIZE_2, ModuleClass.D, false, Mounting.FIXED   ,  681530, "Hpt_ATDumbfireMissile_Fixed_Medium_V2"   , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.0), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,1.30), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,38.5), Map.entry(HorizonsModifier.DAMAGE,77.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.14), Map.entry(HorizonsModifier.THERMAL_LOAD,2.4), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0),                                                      Map.entry(HorizonsModifier.SHOT_SPEED,1250.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE, 8.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  64.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6494), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3506), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack ENHANCED_AX_MISSILE_RACK_2_E_T = new AXMissileRack("ENHANCED_AX_MISSILE_RACK_2_E_T", HorizonsBlueprintName.ENHANCED_AX_MISSILE_RACK, ModuleSize.SIZE_2, ModuleClass.E, true , Mounting.TURRETED, 2666290, "Hpt_ATDumbfireMissile_Turret_Medium_V2"  , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.0), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,1.30), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,32.0), Map.entry(HorizonsModifier.DAMAGE,64.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.08), Map.entry(HorizonsModifier.THERMAL_LOAD,1.5), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,5000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1250.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE, 8.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  64.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6875), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3125), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack ENHANCED_AX_MISSILE_RACK_3_B_F = new AXMissileRack("ENHANCED_AX_MISSILE_RACK_3_B_F", HorizonsBlueprintName.ENHANCED_AX_MISSILE_RACK, ModuleSize.SIZE_3, ModuleClass.B, false, Mounting.FIXED   , 1703830, "Hpt_ATDumbfireMissile_Fixed_Large_V2"    , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.0), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.72), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,38.5), Map.entry(HorizonsModifier.DAMAGE,77.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.24), Map.entry(HorizonsModifier.THERMAL_LOAD,3.6), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0),                                                      Map.entry(HorizonsModifier.SHOT_SPEED,1250.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,12.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM, 128.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6494), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3506), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack ENHANCED_AX_MISSILE_RACK_3_D_T = new AXMissileRack("ENHANCED_AX_MISSILE_RACK_3_D_T", HorizonsBlueprintName.ENHANCED_AX_MISSILE_RACK, ModuleSize.SIZE_3, ModuleClass.D, true , Mounting.TURRETED, 5347530, "Hpt_ATDumbfireMissile_Turret_Large_V2"   , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.0), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.85), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,32.0), Map.entry(HorizonsModifier.DAMAGE,64.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.14), Map.entry(HorizonsModifier.THERMAL_LOAD,1.9), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,5000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1250.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,12.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM, 128.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6875), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3125), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack AX_MISSILE_RACK_2_E_F_PRE      = new AXMissileRack("AX_MISSILE_RACK_2_E_F_PRE"     , HorizonsBlueprintName.AX_MISSILE_RACK, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED   ,  540900, "Hpt_ATDumbfireMissile_Fixed_Medium"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.0), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,1.20), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,35.0), Map.entry(HorizonsModifier.DAMAGE,70.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.14), Map.entry(HorizonsModifier.THERMAL_LOAD,2.4), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0),                                                      Map.entry(HorizonsModifier.SHOT_SPEED, 750.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE, 8.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  64.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6143), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3857), Map.entry(HorizonsModifier.AMMO_COST,235.0)));
    public static final AXMissileRack AX_MISSILE_RACK_3_C_F_PRE      = new AXMissileRack("AX_MISSILE_RACK_3_C_F_PRE"     , HorizonsBlueprintName.AX_MISSILE_RACK, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED   , 1352250, "Hpt_ATDumbfireMissile_Fixed_Large"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.0), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.62), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,35.0), Map.entry(HorizonsModifier.DAMAGE,70.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.24), Map.entry(HorizonsModifier.THERMAL_LOAD,3.6), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 60.0),                                                      Map.entry(HorizonsModifier.SHOT_SPEED, 750.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,0.5), Map.entry(HorizonsModifier.BURST_INTERVAL,2.0), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,12.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM, 128.0), Map.entry(HorizonsModifier.RELOAD_TIME,5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,80.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,100.0), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.6143), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.3857), Map.entry(HorizonsModifier.AMMO_COST,235.0)));

    static {
        AX_MISSILE_RACK_2_E_F_PRE.getModifications().addAll(
            List.of(
                new Modification(HorizonsBlueprintType.HIGH_CAPACITY_MAGAZINE, 1.0, HorizonsBlueprintGrade.GRADE_5),
                new Modification(HorizonsBlueprintType.RAPID_FIRE_MODIFICATION, 1.0, HorizonsBlueprintGrade.GRADE_5)
            )
        );
        AX_MISSILE_RACK_3_C_F_PRE.getModifications().addAll(
            List.of(
                new Modification(HorizonsBlueprintType.HIGH_CAPACITY_MAGAZINE, 1.0, HorizonsBlueprintGrade.GRADE_5),
                new Modification(HorizonsBlueprintType.RAPID_FIRE_MODIFICATION, 1.0, HorizonsBlueprintGrade.GRADE_5)
            )
        );
    }
    public static final List<AXMissileRack> AX_MISSILE_RACKS = List.of(
            AX_MISSILE_RACK_2_E_F,
            AX_MISSILE_RACK_2_F_T,
            AX_MISSILE_RACK_3_C_F,
            AX_MISSILE_RACK_3_E_T,
            ENHANCED_AX_MISSILE_RACK_2_D_F,
            ENHANCED_AX_MISSILE_RACK_2_E_T,
            ENHANCED_AX_MISSILE_RACK_3_B_F,
            ENHANCED_AX_MISSILE_RACK_3_D_T,
            AX_MISSILE_RACK_2_E_F_PRE,
            AX_MISSILE_RACK_3_C_F_PRE
    );

    public AXMissileRack(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public AXMissileRack(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public AXMissileRack(AXMissileRack axMissileRack) {
        super(axMissileRack);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        if(AX_MISSILE_RACK_2_E_F_PRE.equals(this) || AX_MISSILE_RACK_3_C_F_PRE.equals(this)){
            return AXMissileRackBlueprints.BLUEPRINTS.keySet().stream().toList();
        }
        return Collections.emptyList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public AXMissileRack Clone() {
        return new AXMissileRack(this);
    }

    @Override
    public boolean isPreEngineered() {
        return AX_MISSILE_RACK_2_E_F_PRE.equals(this) || AX_MISSILE_RACK_3_C_F_PRE.equals(this);
    }

    @Override
    public String getNonSortingClarifier() {
        if(ENHANCED_AX_MISSILE_RACK_2_D_F.equals(this) || ENHANCED_AX_MISSILE_RACK_2_E_T.equals(this) || ENHANCED_AX_MISSILE_RACK_3_B_F.equals(this) || ENHANCED_AX_MISSILE_RACK_3_D_T.equals(this)){
            return " ENH.";
        }
        return super.getNonSortingClarifier();
    }
    public boolean groupOnName() {
        return true;
    }
}
