package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class AXMultiCannon extends HardpointModule {

    //		      86253 : {mtype:'hexxc',cost:  379000, name:'AX Multi-Cannon',             mount:'F',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.46, boottime:0, dps:23.643, damage: 3.310, distdraw:0.110, thmload:0.18, pierce: 17, maximumrng:4000, shotspd:1600, rof:7.143, bstint:0.140,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 2.8, minbrc:50, maxbrc:80,             axewgt:2.190/.03310, kinwgt:1.12/.03310, dmgfall:2000, ammocost:  1, limit:'hex', fdid:128788701, fdname:'Hpt_ATMultiCannon_Fixed_Medium', eddbid:1618 }, // TODO: 85% brcmul
    //            86265 : {mtype:'hexxc',cost: 1826500, name:'AX Multi-Cannon',             mount:'T',              class:2, rating:'F', mass: 4.00, integ:51, pwrdraw:0.50, boottime:0, dps:10.812, damage: 1.730, distdraw:0.060, thmload:0.09, pierce: 17, maximumrng:4000, shotspd:1600, rof:6.250, bstint:0.160,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 0.4, minbrc:50, maxbrc:50,             axewgt:1.170/.01730, kinwgt:0.56/.01730, dmgfall:2000, ammocost:  1, limit:'hex', fdid:128793059, fdname:'Hpt_ATMultiCannon_Turret_Medium', eddbid:1619 }, // TODO: 25% brcmul
    //            86333 : {mtype:'hexxc',cost: 1181500, name:'AX Multi-Cannon',             mount:'F',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.64, boottime:0, dps:35.971, damage: 6.115, distdraw:0.180, thmload:0.28, pierce: 33, maximumrng:4000, shotspd:1600, rof:5.882, bstint:0.170,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 5.2, minbrc:50, maxbrc:80,             axewgt:3.925/.06115, kinwgt:2.19/.06115, dmgfall:2000, ammocost:  1, limit:'hex', fdid:128788702, fdname:'Hpt_ATMultiCannon_Fixed_Large', eddbid:1625 }, // TODO: 85% brcmul
    //            86355 : {mtype:'hexxc',cost: 3821600, name:'AX Multi-Cannon',             mount:'T',              class:3, rating:'E', mass: 8.00, integ:64, pwrdraw:0.64, boottime:0, dps:20.688, damage: 3.310, distdraw:0.060, thmload:0.09, pierce: 33, maximumrng:4000, shotspd:1600, rof:6.250, bstint:0.160,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 0.8, minbrc:50, maxbrc:50,             axewgt:2.190/.03310, kinwgt:1.12/.03310, dmgfall:2000, ammocost:  1, limit:'hex', fdid:128793060, fdname:'Hpt_ATMultiCannon_Turret_Large', eddbid:1626 }, // TODO: 25% brcmul
    //            86246 : {mtype:'hexxc',cost:  455080, name:'Enhanced AX Multi-Cannon',    mount:'F',              class:2, rating:'D', mass: 4.00, integ:51, pwrdraw:0.48, boottime:0, dps:27.9  , damage: 3.9  , distdraw:0.11 , thmload:0.2 , pierce: 17, maximumrng:4000, shotspd:4000, rof:7.1  , bstint:0.14 ,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 3.3, minbrc:50, maxbrc:80,             axewgt:2.8  /.039  , kinwgt:1.1 /.039  , dmgfall:2000, ammocost:  1, limit:'hex', fdid:129022080, fdname:'Hpt_ATMultiCannon_Fixed_Medium_V2', eddbid:1828 }, // TODO: exact stats // TODO: 85% brcmul
    //            86257 : {mtype:'hexxc',cost: 1197640, name:'Enhanced AX Multi-Cannon',    mount:'G',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.46, boottime:0, dps:26.4  , damage: 3.7  , distdraw:0.11 , thmload:0.2 , pierce: 17, maximumrng:4000, shotspd:4000, rof:7.1  , bstint:0.14 ,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 3.1, minbrc:50, maxbrc:80,             axewgt:2.2  /.033  , kinwgt:1.1 /.033  , dmgfall:2000, ammocost:  1, limit:'hex', fdid:129022089, fdname:'Hpt_ATMultiCannon_Gimbal_Medium', eddbid:1835 }, // TODO: exact stats // TODO: 85% brcmul
    //            86258 : {mtype:'hexxc',cost: 2193300, name:'Enhanced AX Multi-Cannon',    mount:'T',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.52, boottime:0, dps:12.5  , damage: 2.0  , distdraw:0.06 , thmload:0.1 , pierce: 17, maximumrng:4000, shotspd:4000, rof:6.2  , bstint:0.16 ,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 0.5, minbrc:50, maxbrc:50,             axewgt:1.4  /.02   , kinwgt:0.6 /.02   , dmgfall:2000, ammocost:  1, limit:'hex', fdid:129022086, fdname:'Hpt_ATMultiCannon_Turret_Medium_V2', eddbid:1827 }, // TODO: exact stats // TODO: 25% brcmul
    //            86326 : {mtype:'hexxc',cost: 1360320, name:'Enhanced AX Multi-Cannon',    mount:'F',              class:3, rating:'B', mass: 8.00, integ:64, pwrdraw:0.69, boottime:0, dps:42.9  , damage: 7.3  , distdraw:0.18 , thmload:0.3 , pierce: 33, maximumrng:4000, shotspd:4000, rof:5.9  , bstint:0.17 ,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 6.2, minbrc:50, maxbrc:80,             axewgt:5.1  /.073  , kinwgt:2.2 /.073  , dmgfall:2000, ammocost:  1, limit:'hex', fdid:129022084, fdname:'Hpt_ATMultiCannon_Fixed_Large_V2', eddbid:1831 }, // TODO: exact stats // TODO: 85% brcmul
    //            86337 : {mtype:'hexxc',cost: 2390460, name:'Enhanced AX Multi-Cannon',    mount:'G',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.64, boottime:0, dps:41.8  , damage: 6.3  , distdraw:0.18 , thmload:0.3 , pierce: 33, maximumrng:4000, shotspd:4000, rof:5.9  , bstint:0.17 ,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 5.2, minbrc:50, maxbrc:80,             axewgt:4.1  /.063  , kinwgt:2.2 /.063  , dmgfall:2000, ammocost:  1, limit:'hex', fdid:129022088, fdname:'Hpt_ATMultiCannon_Gimbal_Large', eddbid:1834 }, // TODO: exact stats // TODO: 85% brcmul
    //            86348 : {mtype:'hexxc',cost: 4588710, name:'Enhanced AX Multi-Cannon',    mount:'T',              class:3, rating:'D', mass: 8.00, integ:64, pwrdraw:0.69, boottime:0, dps:24.4  , damage: 3.9  , distdraw:0.06 , thmload:0.1 , pierce: 33, maximumrng:4000, shotspd:4000, rof:6.2  , bstint:0.16 ,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 1.0, minbrc:50, maxbrc:50,             axewgt:2.8  /.039  , kinwgt:1.1 /.039  , dmgfall:2000, ammocost:  1, limit:'hex', fdid:129022085, fdname:'Hpt_ATMultiCannon_Turret_Large_V2', eddbid:1826 }, // TODO: exact stats // TODO: 25% brcmul

    public static final AXMultiCannon  AX_MULTI_CANNON_2_E_F          = new AXMultiCannon("AX_MULTI_CANNON_2_E_F"         , HorizonsBlueprintName.AX_MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED    ,  379000, "Hpt_ATMultiCannon_Fixed_Medium"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.46), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,23.643), Map.entry(HorizonsModifier.DAMAGE, 3.310), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.110), Map.entry(HorizonsModifier.THERMAL_LOAD,0.18), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 17.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,7.143), Map.entry(HorizonsModifier.BURST_INTERVAL,0.140), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 2.8), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.2190/0.03310), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.112/0.03310), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  AX_MULTI_CANNON_2_F_T          = new AXMultiCannon("AX_MULTI_CANNON_2_F_T"         , HorizonsBlueprintName.AX_MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.F, true , Mounting.TURRETED , 1826500, "Hpt_ATMultiCannon_Turret_Medium"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.50), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,10.812), Map.entry(HorizonsModifier.DAMAGE, 1.730), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.060), Map.entry(HorizonsModifier.THERMAL_LOAD,0.09), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 17.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,6.250), Map.entry(HorizonsModifier.BURST_INTERVAL,0.160), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,90.0    ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.4), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.1170/0.01730), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.056/0.01730), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  AX_MULTI_CANNON_3_C_F          = new AXMultiCannon("AX_MULTI_CANNON_3_C_F"         , HorizonsBlueprintName.AX_MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED    , 1181500, "Hpt_ATMultiCannon_Fixed_Large"        , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.64), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,35.971), Map.entry(HorizonsModifier.DAMAGE, 6.115), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.180), Map.entry(HorizonsModifier.THERMAL_LOAD,0.28), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 33.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,5.882), Map.entry(HorizonsModifier.BURST_INTERVAL,0.170), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 5.2), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.3925/0.06115), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.219/0.06115), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  AX_MULTI_CANNON_3_E_T          = new AXMultiCannon("AX_MULTI_CANNON_3_E_T"         , HorizonsBlueprintName.AX_MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.E, true , Mounting.TURRETED , 3821600, "Hpt_ATMultiCannon_Turret_Large"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.64), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,20.688), Map.entry(HorizonsModifier.DAMAGE, 3.310), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.060), Map.entry(HorizonsModifier.THERMAL_LOAD,0.09), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 33.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,6.250), Map.entry(HorizonsModifier.BURST_INTERVAL,0.160), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,90.0    ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.8), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.2190/0.03310), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.112/0.03310), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  ENHANCED_AX_MULTI_CANNON_2_D_F = new AXMultiCannon("ENHANCED_AX_MULTI_CANNON_2_D_F", HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.D, false, Mounting.FIXED    ,  455080, "Hpt_ATMultiCannon_Fixed_Medium_V2"    , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.48), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,27.9  ), Map.entry(HorizonsModifier.DAMAGE, 3.9  ), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.11 ), Map.entry(HorizonsModifier.THERMAL_LOAD,0.2 ), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 17.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,4000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,7.1  ), Map.entry(HorizonsModifier.BURST_INTERVAL,0.14 ), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 3.3), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.28  /0.039  ), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.11 /0.039  ), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  ENHANCED_AX_MULTI_CANNON_2_E_G = new AXMultiCannon("ENHANCED_AX_MULTI_CANNON_2_E_G", HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.GIMBALLED, 1197640, "Hpt_ATMultiCannon_Gimbal_Medium"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.46), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,26.4  ), Map.entry(HorizonsModifier.DAMAGE, 3.7  ), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.11 ), Map.entry(HorizonsModifier.THERMAL_LOAD,0.2 ), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 17.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,4000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,7.1  ), Map.entry(HorizonsModifier.BURST_INTERVAL,0.14 ), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 3.1), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.22  /0.033  ), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.11 /0.033  ), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  ENHANCED_AX_MULTI_CANNON_2_E_T = new AXMultiCannon("ENHANCED_AX_MULTI_CANNON_2_E_T", HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.E, true , Mounting.TURRETED , 2193300, "Hpt_ATMultiCannon_Turret_Medium_V2"   , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.52), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,12.5  ), Map.entry(HorizonsModifier.DAMAGE, 2.0  ), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.06 ), Map.entry(HorizonsModifier.THERMAL_LOAD,0.1 ), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 17.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,4000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,6.2  ), Map.entry(HorizonsModifier.BURST_INTERVAL,0.16 ), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,90.0    ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.14  /0.02   ), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.06 /0.02   ), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  ENHANCED_AX_MULTI_CANNON_3_B_F = new AXMultiCannon("ENHANCED_AX_MULTI_CANNON_3_B_F", HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.B, false, Mounting.FIXED    , 1360320, "Hpt_ATMultiCannon_Fixed_Large_V2"     , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.69), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,42.9  ), Map.entry(HorizonsModifier.DAMAGE, 7.3  ), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.18 ), Map.entry(HorizonsModifier.THERMAL_LOAD,0.3 ), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 33.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,4000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,5.9  ), Map.entry(HorizonsModifier.BURST_INTERVAL,0.17 ), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 6.2), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.51  /0.073  ), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.22 /0.073  ), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  ENHANCED_AX_MULTI_CANNON_3_C_G = new AXMultiCannon("ENHANCED_AX_MULTI_CANNON_3_C_G", HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.GIMBALLED, 2390460, "Hpt_ATMultiCannon_Gimbal_Large"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.64), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,41.8  ), Map.entry(HorizonsModifier.DAMAGE, 6.3  ), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.18 ), Map.entry(HorizonsModifier.THERMAL_LOAD,0.3 ), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 33.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,4000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,5.9  ), Map.entry(HorizonsModifier.BURST_INTERVAL,0.17 ), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 5.2), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.41  /0.063  ), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.22 /0.063  ), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  ENHANCED_AX_MULTI_CANNON_3_D_T = new AXMultiCannon("ENHANCED_AX_MULTI_CANNON_3_D_T", HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.D, true , Mounting.TURRETED , 4588710, "Hpt_ATMultiCannon_Turret_Large_V2"    , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.69), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,24.4  ), Map.entry(HorizonsModifier.DAMAGE, 3.9  ), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.06 ), Map.entry(HorizonsModifier.THERMAL_LOAD,0.1 ), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 33.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,4000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,6.2  ), Map.entry(HorizonsModifier.BURST_INTERVAL,0.16 ), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,90.0    ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 1.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.28  /0.039  ), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.11 /0.039  ), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  AX_MULTI_CANNON_2_E_F_PRE          = new AXMultiCannon("AX_MULTI_CANNON_2_E_F_PRE" , HorizonsBlueprintName.AX_MULTI_CANNON_PRE, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED    ,  379000, "Hpt_ATMultiCannon_Fixed_Medium"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,51.0), Map.entry(HorizonsModifier.POWER_DRAW,0.46), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,23.643), Map.entry(HorizonsModifier.DAMAGE, 3.310), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.110), Map.entry(HorizonsModifier.THERMAL_LOAD,0.18), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 17.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,7.143), Map.entry(HorizonsModifier.BURST_INTERVAL,0.140), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 2.8), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.2190/0.03310), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.112/0.03310), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));
    public static final AXMultiCannon  AX_MULTI_CANNON_3_C_F_PRE          = new AXMultiCannon("AX_MULTI_CANNON_3_C_F_PRE" , HorizonsBlueprintName.AX_MULTI_CANNON_PRE, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED    , 1181500, "Hpt_ATMultiCannon_Fixed_Large"        , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,0.64), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,35.971), Map.entry(HorizonsModifier.DAMAGE, 6.115), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.180), Map.entry(HorizonsModifier.THERMAL_LOAD,0.28), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 33.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,5.882), Map.entry(HorizonsModifier.BURST_INTERVAL,0.170), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,100.0   ), Map.entry(HorizonsModifier.AMMO_MAXIMUM,2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 5.2), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,0.50), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,0.80), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO,0.3925/0.06115), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.219/0.06115), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,2000.0), Map.entry(HorizonsModifier.AMMO_COST,  1.0)));

    static {
        AX_MULTI_CANNON_2_E_F_PRE.getModifications().add(
            new Modification(HorizonsBlueprintType.OVERCHARGED_WEAPON_AUTO_LOADER, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
        AX_MULTI_CANNON_3_C_F_PRE.getModifications().add(
            new Modification(HorizonsBlueprintType.OVERCHARGED_WEAPON_AUTO_LOADER, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
    }
    public static final List<AXMultiCannon> AX_MULTI_CANNONS = List.of(
            AX_MULTI_CANNON_2_E_F,
            AX_MULTI_CANNON_2_F_T,
            AX_MULTI_CANNON_3_C_F,
            AX_MULTI_CANNON_3_E_T,
            ENHANCED_AX_MULTI_CANNON_2_D_F,
            ENHANCED_AX_MULTI_CANNON_2_E_G,
            ENHANCED_AX_MULTI_CANNON_2_E_T,
            ENHANCED_AX_MULTI_CANNON_3_B_F,
            ENHANCED_AX_MULTI_CANNON_3_C_G,
            ENHANCED_AX_MULTI_CANNON_3_D_T,
            AX_MULTI_CANNON_2_E_F_PRE,
            AX_MULTI_CANNON_3_C_F_PRE
    );
    public AXMultiCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public AXMultiCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public AXMultiCannon(AXMultiCannon axMultiCannon) {
        super(axMultiCannon);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return Collections.emptyList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public AXMultiCannon Clone() {
        return new AXMultiCannon(this);
    }

    @Override
    public boolean isPreEngineered() {
        return AX_MULTI_CANNON_2_E_F_PRE.equals(this) || AX_MULTI_CANNON_3_C_F_PRE.equals(this);
    }
    @Override
    public String getNonSortingClarifier() {
        if(this.getName().equals(HorizonsBlueprintName.ENHANCED_AX_MULTI_CANNON)){
            return " ENH";
        }
        return super.getNonSortingClarifier();
    }
    public boolean groupOnName() {
        return true;
    }

}
