package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.hardpoints.BurstLaserBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;
import nl.jixxed.eliteodysseymaterials.service.LocaleService;

import java.util.List;
import java.util.Map;

public class BurstLaser extends HardpointModule {
    //
    //		      61160 : { mtype:'hul', cost:    4400, name:'Burst Laser',                 mount:'F',              class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.65, boottime:0, dps: 8.147, damage: 1.720, distdraw:0.250, thmload:0.38, pierce: 20, maximumrng:3000,               rof:4.737, bstint:0.500, bstrof:15, bstsize:3,                                                   brcdmg: 1.5, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049400, fdname:'Hpt_PulseLaserBurst_Fixed_Small', eddbid:832 },
    //            61171 : { mtype:'hul', cost:    8600, name:'Burst Laser',                 mount:'G',              class:1, rating:'G', mass: 2.00, integ:40, pwrdraw:0.64, boottime:0, dps: 6.448, damage: 1.220, distdraw:0.240, thmload:0.34, pierce: 20, maximumrng:3000,               rof:5.285, bstint:0.450, bstrof:17, bstsize:3,                                                   brcdmg: 1.0, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049404, fdname:'Hpt_PulseLaserBurst_Gimbal_Small', eddbid:835 },
    //            61172 : { mtype:'hul', cost:   52800, name:'Burst Laser',                 mount:'T',              class:1, rating:'G', mass: 2.00, integ:40, pwrdraw:0.60, boottime:0, dps: 4.174, damage: 0.870, distdraw:0.139, thmload:0.19, pierce: 20, maximumrng:3000,               rof:4.798, bstint:0.520, bstrof:19, bstsize:3,                                                   brcdmg: 0.4, minbrc:60, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049407, fdname:'Hpt_PulseLaserBurst_Turret_Small', eddbid:838 },
    //            61250 : { mtype:'hul', cost:   23000, name:'Burst Laser',                 mount:'F',              class:2, rating:'E', mass: 4.00, integ:40, pwrdraw:1.05, boottime:0, dps:13.045, damage: 3.530, distdraw:0.500, thmload:0.78, pierce: 35, maximumrng:3000,               rof:3.695, bstint:0.630, bstrof:11, bstsize:3,                                                   brcdmg: 3.0, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049401, fdname:'Hpt_PulseLaserBurst_Fixed_Medium', eddbid:833 },
    //            61261 : { mtype:'hul', cost:   48500, name:'Burst Laser',                 mount:'G',              class:2, rating:'F', mass: 4.00, integ:40, pwrdraw:1.04, boottime:0, dps:10.296, damage: 2.450, distdraw:0.490, thmload:0.67, pierce: 35, maximumrng:3000,               rof:4.203, bstint:0.560, bstrof:13, bstsize:3,                                                   brcdmg: 2.1, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049405, fdname:'Hpt_PulseLaserBurst_Gimbal_Medium', eddbid:836 },
    //            61262 : { mtype:'hul', cost:  162800, name:'Burst Laser',                 mount:'T',              class:2, rating:'F', mass: 4.00, integ:40, pwrdraw:0.98, boottime:0, dps: 6.760, damage: 1.720, distdraw:0.275, thmload:0.38, pierce: 35, maximumrng:3000,               rof:3.930, bstint:0.630, bstrof:15, bstsize:3,                                                   brcdmg: 0.9, minbrc:60, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049408, fdname:'Hpt_PulseLaserBurst_Turret_Medium', eddbid:839 },
    //            61340 : { mtype:'hul', cost:  140400, name:'Burst Laser',                 mount:'F',              class:3, rating:'D', mass: 8.00, integ:64, pwrdraw:1.66, boottime:0, dps:20.785, damage: 7.730, distdraw:1.110, thmload:1.70, pierce: 52, maximumrng:3000,               rof:2.689, bstint:0.830, bstrof: 7, bstsize:3,                                                   brcdmg: 3.9, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049402, fdname:'Hpt_PulseLaserBurst_Fixed_Large', eddbid:834 },
    //            61351 : { mtype:'hul', cost:  281600, name:'Burst Laser',                 mount:'G',              class:3, rating:'E', mass: 8.00, integ:64, pwrdraw:1.65, boottime:0, dps:16.605, damage: 5.160, distdraw:1.030, thmload:1.42, pierce: 52, maximumrng:3000,               rof:3.218, bstint:0.710, bstrof: 9, bstsize:3,                                                   brcdmg: 4.4, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049406, fdname:'Hpt_PulseLaserBurst_Gimbal_Large', eddbid:837 },
    //            61352 : { mtype:'hul', cost:  800400, name:'Burst Laser',                 mount:'T',              class:3, rating:'E', mass: 8.00, integ:64, pwrdraw:1.57, boottime:0, dps:11.010, damage: 3.530, distdraw:0.560, thmload:0.78, pierce: 52, maximumrng:3000,               rof:3.119, bstint:0.780, bstrof:11, bstsize:3,                                                   brcdmg: 1.8, minbrc:60, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049409, fdname:'Hpt_PulseLaserBurst_Turret_Large', eddbid:840 },
    //            61450 : { mtype:'hul', cost:  281600, name:'Burst Laser',                 mount:'F',              class:4, rating:'E', mass:16.00, integ:80, pwrdraw:2.58, boottime:0, dps:32.259, damage:20.610, distdraw:2.980, thmload:4.53, pierce: 65, maximumrng:3000,               rof:1.565, bstint:1.250, bstrof: 3, bstsize:3,                                                   brcdmg:17.5, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128049403, fdname:'Hpt_PulseLaserBurst_Fixed_Huge', eddbid:1549 },
    //            61451 : { mtype:'hul', cost: 1245600, name:'Burst Laser',                 mount:'G',              class:4, rating:'E', mass:16.00, integ:64, pwrdraw:2.59, boottime:0, dps:25.907, damage:12.090, distdraw:2.410, thmload:3.33, pierce: 65, maximumrng:3000,               rof:2.143, bstint:1.000, bstrof: 5, bstsize:3,                                                   brcdmg:10.3, minbrc:40, maxbrc:80,             thmwgt:100, kinwgt:0, dmgfall:500, fdid:128727920, fdname:'Hpt_PulseLaserBurst_Gimbal_Huge', eddbid:1550 },
    //            61164 : { mtype:'hul', cost:    8800, name:'Cytoscrambler Burst Laser',   mount:'F', tag:'P',     class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.80, boottime:0, dps:27.429, damage: 3.600, distdraw:0.310, thmload:0.28, pierce:  1, maximumrng:1000,               rof:7.619, bstint:0.700, bstrof:20, bstsize:8,                                                   brcdmg: 3.1, minbrc: 0, maxbrc: 0, jitter:1.70,thmwgt:100, kinwgt:0, dmgfall:600, fdid:128671449, fdname:'Hpt_PulseLaserBurst_Fixed_Small_Scatter', eddbid:1477 }, // powerplay // verify jitter
    public static final BurstLaser BURST_LASER_1_F_F               = new BurstLaser("BURST_LASER_1_E_F"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_1, ModuleClass.F,                  false, Mounting.FIXED    ,       4400, "Hpt_PulseLaserBurst_Fixed_Small"        , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,0.65), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 8.147), Map.entry(HorizonsModifier.DAMAGE, 1.720), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.250), Map.entry(HorizonsModifier.THERMAL_LOAD,0.38), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 20.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,4.737), Map.entry(HorizonsModifier.BURST_INTERVAL,0.500), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,15.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 1.5), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_1_G_G               = new BurstLaser("BURST_LASER_1_E_G"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_1, ModuleClass.G,                  false, Mounting.GIMBALLED,       8600, "Hpt_PulseLaserBurst_Gimbal_Small"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,0.64), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 6.448), Map.entry(HorizonsModifier.DAMAGE, 1.220), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.240), Map.entry(HorizonsModifier.THERMAL_LOAD,0.34), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 20.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,5.285), Map.entry(HorizonsModifier.BURST_INTERVAL,0.450), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,17.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 1.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_1_G_T               = new BurstLaser("BURST_LASER_1_F_T"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_1, ModuleClass.G,                  true , Mounting.TURRETED ,      52800, "Hpt_PulseLaserBurst_Turret_Small"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,0.60), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 4.174), Map.entry(HorizonsModifier.DAMAGE, 0.870), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.139), Map.entry(HorizonsModifier.THERMAL_LOAD,0.19), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 20.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,4.798), Map.entry(HorizonsModifier.BURST_INTERVAL,0.520), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,19.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.4), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_2_E_F               = new BurstLaser("BURST_LASER_2_D_F"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_2, ModuleClass.E,                  false, Mounting.FIXED    ,      23000, "Hpt_PulseLaserBurst_Fixed_Medium"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,1.05), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,13.045), Map.entry(HorizonsModifier.DAMAGE, 3.530), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.500), Map.entry(HorizonsModifier.THERMAL_LOAD,0.78), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 35.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,3.695), Map.entry(HorizonsModifier.BURST_INTERVAL,0.630), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,11.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 3.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_2_F_G               = new BurstLaser("BURST_LASER_2_D_G"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_2, ModuleClass.F,                  false, Mounting.GIMBALLED,      48500, "Hpt_PulseLaserBurst_Gimbal_Medium"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,1.04), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,10.296), Map.entry(HorizonsModifier.DAMAGE, 2.450), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.490), Map.entry(HorizonsModifier.THERMAL_LOAD,0.67), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 35.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,4.203), Map.entry(HorizonsModifier.BURST_INTERVAL,0.560), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,13.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 2.1), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_2_F_T               = new BurstLaser("BURST_LASER_2_E_T"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_2, ModuleClass.F,                  true , Mounting.TURRETED ,     162800, "Hpt_PulseLaserBurst_Turret_Medium"      , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 4.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,0.98), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 6.760), Map.entry(HorizonsModifier.DAMAGE, 1.720), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.275), Map.entry(HorizonsModifier.THERMAL_LOAD,0.38), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 35.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,3.930), Map.entry(HorizonsModifier.BURST_INTERVAL,0.630), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,15.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 0.9), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_3_D_F               = new BurstLaser("BURST_LASER_3_C_F"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_3, ModuleClass.D,                  false, Mounting.FIXED    ,     140400, "Hpt_PulseLaserBurst_Fixed_Large"        , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.66), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,20.785), Map.entry(HorizonsModifier.DAMAGE, 7.730), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,1.110), Map.entry(HorizonsModifier.THERMAL_LOAD,1.70), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 52.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,2.689), Map.entry(HorizonsModifier.BURST_INTERVAL,0.830), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE, 7.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 3.9), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_3_E_G               = new BurstLaser("BURST_LASER_3_C_G"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_3, ModuleClass.E,                  false, Mounting.GIMBALLED,     281600, "Hpt_PulseLaserBurst_Gimbal_Large"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.65), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,16.605), Map.entry(HorizonsModifier.DAMAGE, 5.160), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,1.030), Map.entry(HorizonsModifier.THERMAL_LOAD,1.42), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 52.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,3.218), Map.entry(HorizonsModifier.BURST_INTERVAL,0.710), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE, 9.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 4.4), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_3_E_T               = new BurstLaser("BURST_LASER_3_D_T"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_3, ModuleClass.E,                  true , Mounting.TURRETED ,     800400, "Hpt_PulseLaserBurst_Turret_Large"       , Map.ofEntries(Map.entry(HorizonsModifier.MASS, 8.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,1.57), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,11.010), Map.entry(HorizonsModifier.DAMAGE, 3.530), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.560), Map.entry(HorizonsModifier.THERMAL_LOAD,0.78), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 52.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,3.119), Map.entry(HorizonsModifier.BURST_INTERVAL,0.780), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,11.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 1.8), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_4_E_F               = new BurstLaser("BURST_LASER_4_A_F"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_4, ModuleClass.E,                  false, Mounting.FIXED    ,     281600, "Hpt_PulseLaserBurst_Fixed_Huge"         , Map.ofEntries(Map.entry(HorizonsModifier.MASS,16.00), Map.entry(HorizonsModifier.INTEGRITY,80.0), Map.entry(HorizonsModifier.POWER_DRAW,2.58), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,32.259), Map.entry(HorizonsModifier.DAMAGE,20.610), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,2.980), Map.entry(HorizonsModifier.THERMAL_LOAD,4.53), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 65.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,1.565), Map.entry(HorizonsModifier.BURST_INTERVAL,1.250), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE, 3.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,17.5), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser BURST_LASER_4_E_G               = new BurstLaser("BURST_LASER_4_A_G"              , HorizonsBlueprintName.BURST_LASER, ModuleSize.SIZE_4, ModuleClass.E,                  false, Mounting.GIMBALLED,    1245600, "Hpt_PulseLaserBurst_Gimbal_Huge"        , Map.ofEntries(Map.entry(HorizonsModifier.MASS,16.00), Map.entry(HorizonsModifier.INTEGRITY,64.0), Map.entry(HorizonsModifier.POWER_DRAW,2.59), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,25.907), Map.entry(HorizonsModifier.DAMAGE,12.090), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,2.410), Map.entry(HorizonsModifier.THERMAL_LOAD,3.33), Map.entry(HorizonsModifier.ARMOUR_PIERCING, 65.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,3000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,2.143), Map.entry(HorizonsModifier.BURST_INTERVAL,1.000), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE, 5.0), Map.entry(HorizonsModifier.BURST_SIZE,3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,10.3), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN,40.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX,80.0),                                             Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,500.0)));
    public static final BurstLaser CYTOSCRAMBLER_BURST_LASER_1_F_F = new BurstLaser("CYTOSCRAMBLER_BURST_LASER_1_E_F", HorizonsBlueprintName.CYTOSCRAMBLER_BURST_LASER, ModuleSize.SIZE_1, ModuleClass.F, Origin.POWERPLAY,false, Mounting.FIXED    ,       8800, "Hpt_PulseLaserBurst_Fixed_Small_Scatter", Map.ofEntries(Map.entry(HorizonsModifier.MASS, 2.00), Map.entry(HorizonsModifier.INTEGRITY,40.0), Map.entry(HorizonsModifier.POWER_DRAW,0.80), Map.entry(HorizonsModifier.BOOT_TIME,0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,27.429), Map.entry(HorizonsModifier.DAMAGE, 3.600), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,0.310), Map.entry(HorizonsModifier.THERMAL_LOAD,0.28), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  1.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,1000.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,7.619), Map.entry(HorizonsModifier.BURST_INTERVAL,0.700), Map.entry(HorizonsModifier.BURST_RATE_OF_FIRE,20.0), Map.entry(HorizonsModifier.BURST_SIZE,8.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 3.1), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 0.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 0.0), Map.entry(HorizonsModifier.JITTER,1.70), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,100.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,600.0)));
   
    public static final List<BurstLaser> BURST_LASERS = List.of(
        BURST_LASER_1_F_F,
        BURST_LASER_1_G_G,
        BURST_LASER_1_G_T,
        BURST_LASER_2_E_F,
        BURST_LASER_2_F_G,
        BURST_LASER_2_F_T,
        BURST_LASER_3_D_F,
        BURST_LASER_3_E_G,
        BURST_LASER_3_E_T,
        BURST_LASER_4_E_F,
        BURST_LASER_4_E_G,
        CYTOSCRAMBLER_BURST_LASER_1_F_F
    );
    public BurstLaser(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public BurstLaser(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public BurstLaser(BurstLaser burstLaser) {
        super(burstLaser);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return BurstLaserBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return ExperimentalEffectBlueprints.BURST_LASER.keySet().stream().toList();
    }

    @Override
    public BurstLaser Clone() {
        return new BurstLaser(this);
    }
    @Override
    public String getClarifier() {
        if(CYTOSCRAMBLER_BURST_LASER_1_F_F.equals(this)){
            return " " + LocaleService.getLocalizedStringForCurrentLocale(getName().getLocalizationKey());
        }
        return super.getClarifier();
    }
}
