package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.hardpoints.CannonBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.List;
import java.util.Map;

public class Cannon extends HardpointModule {

    //		      70140 : { mtype:'hc',  cost:   21100, name:'Cannon',                      mount:'F',              class:1, rating:'D', mass: 2.00, integ:40, pwrdraw:0.34, boottime:0, dps:11.250, damage:22.500, distdraw:0.460, thmload:1.38, pierce: 35.0, maximumrng:3000.0, shotspd:1200,        rof:0.500, bstint:2.000, ammoclip: 6, ammomax: 120, rldtime:3.0, brcdmg:21.4, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:3000, ammocost:20, fdid:128049438, fdname:'Hpt_Cannon_Fixed_Small', eddbid:850 },
    //            70151 : { mtype:'hc',  cost:   42200, name:'Cannon',                      mount:'G',              class:1, rating:'E', mass: 2.00, integ:40, pwrdraw:0.38, boottime:0, dps: 8.292, damage:15.920, distdraw:0.480, thmload:1.25, pierce: 35.0, maximumrng:3000.0, shotspd:1000,        rof:0.521, bstint:1.920, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:15.1, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:3000, ammocost:20, fdid:128049442, fdname:'Hpt_Cannon_Gimbal_Small', eddbid:854 },
    //            70162 : { mtype:'hc',  cost:  506400, name:'Cannon',                      mount:'T',              class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.32, boottime:0, dps: 5.528, damage:12.770, distdraw:0.220, thmload:0.67, pierce: 35.0, maximumrng:3000.0, shotspd:1000,        rof:0.433, bstint:2.310, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:12.1, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:3000, ammocost:20, fdid:128049445, fdname:'Hpt_Cannon_Turret_Small', eddbid:857 },
    //            70240 : { mtype:'hc',  cost:  168430, name:'Cannon',                      mount:'F',              class:2, rating:'D', mass: 4.00, integ:51, pwrdraw:0.49, boottime:0, dps:16.993, damage:36.875, distdraw:0.700, thmload:2.11, pierce: 50.0, maximumrng:3500.0, shotspd:1051.051,    rof:0.461, bstint:2.170, ammoclip: 6, ammomax: 120, rldtime:3.0, brcdmg:35.0, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:3500, ammocost:20, fdid:128049439, fdname:'Hpt_Cannon_Fixed_Medium', eddbid:851 },
    //            70241 : { mtype:'hc',  cost:  337600, name:'Cannon',                      mount:'G',              class:2, rating:'D', mass: 4.00, integ:51, pwrdraw:0.54, boottime:0, dps:12.274, damage:25.530, distdraw:0.750, thmload:1.92, pierce: 50.0, maximumrng:3500.0, shotspd: 875,        rof:0.481, bstint:2.080, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:24.3, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:3500, ammocost:20, fdid:128049443, fdname:'Hpt_Cannon_Gimbal_Medium', eddbid:855 },
    //            70252 : { mtype:'hc',  cost: 4051200, name:'Cannon',                      mount:'T',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.45, boottime:0, dps: 7.916, damage:19.790, distdraw:0.340, thmload:1.03, pierce: 50.0, maximumrng:3500.0, shotspd: 875,        rof:0.400, bstint:2.500, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:18.8, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:3500, ammocost:20, fdid:128049446, fdname:'Hpt_Cannon_Turret_Medium', eddbid:858 },
    //            70330 : { mtype:'hc',  cost:  675200, name:'Cannon',                      mount:'F',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.67, boottime:0, dps:23.372, damage:55.625, distdraw:1.070, thmload:3.20, pierce: 70.0, maximumrng:4000.0, shotspd: 959.233,    rof:0.420, bstint:2.380, ammoclip: 6, ammomax: 120, rldtime:3.0, brcdmg:52.8, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:4000, ammocost:20, fdid:128049440, fdname:'Hpt_Cannon_Fixed_Large', eddbid:852 },
    //            70331 : { mtype:'hc',  cost: 1350400, name:'Cannon',                      mount:'G',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.75, boottime:0, dps:16.485, damage:37.421, distdraw:1.140, thmload:2.93, pierce: 70.0, maximumrng:4000.0, shotspd: 800,        rof:0.441, bstint:2.270, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:35.5, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:4000, ammocost:20, fdid:128671120, fdname:'Hpt_Cannon_Gimbal_Large', eddbid:1383 },
    //            70342 : { mtype:'hc',  cost:16204800, name:'Cannon',                      mount:'T',              class:3, rating:'D', mass: 8.00, integ:64, pwrdraw:0.64, boottime:0, dps:11.154, damage:30.340, distdraw:0.530, thmload:1.58, pierce: 70.0, maximumrng:4000.0, shotspd: 800,        rof:0.368, bstint:2.720, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:28.8, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:4000, ammocost:20, fdid:128049447, fdname:'Hpt_Cannon_Turret_Large', eddbid:859 },
    //            70420 : { mtype:'hc',  cost: 2700800, name:'Cannon',                      mount:'F',              class:4, rating:'B', mass:16.00, integ:80, pwrdraw:0.92, boottime:0, dps:31.606, damage:83.125, distdraw:1.610, thmload:4.83, pierce: 90.0, maximumrng:4500.0, shotspd: 900,        rof:0.380, bstint:2.630, ammoclip: 6, ammomax: 120, rldtime:3.0, brcdmg:79.0, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:4500, ammocost:20, fdid:128049441, fdname:'Hpt_Cannon_Fixed_Huge', eddbid:853 },
    //            70421 : { mtype:'hc',  cost: 5401600, name:'Cannon',                      mount:'G',              class:4, rating:'B', mass:16.00, integ:80, pwrdraw:1.03, boottime:0, dps:22.636, damage:56.590, distdraw:1.720, thmload:4.43, pierce: 90.0, maximumrng:4500.0, shotspd: 750,        rof:0.400, bstint:2.500, ammoclip: 5, ammomax: 100, rldtime:4.0, brcdmg:53.8, minbrc:60, maxbrc:90, kinwgt:100, expwgt:0, dmgfall:4500, ammocost:20, fdid:128049444, fdname:'Hpt_Cannon_Gimbal_Huge', eddbid:856 },

    //    //	704 2 : { mtype:'hc',  cost:        , name:'Cannon',                      mount:'T',              class:4, rating:   , mass:16.00, integ:80, pwrdraw:0.88, boottime:0, dps:15.456, damage:46.060, distdraw:0.800, thmload:2.40, pierce: 90, maximumrng:4500, shotspd: 750, rof:0.336, bstint:2.980,                      ammoclip: 5, ammomax: 100,            rldtime:4.0, brcdmg:    , minbrc:60, maxbrc:90,             kinwgt:100, expwgt:0, dmgfall:4500, ammocost:20, fdid:null, fdname:'Hpt_Cannon_Turret_Huge', eddbid:null },
    public static final Cannon CANNON_1_D_F = new Cannon("CANNON_1_D_F", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_1, ModuleClass.D, false, Mounting.FIXED    ,   21100, "Hpt_Cannon_Fixed_Small"  ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.00), Map.entry(HorizonsModifier.INTEGRITY, 40.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.34), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 11.250), Map.entry(HorizonsModifier.DAMAGE, 22.500), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.460), Map.entry(HorizonsModifier.THERMAL_LOAD, 1.38), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  35.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 3000.0), Map.entry(HorizonsModifier.SHOT_SPEED, 1200.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.500), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.000), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  6.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  120.0), Map.entry(HorizonsModifier.RELOAD_TIME, 3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 21.4), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 3000.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_1_E_G = new Cannon("CANNON_1_E_G", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_1, ModuleClass.E, false, Mounting.GIMBALLED,   42200, "Hpt_Cannon_Gimbal_Small" ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.00), Map.entry(HorizonsModifier.INTEGRITY, 40.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.38), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  8.292), Map.entry(HorizonsModifier.DAMAGE, 15.920), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.480), Map.entry(HorizonsModifier.THERMAL_LOAD, 1.25), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  35.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 3000.0), Map.entry(HorizonsModifier.SHOT_SPEED, 1000.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.521), Map.entry(HorizonsModifier.BURST_INTERVAL, 1.920), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 15.1), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 3000.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_1_F_T = new Cannon("CANNON_1_F_T", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_1, ModuleClass.F, true , Mounting.TURRETED ,  506400, "Hpt_Cannon_Turret_Small" ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.00), Map.entry(HorizonsModifier.INTEGRITY, 40.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.32), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  5.528), Map.entry(HorizonsModifier.DAMAGE, 12.770), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.220), Map.entry(HorizonsModifier.THERMAL_LOAD, 0.67), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  35.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 3000.0), Map.entry(HorizonsModifier.SHOT_SPEED, 1000.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.433), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.310), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 12.1), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 3000.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_2_D_F = new Cannon("CANNON_2_D_F", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_2, ModuleClass.D, false, Mounting.FIXED    ,  168430, "Hpt_Cannon_Fixed_Medium" ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.00), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.49), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 16.993), Map.entry(HorizonsModifier.DAMAGE, 36.875), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.700), Map.entry(HorizonsModifier.THERMAL_LOAD, 2.11), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  50.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 3500.0), Map.entry(HorizonsModifier.SHOT_SPEED, 1051.051), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.461), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.170), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  6.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  120.0), Map.entry(HorizonsModifier.RELOAD_TIME, 3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 35.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 3500.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_2_D_G = new Cannon("CANNON_2_D_G", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_2, ModuleClass.D, false, Mounting.GIMBALLED,  337600, "Hpt_Cannon_Gimbal_Medium",Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.00), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.54), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 12.274), Map.entry(HorizonsModifier.DAMAGE, 25.530), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.750), Map.entry(HorizonsModifier.THERMAL_LOAD, 1.92), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  50.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 3500.0), Map.entry(HorizonsModifier.SHOT_SPEED,  875.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.481), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.080), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 24.3), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 3500.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_2_E_T = new Cannon("CANNON_2_E_T", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_2, ModuleClass.E, true , Mounting.TURRETED , 4051200, "Hpt_Cannon_Turret_Medium",Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.00), Map.entry(HorizonsModifier.INTEGRITY, 51.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.45), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  7.916), Map.entry(HorizonsModifier.DAMAGE, 19.790), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.340), Map.entry(HorizonsModifier.THERMAL_LOAD, 1.03), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  50.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 3500.0), Map.entry(HorizonsModifier.SHOT_SPEED,  875.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.400), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.500), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 18.8), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 3500.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_3_C_F = new Cannon("CANNON_3_C_F", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED    ,  675200, "Hpt_Cannon_Fixed_Large"  ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.67), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 23.372), Map.entry(HorizonsModifier.DAMAGE, 55.625), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 1.070), Map.entry(HorizonsModifier.THERMAL_LOAD, 3.20), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  70.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  959.233), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.420), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.380), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  6.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  120.0), Map.entry(HorizonsModifier.RELOAD_TIME, 3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 52.8), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 4000.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_3_C_G = new Cannon("CANNON_3_C_G", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.GIMBALLED, 1350400, "Hpt_Cannon_Gimbal_Large" ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.75), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 16.485), Map.entry(HorizonsModifier.DAMAGE, 37.421), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 1.140), Map.entry(HorizonsModifier.THERMAL_LOAD, 2.93), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  70.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  800.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.441), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.270), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 35.5), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 4000.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_3_D_T = new Cannon("CANNON_3_D_T", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_3, ModuleClass.D, true , Mounting.TURRETED ,16204800, "Hpt_Cannon_Turret_Large" ,Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.00), Map.entry(HorizonsModifier.INTEGRITY, 64.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.64), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 11.154), Map.entry(HorizonsModifier.DAMAGE, 30.340), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 0.530), Map.entry(HorizonsModifier.THERMAL_LOAD, 1.58), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  70.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  800.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.368), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.720), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 28.8), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 4000.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_4_B_F = new Cannon("CANNON_4_B_F", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_4, ModuleClass.B, false, Mounting.FIXED    , 2700800, "Hpt_Cannon_Fixed_Huge"   ,Map.ofEntries(Map.entry(HorizonsModifier.MASS, 16.00), Map.entry(HorizonsModifier.INTEGRITY, 80.0), Map.entry(HorizonsModifier.POWER_DRAW, 0.92), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 31.606), Map.entry(HorizonsModifier.DAMAGE, 83.125), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 1.610), Map.entry(HorizonsModifier.THERMAL_LOAD, 4.83), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  90.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 4500.0), Map.entry(HorizonsModifier.SHOT_SPEED,  900.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.380), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.630), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  6.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  120.0), Map.entry(HorizonsModifier.RELOAD_TIME, 3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 79.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 4500.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));
    public static final Cannon CANNON_4_B_G = new Cannon("CANNON_4_B_G", HorizonsBlueprintName.CANNON, ModuleSize.SIZE_4, ModuleClass.B, false, Mounting.GIMBALLED, 5401600, "Hpt_Cannon_Gimbal_Huge"  ,Map.ofEntries(Map.entry(HorizonsModifier.MASS, 16.00), Map.entry(HorizonsModifier.INTEGRITY, 80.0), Map.entry(HorizonsModifier.POWER_DRAW, 1.03), Map.entry(HorizonsModifier.BOOT_TIME, 0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND, 22.636), Map.entry(HorizonsModifier.DAMAGE, 56.590), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW, 1.720), Map.entry(HorizonsModifier.THERMAL_LOAD, 4.43), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  90.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE, 4500.0), Map.entry(HorizonsModifier.SHOT_SPEED,  750.0  ), Map.entry(HorizonsModifier.RATE_OF_FIRE, 0.400), Map.entry(HorizonsModifier.BURST_INTERVAL, 2.500), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  100.0), Map.entry(HorizonsModifier.RELOAD_TIME, 4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE, 53.8), Map.entry(HorizonsModifier.BREACH_CHANCE_MIN, 60.0), Map.entry(HorizonsModifier.BREACH_CHANCE_MAX, 90.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO, 100.0), Map.entry(HorizonsModifier.EXPLOSIVE_DAMAGE_RATIO, 0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START, 4500.0), Map.entry(HorizonsModifier.AMMO_COST, 20.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.TARGET_PUSHED_OFF_COURSE,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_EXPLOSIVE,false), Map.entry(HorizonsModifier.TARGET_GIMBAL_TURRET_TRACKING_REDUCED,false), Map.entry(HorizonsModifier.SHIELDED_TARGET_HEAT_INCREASED,false), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false)));

    public static final List<Cannon> CANNONS = List.of(
            CANNON_1_D_F,
            CANNON_1_E_G,
            CANNON_1_F_T,
            CANNON_2_D_F,
            CANNON_2_D_G,
            CANNON_2_E_T,
            CANNON_3_C_F,
            CANNON_3_C_G,
            CANNON_3_D_T,
            CANNON_4_B_F,
            CANNON_4_B_G
    );
    public Cannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public Cannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public Cannon(Cannon cannon) {
        super(cannon);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return CannonBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return ExperimentalEffectBlueprints.CANNON.keySet().stream().toList();
    }

    @Override
    public Cannon Clone() {
        return new Cannon(this);
    }
}
