package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class GuardianShardCannon extends HardpointModule {
    //        88146 : {mtype:'hexgs',cost:  151650, name:'Guardian Shard Cannon',       mount:'F', tag:'G',     class:1, rating:'D', mass: 2.00, integ:34, pwrdraw:0.87, boottime:0, dps:72.800, damage: 3.640, distdraw:0.420, thmload:0.69, pierce: 30, maximumrng:1700, shotspd:1133, rof:1.667, bstint:0.600,                      ammoclip: 5, ammomax: 180, rounds:12, rldtime:5.0, brcdmg: 2.9, minbrc:60, maxbrc:80, jitter:5.0, thmwgt:1.820/.0364, axewgt:1.820/.0364, dmgfall:1700, ammocost:  9, limit:'hex', fdid:128891609, fdname:'Hpt_Guardian_ShardCannon_Fixed_Small', eddbid:1783 }, // guardian tech broker // TODO: 80% brcmul
    //        88168 : {mtype:'hexgs',cost:  502000, name:'Guardian Shard Cannon',       mount:'T', tag:'G',     class:1, rating:'F', mass: 2.00, integ:34, pwrdraw:0.72, boottime:0, dps:40.400, damage: 2.020, distdraw:0.360, thmload:0.58, pierce: 30, maximumrng:1700, shotspd:1133, rof:1.667, bstint:0.600,                      ammoclip: 5, ammomax: 180, rounds:12, rldtime:5.0, brcdmg: 1.6, minbrc:60, maxbrc:80, jitter:5.0, thmwgt:1.010/.0202, axewgt:1.010/.0202, dmgfall:1700, ammocost:  9, limit:'hex', fdid:128891608, fdname:'Hpt_Guardian_ShardCannon_Turret_Small', eddbid:1782 }, // guardian tech broker // TODO: 80% brcmul
    //        88216 : {mtype:'hexgs',cost:  507760, name:'Guardian Shard Cannon',       mount:'F', tag:'G',     class:2, rating:'A', mass: 4.00, integ:42, pwrdraw:1.21, boottime:0,dps:135.400, damage: 6.770, distdraw:0.650, thmload:1.20, pierce: 45, maximumrng:1700, shotspd:1133, rof:1.667, bstint:0.600,                      ammoclip: 5, ammomax: 180, rounds:12, rldtime:5.0, brcdmg: 5.4, minbrc:60, maxbrc:80, jitter:5.0, thmwgt:3.385/.0677, axewgt:3.385/.0677, dmgfall:1700, ammocost:  9, limit:'hex', fdid:128834000, fdname:'Hpt_Guardian_ShardCannon_Fixed_Medium', eddbid:1755 }, // guardian tech broker // verify cost // TODO: 80% brcmul
    //        88218 : {mtype:'hexgs',cost: 1767000, name:'Guardian Shard Cannon',       mount:'T', tag:'G',     class:2, rating:'A', mass: 4.00, integ:42, pwrdraw:1.16, boottime:0,dps: 86.800, damage: 4.340, distdraw:0.570, thmload:1.09, pierce: 45, maximumrng:1700, shotspd:1133, rof:1.667, bstint:0.600,                      ammoclip: 5, ammomax: 180, rounds:12, rldtime:5.0, brcdmg: 3.5, minbrc:60, maxbrc:80, jitter:5.0, thmwgt:2.170/.0434, axewgt:2.170/.0434, dmgfall:1700, ammocost:  9, limit:'hex', fdid:128834001, fdname:'Hpt_Guardian_ShardCannon_Turret_Medium', eddbid:1756 }, // guardian tech broker // verify cost // TODO: 80% brcmul
    //        88336 : {mtype:'hexgs',cost: 1461350, name:'Guardian Shard Cannon',       mount:'F', tag:'G',     class:3, rating:'C', mass: 8.00, integ:51, pwrdraw:1.68, boottime:0,dps:190.000, damage: 9.500, distdraw:1.400, thmload:2.20, pierce: 60, maximumrng:1700, shotspd:1133, rof:1.667, bstint:0.600,                      ammoclip: 5, ammomax: 180, rounds:12, rldtime:5.0, brcdmg: 7.6, minbrc:60, maxbrc:80, jitter:5.0, thmwgt:4.750/.0950, axewgt:4.750/.0950, dmgfall:1700, ammocost:  9, limit:'hex', fdid:128834778, fdname:'Hpt_Guardian_ShardCannon_Fixed_Large', eddbid:1760 }, // guardian tech broker // verify cost // TODO: 80% brcmul
    //        88348 : {mtype:'hexgs',cost: 5865030, name:'Guardian Shard Cannon',       mount:'T', tag:'G',     class:3, rating:'D', mass: 8.00, integ:51, pwrdraw:1.39, boottime:0,dps:124.000, damage: 6.200, distdraw:1.200, thmload:1.98, pierce: 60, maximumrng:1700, shotspd:1133, rof:1.667, bstint:0.600,                      ammoclip: 5, ammomax: 180, rounds:12, rldtime:5.0, brcdmg: 5.0, minbrc:60, maxbrc:80, jitter:5.0, thmwgt:3.100/.0620, axewgt:3.100/.0620, dmgfall:1700, ammocost:  9, limit:'hex', fdid:128834779, fdname:'Hpt_Guardian_ShardCannon_Turret_Large', eddbid:1761 }, // guardian tech broker // verify cost // TODO: 80% brcmul
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_1_D_F = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_1_D_F", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON, ModuleSize.SIZE_1, ModuleClass.D, Origin.GUARDIAN, false, Mounting.FIXED, 151650, "Hpt_Guardian_ShardCannon_Fixed_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  34.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.87), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  72.8), Map.entry(HorizonsModifier.DAMAGE,  3.64), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.42), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.69), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  30.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.9), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_1_F_T = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_1_F_T", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON, ModuleSize.SIZE_1, ModuleClass.F, Origin.GUARDIAN, true, Mounting.TURRETED, 502000, "Hpt_Guardian_ShardCannon_Turret_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  34.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.72), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  40.4), Map.entry(HorizonsModifier.DAMAGE,  2.02), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.36), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.58), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  30.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.6), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_2_A_F = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_2_A_F", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON, ModuleSize.SIZE_2, ModuleClass.A, Origin.GUARDIAN, false, Mounting.FIXED, 507760, "Hpt_Guardian_ShardCannon_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  42.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.21), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  135.4), Map.entry(HorizonsModifier.DAMAGE,  6.77), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.65), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.2), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  45.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  5.4), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_2_A_T = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_2_A_T", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON, ModuleSize.SIZE_2, ModuleClass.A, Origin.GUARDIAN, true, Mounting.TURRETED, 1767000, "Hpt_Guardian_ShardCannon_Turret_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  42.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.16), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  86.8), Map.entry(HorizonsModifier.DAMAGE,  4.34), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.57), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.09), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  45.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  3.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_3_C_F = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_3_C_F", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON, ModuleSize.SIZE_3, ModuleClass.C, Origin.GUARDIAN, false, Mounting.FIXED, 1461350, "Hpt_Guardian_ShardCannon_Fixed_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.68), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  190.0), Map.entry(HorizonsModifier.DAMAGE,  9.5), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  1.4), Map.entry(HorizonsModifier.THERMAL_LOAD,  2.2), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  7.6), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_3_D_T = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_3_D_T", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON, ModuleSize.SIZE_3, ModuleClass.D, Origin.GUARDIAN, true, Mounting.TURRETED, 5865030, "Hpt_Guardian_ShardCannon_Turret_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.39), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  124.0), Map.entry(HorizonsModifier.DAMAGE,  6.2), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  1.2), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.98), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  5.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_1_D_F_PRE = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_1_D_F_PRE", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON_PRE, ModuleSize.SIZE_1, ModuleClass.D, Origin.GUARDIAN, false, Mounting.FIXED, 151650, "Hpt_Guardian_ShardCannon_Fixed_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  34.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.87), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  72.8), Map.entry(HorizonsModifier.DAMAGE,  3.64), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.42), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.69), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  30.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.9), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    public static final GuardianShardCannon GUARDIAN_SHARD_CANNON_2_A_F_PRE = new GuardianShardCannon("GUARDIAN_SHARD_CANNON_2_A_F_PRE", HorizonsBlueprintName.GUARDIAN_SHARD_CANNON_PRE, ModuleSize.SIZE_2, ModuleClass.A, Origin.GUARDIAN, false, Mounting.FIXED, 507760, "Hpt_Guardian_ShardCannon_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  42.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.21), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  135.4), Map.entry(HorizonsModifier.DAMAGE,  6.77), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.65), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.2), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  45.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  1700.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1133.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  1.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.6), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  5.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  180.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  12.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  5.4), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  60.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.JITTER,  5.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1700.0)));
    static {
        GUARDIAN_SHARD_CANNON_1_D_F_PRE.getModifications().add(
                new Modification(HorizonsBlueprintType.LONG_RANGE_WEAPON_FOCUSED_WEAPON_PENETRATOR_MUNITIONS, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
        GUARDIAN_SHARD_CANNON_2_A_F_PRE.getModifications().add(
                new Modification(HorizonsBlueprintType.LONG_RANGE_WEAPON_FOCUSED_WEAPON_PENETRATOR_MUNITIONS, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
    }
    public static final List<GuardianShardCannon> GUARDIAN_SHARD_CANNONS = List.of(
        GUARDIAN_SHARD_CANNON_1_D_F,
        GUARDIAN_SHARD_CANNON_1_F_T,
        GUARDIAN_SHARD_CANNON_2_A_F,
        GUARDIAN_SHARD_CANNON_2_A_T,
        GUARDIAN_SHARD_CANNON_3_C_F,
        GUARDIAN_SHARD_CANNON_3_D_T,
        GUARDIAN_SHARD_CANNON_1_D_F_PRE,
        GUARDIAN_SHARD_CANNON_2_A_F_PRE
    );
    public GuardianShardCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public GuardianShardCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public GuardianShardCannon(GuardianShardCannon guardianShardCannon) {
        super(guardianShardCannon);
    }


    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return Collections.emptyList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public GuardianShardCannon Clone() {
        return new GuardianShardCannon(this);
    }

    @Override
    public boolean isPreEngineered() {
        return HorizonsBlueprintName.GUARDIAN_SHARD_CANNON_PRE.equals(this.getName());
    }
}
