package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class GuardianPlasmaCharger extends HardpointModule {
    //    		  88143 : {mtype:'hexgp',cost:  176500, name:'Guardian Plasma Charger',     mount:'F', tag:'G',     class:1, rating:'D', mass: 2.00, integ:34, pwrdraw:1.40, boottime:0, dps:15.0  , damage: 3.000, duration:1.8, dmgmul:17.0, distdraw:0.680, thmload:4.21, pierce:65, maximumrng:3000, shotspd:1200, rof:5.0, bstint:0.2,ammoclip:15, ammomax: 200,            rldtime:3.0, brcdmg: 0.75,minbrc:50, maxbrc:80,             abswgt:1.5  /.03  , axewgt:1.5  /.03  , dmgfall:1000, ammocost:100, limit:'hex', fdid:128891607, fdname:'Hpt_Guardian_PlasmaLauncher_Fixed_Small', eddbid:1781 }, // guardian tech broker // TODO: model duration,dmgmul for min-max dps // TODO: 25% brcmul
    //            88165 : {mtype:'hexgp',cost:  484050, name:'Guardian Plasma Charger',     mount:'T', tag:'G',     class:1, rating:'F', mass: 2.00, integ:34, pwrdraw:1.60, boottime:0, dps:10.0  , damage: 2.000, duration:1.8, dmgmul:17.0, distdraw:0.800, thmload:5.01, pierce:65, maximumrng:3000, shotspd:1200, rof:5.0, bstint:0.2,ammoclip:15, ammomax: 200,            rldtime:3.0, brcdmg: 0.5, minbrc:50, maxbrc:80,             abswgt:1.0  /.02  , axewgt:1.0  /.02  , dmgfall:1000, ammocost:100, limit:'hex', fdid:128891606, fdname:'Hpt_Guardian_PlasmaLauncher_Turret_Small', eddbid:1780 }, // guardian tech broker // TODO: 25% brcmul
    //            88223 : {mtype:'hexgp',cost:  567760, name:'Guardian Plasma Charger',     mount:'F', tag:'G',     class:2, rating:'B', mass: 4.00, integ:42, pwrdraw:2.13, boottime:0, dps:25.0  , damage: 5.000, duration:1.8, dmgmul:17.0, distdraw:1.250, thmload:5.21, pierce:80, maximumrng:3000, shotspd:1200, rof:5.0, bstint:0.2,ammoclip:15, ammomax: 200,            rldtime:3.0, brcdmg: 1.25,minbrc:50, maxbrc:80,             abswgt:2.5  /.05  , axewgt:2.5  /.05  , dmgfall:1000, ammocost:100, limit:'hex', fdid:128833998, fdname:'Hpt_Guardian_PlasmaLauncher_Fixed_Medium', eddbid:1753 }, // guardian tech broker // verify cost // TODO: 25% brcmul
    //            88255 : {mtype:'hexgp',cost: 1659200, name:'Guardian Plasma Charger',     mount:'T', tag:'G',     class:2, rating:'E', mass: 4.00, integ:42, pwrdraw:2.01, boottime:0, dps:20.0  , damage: 4.000, duration:1.8, dmgmul:17.0, distdraw:1.400, thmload:5.80, pierce:80, maximumrng:3000, shotspd:1200, rof:5.0, bstint:0.2,ammoclip:15, ammomax: 200,            rldtime:3.0, brcdmg: 1.0, minbrc:50, maxbrc:80,             abswgt:2.0  /.04  , axewgt:2.0  /.04  , dmgfall:1000, ammocost:100, limit:'hex', fdid:128833999, fdname:'Hpt_Guardian_PlasmaLauncher_Turret_Medium', eddbid:1754 }, // guardian tech broker // verify cost // TODO: 25% brcmul
    //            88333 : {mtype:'hexgp',cost: 1423300, name:'Guardian Plasma Charger',     mount:'F', tag:'G',     class:3, rating:'C', mass: 8.00, integ:51, pwrdraw:3.10, boottime:0, dps:35.0  , damage: 7.000, duration:1.8, dmgmul:17.0, distdraw:2.420, thmload:6.15, pierce:95, maximumrng:3000, shotspd:1200, rof:5.0, bstint:0.2,ammoclip:15, ammomax: 200,            rldtime:3.0, brcdmg: 1.75,minbrc:50, maxbrc:80,             abswgt:3.5  /.07  , axewgt:3.5  /.07  , dmgfall:1000, ammocost:100, limit:'hex', fdid:128834783, fdname:'Hpt_Guardian_PlasmaLauncher_Fixed_Large', eddbid:1765 }, // guardian tech broker // verify cost // TODO: 25% brcmul
    //            88345 : {mtype:'hexgp',cost: 5495200, name:'Guardian Plasma Charger',     mount:'T', tag:'G',     class:3, rating:'D', mass: 8.00, integ:51, pwrdraw:2.53, boottime:0, dps:30.0  , damage: 6.000, duration:1.8, dmgmul:17.0, distdraw:2.600, thmload:6.40, pierce:95, maximumrng:3000, shotspd:1200, rof:5.0, bstint:0.2,ammoclip:15, ammomax: 200,            rldtime:3.0, brcdmg: 1.5, minbrc:50, maxbrc:80,             abswgt:3.0  /.06  , axewgt:3.0  /.06  , dmgfall:1000, ammocost:100, limit:'hex', fdid:128834784, fdname:'Hpt_Guardian_PlasmaLauncher_Turret_Large', eddbid:1766 }, // guardian tech broker // verify cost // TODO: 25% brcmul
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_1_D_F = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_1_D_F", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER, ModuleSize.SIZE_1, ModuleClass.D, Origin.GUARDIAN, false, Mounting.FIXED, 176500, "Hpt_Guardian_PlasmaLauncher_Fixed_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  34.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.4), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  15.0), Map.entry(HorizonsModifier.DAMAGE,  3.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.68), Map.entry(HorizonsModifier.THERMAL_LOAD,  4.21), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  65.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  0.75), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_1_F_T = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_1_F_T", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER, ModuleSize.SIZE_1, ModuleClass.F, Origin.GUARDIAN, true, Mounting.TURRETED, 484050, "Hpt_Guardian_PlasmaLauncher_Turret_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  34.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.6), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  10.0), Map.entry(HorizonsModifier.DAMAGE,  2.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.8), Map.entry(HorizonsModifier.THERMAL_LOAD,  5.01), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  65.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  0.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_2_B_F = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_2_B_F", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER, ModuleSize.SIZE_2, ModuleClass.B, Origin.GUARDIAN, false, Mounting.FIXED, 567760, "Hpt_Guardian_PlasmaLauncher_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  42.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.13), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  25.0), Map.entry(HorizonsModifier.DAMAGE,  5.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  1.25), Map.entry(HorizonsModifier.THERMAL_LOAD,  5.21), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  80.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.25), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_2_E_T = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_2_E_T", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER, ModuleSize.SIZE_2, ModuleClass.E, Origin.GUARDIAN, true, Mounting.TURRETED, 1659200, "Hpt_Guardian_PlasmaLauncher_Turret_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  42.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.01), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  20.0), Map.entry(HorizonsModifier.DAMAGE,  4.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  1.4), Map.entry(HorizonsModifier.THERMAL_LOAD,  5.8), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  80.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_3_C_F = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_3_C_F", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER, ModuleSize.SIZE_3, ModuleClass.C, Origin.GUARDIAN, false, Mounting.FIXED, 1423300, "Hpt_Guardian_PlasmaLauncher_Fixed_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  3.1), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  35.0), Map.entry(HorizonsModifier.DAMAGE,  7.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  2.42), Map.entry(HorizonsModifier.THERMAL_LOAD,  6.15), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  95.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.75), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_3_D_T = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_3_D_T", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER, ModuleSize.SIZE_3, ModuleClass.D, Origin.GUARDIAN, true, Mounting.TURRETED, 5495200, "Hpt_Guardian_PlasmaLauncher_Turret_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.53), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  30.0), Map.entry(HorizonsModifier.DAMAGE,  6.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  2.6), Map.entry(HorizonsModifier.THERMAL_LOAD,  6.4), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  95.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_1_D_F_PRE = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_1_D_F_PRE", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER_PRE, ModuleSize.SIZE_1, ModuleClass.D, Origin.GUARDIAN, false, Mounting.FIXED, 176500, "Hpt_Guardian_PlasmaLauncher_Fixed_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  34.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.4), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  15.0), Map.entry(HorizonsModifier.DAMAGE,  3.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.68), Map.entry(HorizonsModifier.THERMAL_LOAD,  4.21), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  65.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  0.75), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    public static final GuardianPlasmaCharger GUARDIAN_PLASMA_CHARGER_2_B_F_PRE = new GuardianPlasmaCharger("GUARDIAN_PLASMA_CHARGER_2_B_F_PRE", HorizonsBlueprintName.GUARDIAN_PLASMA_CHARGER_PRE, ModuleSize.SIZE_2, ModuleClass.B, Origin.GUARDIAN, false, Mounting.FIXED, 567760, "Hpt_Guardian_PlasmaLauncher_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  42.0), Map.entry(HorizonsModifier.POWER_DRAW,  2.13), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  25.0), Map.entry(HorizonsModifier.DAMAGE,  5.0), Map.entry(HorizonsModifier.DURATION,  1.8), Map.entry(HorizonsModifier.DAMAGE_MULTIPLIER,  17.0), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  1.25), Map.entry(HorizonsModifier.THERMAL_LOAD,  5.21), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  80.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.2), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  15.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  200.0), Map.entry(HorizonsModifier.RELOAD_TIME,  3.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.25), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  50.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.ABSOLUTE_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.ANTI_XENO_DAMAGE_RATIO, 0.5), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1000.0)));
    static {
        GUARDIAN_PLASMA_CHARGER_1_D_F_PRE.getModifications().add(
                new Modification(HorizonsBlueprintType.OVERCHARGED_WEAPON_FOCUSED_WEAPON, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
        GUARDIAN_PLASMA_CHARGER_2_B_F_PRE.getModifications().add(
                new Modification(HorizonsBlueprintType.OVERCHARGED_WEAPON_FOCUSED_WEAPON, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
    }

    public static final List<GuardianPlasmaCharger> GUARDIAN_PLASMA_CHARGERS = List.of(
        GUARDIAN_PLASMA_CHARGER_1_D_F,
        GUARDIAN_PLASMA_CHARGER_1_F_T,
        GUARDIAN_PLASMA_CHARGER_2_B_F,
        GUARDIAN_PLASMA_CHARGER_2_E_T,
        GUARDIAN_PLASMA_CHARGER_3_C_F,
        GUARDIAN_PLASMA_CHARGER_3_D_T,
        GUARDIAN_PLASMA_CHARGER_1_D_F_PRE,
        GUARDIAN_PLASMA_CHARGER_2_B_F_PRE
    );
    public GuardianPlasmaCharger(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public GuardianPlasmaCharger(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public GuardianPlasmaCharger(GuardianPlasmaCharger guardianPlasmaCharger) {
        super(guardianPlasmaCharger);
    }


    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return Collections.emptyList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public GuardianPlasmaCharger Clone() {
        return new GuardianPlasmaCharger(this);
    }

    @Override
    public boolean isPreEngineered() {
        return GUARDIAN_PLASMA_CHARGER_1_D_F_PRE.equals(this) || GUARDIAN_PLASMA_CHARGER_2_B_F_PRE.equals(this);
    }
}
