package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.constants.horizons.ExperimentalEffectBlueprints;
import nl.jixxed.eliteodysseymaterials.constants.horizons.hardpoints.MultiCannonBlueprints;
import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintGrade;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;
import nl.jixxed.eliteodysseymaterials.service.LocaleService;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class MultiCannon extends HardpointModule {
    //    		  72160 : { mtype:'hmc', cost:    9500, name:'Multi-cannon',                mount:'F',              class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.28, boottime:0, dps: 8.615, damage: 1.120, distdraw:0.060, thmload:0.09, pierce: 22, maximumrng:4000, shotspd:1600, rof:7.692, bstint:0.130,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 1.0, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049455, fdname:'Hpt_MultiCannon_Fixed_Small', eddbid:867 },
    //            72171 : { mtype:'hmc', cost:   14250, name:'Multi-cannon',                mount:'G',              class:1, rating:'G', mass: 2.00, integ:40, pwrdraw:0.37, boottime:0, dps: 6.833, damage: 0.820, distdraw:0.070, thmload:0.10, pierce: 22, maximumrng:4000, shotspd:1600, rof:8.333, bstint:0.120,                      ammoclip:90, ammomax:2100,            rldtime:5.0, brcdmg: 0.7, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049459, fdname:'Hpt_MultiCannon_Gimbal_Small', eddbid:869 },
    //            72172 : { mtype:'hmc', cost:   81600, name:'Multi-cannon',                mount:'T',              class:1, rating:'G', mass: 2.00, integ:40, pwrdraw:0.26, boottime:0, dps: 4.000, damage: 0.560, distdraw:0.030, thmload:0.04, pierce: 22, maximumrng:4000, shotspd:1600, rof:7.143, bstint:0.140,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 0.5, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049462, fdname:'Hpt_MultiCannon_Turret_Small', eddbid:871 },
    //            72163 : { mtype:'hmc', cost:    9500, name:'Advanced Multi-cannon',       mount:'F',              class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.28, boottime:0, dps: 8.615, damage: 1.120, distdraw:0.060, thmload:0.09, pierce: 22, maximumrng:4000, shotspd:1600, rof:7.692, bstint:0.130,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 1.0, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128935981, fdname:'Hpt_MultiCannon_Fixed_Small_Advanced', eddbid:1812 }, // verify
    //            72250 : { mtype:'hmc', cost:   38000, name:'Multi-cannon',                mount:'F',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.46, boottime:0, dps:15.643, damage: 2.190, distdraw:0.110, thmload:0.18, pierce: 37, maximumrng:4000, shotspd:1600, rof:7.143, bstint:0.140,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 2.0, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1,                               fdid:128049456, fdname:'Hpt_MultiCannon_Fixed_Medium', eddbid:868 },
    //            72261 : { mtype:'hmc', cost:   57000, name:'Multi-cannon',                mount:'G',              class:2, rating:'F', mass: 4.00, integ:51, pwrdraw:0.64, boottime:0, dps:12.615, damage: 1.640, distdraw:0.140, thmload:0.20, pierce: 37, maximumrng:4000, shotspd:1600, rof:7.692, bstint:0.130,                      ammoclip:90, ammomax:2100,            rldtime:5.0, brcdmg: 1.5, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049460, fdname:'Hpt_MultiCannon_Gimbal_Medium', eddbid:870 },
    //            72262 : { mtype:'hmc', cost: 1292800, name:'Multi-cannon',                mount:'T',              class:2, rating:'F', mass: 4.00, integ:51, pwrdraw:0.50, boottime:0, dps: 7.313, damage: 1.170, distdraw:0.060, thmload:0.09, pierce: 37, maximumrng:4000, shotspd:1600, rof:6.250, bstint:0.160,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 1.1, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049463, fdname:'Hpt_MultiCannon_Turret_Medium', eddbid:872 },
    //            72253 : { mtype:'hmc', cost:   38000, name:'Advanced Multi-cannon',       mount:'F',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.46, boottime:0, dps:15.643, damage: 2.190, distdraw:0.110, thmload:0.18, pierce: 37, maximumrng:4000, shotspd:1600, rof:7.143, bstint:0.140,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 2.0, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128935980, fdname:'Hpt_MultiCannon_Fixed_Medium_Advanced', eddbid:1811 }, // verify
    //            72330 : { mtype:'hmc', cost:  140400, name:'Multi-cannon',                mount:'F',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.64, boottime:0, dps:23.088, damage: 3.925, distdraw:0.180, thmload:0.28, pierce: 54, maximumrng:4000, shotspd:1600, rof:5.882, bstint:0.170,                     ammoclip:100, ammomax:2100,            rldtime:4.0, brcdmg: 3.5, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049457, fdname:'Hpt_MultiCannon_Fixed_Large', eddbid:1541 },
    //            72331 : { mtype:'hmc', cost:  578440, name:'Multi-cannon',                mount:'G',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.97, boottime:0, dps:18.933, damage: 2.840, distdraw:0.250, thmload:0.34, pierce: 54, maximumrng:4000, shotspd:1600, rof:6.667, bstint:0.150,                      ammoclip:90, ammomax:2100,            rldtime:5.0, brcdmg: 2.6, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049461, fdname:'Hpt_MultiCannon_Gimbal_Large', eddbid:1543 },
    //            72352 : { mtype:'hmc', cost: 3794600, name:'Multi-cannon',                mount:'T',              class:3, rating:'E', mass: 8.00, integ:64, pwrdraw:0.86, boottime:0, dps:11.737, damage: 2.230, distdraw:0.160, thmload:0.19, pierce: 54, maximumrng:4000, shotspd:1600, rof:5.263, bstint:0.190,                      ammoclip:90, ammomax:2100,            rldtime:4.0, brcdmg: 2.0, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049464, fdname:'Hpt_MultiCannon_Turret_Large', eddbid:1658 },
    //            72410 : { mtype:'hmc', cost: 1177600, name:'Multi-cannon',                mount:'F',              class:4, rating:'A', mass:16.00, integ:80, pwrdraw:0.73, boottime:0, dps:28.030, damage: 4.625, distdraw:0.240, thmload:0.39, pierce: 68, maximumrng:4000, shotspd:1600, rof:3.030, bstint:0.330,                     ammoclip:100, ammomax:2100, rounds: 2, rldtime:4.0, brcdmg: 4.2, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128049458, fdname:'Hpt_MultiCannon_Fixed_Huge', eddbid:1542 },
    //            72411 : { mtype:'hmc', cost: 6377600, name:'Multi-cannon',                mount:'G',              class:4, rating:'A', mass:16.00, integ:80, pwrdraw:1.22, boottime:0, dps:23.300, damage: 3.460, distdraw:0.370, thmload:0.51, pierce: 68, maximumrng:4000, shotspd:1600, rof:3.367, bstint:0.297,                      ammoclip:90, ammomax:2100, rounds: 2, rldtime:5.0, brcdmg: 3.1, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall:2000, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128681996, fdname:'Hpt_MultiCannon_Gimbal_Huge', eddbid:1546 },
    //            72144 : { mtype:'hmc', cost:   14250, name:'Enforcer Cannon',             mount:'F', tag:'P',     class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.28, boottime:0, dps:12.391, damage: 2.850, distdraw:0.120, thmload:0.18, pierce: 30, maximumrng:4500, shotspd:1800, rof:4.348, bstint:0.230,                      ammoclip:60, ammomax:1000,            rldtime:4.0, brcdmg: 2.6, minbrc:40, maxbrc:80,             KINETIC_DAMAGE_RATIO:1, thmwgt:0, dmgfall: NaN, ammocostTHERMAL_DAMAGE_RATIO1, noexpeffects:{'wpnx_phse':1}, fdid:128671345, fdname:'Hpt_MultiCannon_Fixed_Small_Strong', eddbid:1481 }, // powerplay // TODO: dmgfall
    public static final MultiCannon MULTI_CANNON_1_F_F = new MultiCannon("MULTI_CANNON_1_F_F", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_1, ModuleClass.F, false, Mounting.FIXED, 9500, "Hpt_MultiCannon_Fixed_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.28), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  8.615), Map.entry(HorizonsModifier.DAMAGE,  1.12), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.06), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.09), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  22.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.692), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.13), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_1_G_G = new MultiCannon("MULTI_CANNON_1_G_G", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_1, ModuleClass.G, false, Mounting.GIMBALLED, 14250, "Hpt_MultiCannon_Gimbal_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.37), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  6.833), Map.entry(HorizonsModifier.DAMAGE,  0.82), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.07), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.1), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  22.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  8.333), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.12), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  0.7), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_1_G_T = new MultiCannon("MULTI_CANNON_1_G_T", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_1, ModuleClass.G, true, Mounting.TURRETED, 81600, "Hpt_MultiCannon_Turret_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.26), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  4.0), Map.entry(HorizonsModifier.DAMAGE,  0.56), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.03), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.04), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  22.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.143), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.14), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  0.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon ADVANCED_MULTI_CANNON_1_F_F = new MultiCannon("ADVANCED_MULTI_CANNON_1_F_F", HorizonsBlueprintName.ADVANCED_MULTI_CANNON, ModuleSize.SIZE_1, ModuleClass.F, false, Mounting.FIXED, 9500, "Hpt_MultiCannon_Fixed_Small_Advanced", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.28), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  8.615), Map.entry(HorizonsModifier.DAMAGE,  1.12), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.06), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.09), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  22.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.692), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.13), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_2_E_F = new MultiCannon("MULTI_CANNON_2_E_F", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED, 38000, "Hpt_MultiCannon_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.46), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  15.643), Map.entry(HorizonsModifier.DAMAGE,  2.19), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.11), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.18), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  37.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.143), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.14), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_2_F_G = new MultiCannon("MULTI_CANNON_2_F_G", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.F, false, Mounting.GIMBALLED, 57000, "Hpt_MultiCannon_Gimbal_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.64), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  12.615), Map.entry(HorizonsModifier.DAMAGE,  1.64), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.14), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.2), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  37.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.692), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.13), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_2_F_T = new MultiCannon("MULTI_CANNON_2_F_T", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.F, true, Mounting.TURRETED, 1292800, "Hpt_MultiCannon_Turret_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.5), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  7.313), Map.entry(HorizonsModifier.DAMAGE,  1.17), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.06), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.09), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  37.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  6.25), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.16), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  1.1), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon ADVANCED_MULTI_CANNON_2_E_F = new MultiCannon("ADVANCED_MULTI_CANNON_2_E_F", HorizonsBlueprintName.ADVANCED_MULTI_CANNON, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED, 38000, "Hpt_MultiCannon_Fixed_Medium_Advanced", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.46), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  15.643), Map.entry(HorizonsModifier.DAMAGE,  2.19), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.11), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.18), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  37.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.143), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.14), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_3_C_F = new MultiCannon("MULTI_CANNON_3_C_F", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED, 140400, "Hpt_MultiCannon_Fixed_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.64), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  23.088), Map.entry(HorizonsModifier.DAMAGE,  3.925), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.18), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.28), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  54.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.882), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.17), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  3.5), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_3_C_G = new MultiCannon("MULTI_CANNON_3_C_G", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.GIMBALLED, 578440, "Hpt_MultiCannon_Gimbal_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.97), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  18.933), Map.entry(HorizonsModifier.DAMAGE,  2.84), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.25), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.34), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  54.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  6.667), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.15), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.6), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_3_E_T = new MultiCannon("MULTI_CANNON_3_E_T", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_3, ModuleClass.E, true, Mounting.TURRETED, 3794600, "Hpt_MultiCannon_Turret_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.86), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  11.737), Map.entry(HorizonsModifier.DAMAGE,  2.23), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.16), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.19), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  54.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  5.263), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.19), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_4_A_F = new MultiCannon("MULTI_CANNON_4_A_F", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_4, ModuleClass.A, false, Mounting.FIXED, 1177600, "Hpt_MultiCannon_Fixed_Huge", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  16.0), Map.entry(HorizonsModifier.INTEGRITY,  80.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.73), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  28.03), Map.entry(HorizonsModifier.DAMAGE,  4.625), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.24), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.39), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  68.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  3.03), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.33), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  2.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  4.2), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_4_A_G = new MultiCannon("MULTI_CANNON_4_A_G", HorizonsBlueprintName.MULTI_CANNON, ModuleSize.SIZE_4, ModuleClass.A, false, Mounting.GIMBALLED, 6377600, "Hpt_MultiCannon_Gimbal_Huge", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  16.0), Map.entry(HorizonsModifier.INTEGRITY,  80.0), Map.entry(HorizonsModifier.POWER_DRAW,  1.22), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  23.3), Map.entry(HorizonsModifier.DAMAGE,  3.46), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.37), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.51), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  68.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  3.367), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.297), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  90.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.ROUNDS_PER_SHOT,  2.0), Map.entry(HorizonsModifier.RELOAD_TIME,  5.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  3.1), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon ENFORCER_CANNON_1_F_F = new MultiCannon("ENFORCER_CANNON_1_F_F", HorizonsBlueprintName.ENFORCER_MULTI_CANNON, ModuleSize.SIZE_1, ModuleClass.F, Origin.POWERPLAY, false, Mounting.FIXED, 14250, "Hpt_MultiCannon_Fixed_Small_Strong", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.28), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  12.391), Map.entry(HorizonsModifier.DAMAGE,  2.85), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.12), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.18), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  30.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4500.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1800.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  4.348), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.23), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  60.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  1000.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.6), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  1800.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));
    public static final MultiCannon MULTI_CANNON_2_E_F_PRE = new MultiCannon("MULTI_CANNON_2_E_F_PRE", HorizonsBlueprintName.MULTI_CANNON_PRE, ModuleSize.SIZE_2, ModuleClass.E, false, Mounting.FIXED, 38000, "Hpt_MultiCannon_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.46), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  15.643), Map.entry(HorizonsModifier.DAMAGE,  2.19), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.11), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.18), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  37.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  4000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1600.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  7.143), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.14), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  100.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  2100.0), Map.entry(HorizonsModifier.RELOAD_TIME,  4.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  2.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  40.0), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  80.0), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.THERMAL_DAMAGE_RATIO,  0.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2000.0), Map.entry(HorizonsModifier.JITTER,  0.0), Map.entry(HorizonsModifier.AUTO_RELOAD_WHILE_FIRING,false), Map.entry(HorizonsModifier.TARGET_SIGNATURE_INCREASED,false), Map.entry(HorizonsModifier.DAMAGE_PARTIALLY_THERMAL,false), Map.entry(HorizonsModifier.TARGET_ARMOR_HARDNESS_REDUCED,false), Map.entry(HorizonsModifier.NO_DAMAGE_TO_UNTARGETED_SHIPS,false), Map.entry(HorizonsModifier.TARGET_HEAT_INCREASED,false)));

    static{
        MULTI_CANNON_2_E_F_PRE.getModifications().add(
                new Modification(HorizonsBlueprintType.RAPID_FIRE_MODIFICATION_PHASING_SEQUENCE, 1.0, HorizonsBlueprintGrade.GRADE_5)
        );
    }
    public static final List<MultiCannon> MULTI_CANNONS = List.of(
            MULTI_CANNON_1_F_F,
            MULTI_CANNON_1_G_G,
            MULTI_CANNON_1_G_T,
            ADVANCED_MULTI_CANNON_1_F_F,
            MULTI_CANNON_2_E_F,
            MULTI_CANNON_2_F_G,
            MULTI_CANNON_2_F_T,
            ADVANCED_MULTI_CANNON_2_E_F,
            MULTI_CANNON_3_C_F,
            MULTI_CANNON_3_C_G,
            MULTI_CANNON_3_E_T,
            MULTI_CANNON_4_A_F,
            MULTI_CANNON_4_A_G,
            ENFORCER_CANNON_1_F_F,
            MULTI_CANNON_2_E_F_PRE
    );
    public MultiCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public MultiCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public MultiCannon(MultiCannon multiCannon) {
        super(multiCannon);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        if(isPreEngineered()){
            return Collections.emptyList();
        }
        return MultiCannonBlueprints.BLUEPRINTS.keySet().stream().toList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        if(isPreEngineered()){
            return Collections.emptyList();
        }
        return ExperimentalEffectBlueprints.MULTI_CANNON.keySet().stream().toList();
    }

    @Override
    public MultiCannon Clone() {
        return new MultiCannon(this);
    }

    @Override
    public String getNonSortingClarifier() {
        //TODO localize
        if(ADVANCED_MULTI_CANNON_1_F_F.equals(this) || ADVANCED_MULTI_CANNON_2_E_F.equals(this)) {
            return " Adv.";
        }
        return super.getNonSortingClarifier();
    }
    @Override
    public String getClarifier() {
        //TODO localize
        if(ENFORCER_CANNON_1_F_F.equals(this)) {
            return  " " + LocaleService.getLocalizedStringForCurrentLocale(getName().getLocalizationKey());
        }
        return super.getClarifier();
    }
    public boolean groupOnName() {
        return true;
    }

    @Override
    public boolean isPreEngineered() {
        return HorizonsBlueprintName.MULTI_CANNON_PRE.equals(this.getName());
    }
    @Override
    public boolean isCGExclusive() {
        return isPreEngineered();
    }
}
