package nl.jixxed.eliteodysseymaterials.domain.ships.hardpoint;

import nl.jixxed.eliteodysseymaterials.domain.ships.*;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintName;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType;
import nl.jixxed.eliteodysseymaterials.enums.HorizonsModifier;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class ShockCannon extends HardpointModule {
    //		      87144 : {mtype:'hexsc',cost:   65940, name:'Shock Cannon',                mount:'F',              class:1, rating:'D', mass: 2.00, integ:40, pwrdraw:0.41, boottime:0, dps:86.4  , damage: 8.640, distdraw:0.270, thmload:1.14, pierce: 25, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 6.0, minbrc:40, maxbrc:60,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128891605, fdname:'Hpt_PlasmaShockCannon_Fixed_Small', eddbid:1779 }, // human tech broker
    //            87155 : {mtype:'hexsc',cost:  137500, name:'Shock Cannon',                mount:'G',              class:1, rating:'E', mass: 2.00, integ:40, pwrdraw:0.47, boottime:0, dps:69.1  , damage: 6.910, distdraw:0.390, thmload:1.45, pierce: 25, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 4.8, minbrc:40, maxbrc:80,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128891604, fdname:'Hpt_PlasmaShockCannon_Gimbal_Small', eddbid:1778 }, // human tech broker
    //            87166 : {mtype:'hexsc',cost:  364000, name:'Shock Cannon',                mount:'T',              class:1, rating:'F', mass: 2.00, integ:40, pwrdraw:0.54, boottime:0, dps:44.7  , damage: 4.470, distdraw:0.210, thmload:0.69, pierce: 25, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 3.1, minbrc:40, maxbrc:80,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128891603, fdname:'Hpt_PlasmaShockCannon_Turret_Small', eddbid:1777 }, // human tech broker
    //            87244 : {mtype:'hexsc',cost:  367500, name:'Shock Cannon',                mount:'F',              class:2, rating:'D', mass: 4.00, integ:51, pwrdraw:0.57, boottime:0,dps:129.6  , damage:12.960, distdraw:0.470, thmload:1.80, pierce: 40, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 9.1, minbrc:40, maxbrc:60,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128834002, fdname:'Hpt_PlasmaShockCannon_Fixed_Medium', eddbid:1757 }, // human tech broker // verify cost
    //            87245 : {mtype:'hexsc',cost:  565200, name:'Shock Cannon',                mount:'G',              class:2, rating:'D', mass: 4.00, integ:51, pwrdraw:0.61, boottime:0,dps:102.1  , damage:10.210, distdraw:0.580, thmload:2.10, pierce: 40, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 7.1, minbrc:40, maxbrc:80,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128834003, fdname:'Hpt_PlasmaShockCannon_Gimbal_Medium', eddbid:1758 }, // human tech broker // verify cost
    //            87256 : {mtype:'hexsc',cost: 1359200, name:'Shock Cannon',                mount:'T',              class:2, rating:'E', mass: 4.00, integ:51, pwrdraw:0.50, boottime:0, dps:89.6  , damage: 8.960, distdraw:0.390, thmload:1.24, pierce: 40, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 6.3, minbrc:40, maxbrc:80,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128834004, fdname:'Hpt_PlasmaShockCannon_Turret_Medium', eddbid:1759 }, // human tech broker // verify cost
    //            87334 : {mtype:'hexsc',cost: 1015750, name:'Shock Cannon',                mount:'F',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.89, boottime:0,dps:181.4  , damage:18.140, distdraw:0.920, thmload:2.66, pierce: 60, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg:12.7, minbrc:40, maxbrc:60,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128834780, fdname:'Hpt_PlasmaShockCannon_Fixed_Large', eddbid:1762 }, // human tech broker // verify cost
    //            87335 : {mtype:'hexsc',cost: 2249050, name:'Shock Cannon',                mount:'G',              class:3, rating:'C', mass: 8.00, integ:64, pwrdraw:0.89, boottime:0,dps:148.7  , damage:14.870, distdraw:1.070, thmload:3.12, pierce: 60, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg:10.4, minbrc:40, maxbrc:80,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128834781, fdname:'Hpt_PlasmaShockCannon_Gimbal_Large', eddbid:1763 }, // human tech broker // verify cost
    //            87346 : {mtype:'hexsc',cost: 6050200, name:'Shock Cannon',                mount:'T',              class:3, rating:'D', mass: 8.00, integ:64, pwrdraw:0.64, boottime:0,dps:122.6  , damage:12.260, distdraw:0.790, thmload:2.20, pierce: 60, maximumrng:3000, shotspd:1200,rof:10.0  , bstint:0.1  ,                      ammoclip:16, ammomax: 240,            rldtime:6.0, brcdmg: 8.6, minbrc:40, maxbrc:80,             kinwgt:100, dmgfall:2500, ammocost:9, fdid:128834782, fdname:'Hpt_PlasmaShockCannon_Turret_Large', eddbid:1764 }, // human tech broker // verify cost
    public static final ShockCannon SHOCK_CANNON_1_D_F = new ShockCannon("SHOCK_CANNON_1_D_F", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_1, ModuleClass.D, false, Mounting.FIXED, 65940, "Hpt_PlasmaShockCannon_Fixed_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.41), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  86.4), Map.entry(HorizonsModifier.DAMAGE,  8.64), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.27), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.14), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  25.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  6.0), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.60), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_1_E_G = new ShockCannon("SHOCK_CANNON_1_E_G", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_1, ModuleClass.E, false, Mounting.GIMBALLED, 137500, "Hpt_PlasmaShockCannon_Gimbal_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.47), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  69.1), Map.entry(HorizonsModifier.DAMAGE,  6.91), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.39), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.45), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  25.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  4.8), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.80), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_1_F_T = new ShockCannon("SHOCK_CANNON_1_F_T", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_1, ModuleClass.F, true, Mounting.TURRETED, 364000, "Hpt_PlasmaShockCannon_Turret_Small", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  2.0), Map.entry(HorizonsModifier.INTEGRITY,  40.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.54), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  44.7), Map.entry(HorizonsModifier.DAMAGE,  4.47), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.21), Map.entry(HorizonsModifier.THERMAL_LOAD,  0.69), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  25.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  3.1), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.80), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_2_D_F = new ShockCannon("SHOCK_CANNON_2_D_F", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_2, ModuleClass.D, false, Mounting.FIXED, 367500, "Hpt_PlasmaShockCannon_Fixed_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.57), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  129.6), Map.entry(HorizonsModifier.DAMAGE,  12.96), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.47), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.8), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  40.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  9.1), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.60), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_2_D_G = new ShockCannon("SHOCK_CANNON_2_D_G", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_2, ModuleClass.D, false, Mounting.GIMBALLED, 565200, "Hpt_PlasmaShockCannon_Gimbal_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.61), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  102.1), Map.entry(HorizonsModifier.DAMAGE,  10.21), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.58), Map.entry(HorizonsModifier.THERMAL_LOAD,  2.1), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  40.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  7.1), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.80), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_2_E_T = new ShockCannon("SHOCK_CANNON_2_E_T", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_2, ModuleClass.E, true, Mounting.TURRETED, 1359200, "Hpt_PlasmaShockCannon_Turret_Medium", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  4.0), Map.entry(HorizonsModifier.INTEGRITY,  51.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.5), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  89.6), Map.entry(HorizonsModifier.DAMAGE,  8.96), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.39), Map.entry(HorizonsModifier.THERMAL_LOAD,  1.24), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  40.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  6.3), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.80), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_3_C_F = new ShockCannon("SHOCK_CANNON_3_C_F", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.FIXED, 1015750, "Hpt_PlasmaShockCannon_Fixed_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.89), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  181.4), Map.entry(HorizonsModifier.DAMAGE,  18.14), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.92), Map.entry(HorizonsModifier.THERMAL_LOAD,  2.66), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  12.7), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.60), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_3_C_G = new ShockCannon("SHOCK_CANNON_3_C_G", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_3, ModuleClass.C, false, Mounting.GIMBALLED, 2249050, "Hpt_PlasmaShockCannon_Gimbal_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.89), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  148.7), Map.entry(HorizonsModifier.DAMAGE,  14.87), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  1.07), Map.entry(HorizonsModifier.THERMAL_LOAD,  3.12), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  10.4), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.80), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final ShockCannon SHOCK_CANNON_3_D_T = new ShockCannon("SHOCK_CANNON_3_D_T", HorizonsBlueprintName.SHOCK_CANNON, ModuleSize.SIZE_3, ModuleClass.D, true, Mounting.TURRETED, 6050200, "Hpt_PlasmaShockCannon_Turret_Large", Map.ofEntries(Map.entry(HorizonsModifier.MASS,  8.0), Map.entry(HorizonsModifier.INTEGRITY,  64.0), Map.entry(HorizonsModifier.POWER_DRAW,  0.64), Map.entry(HorizonsModifier.BOOT_TIME,  0.0), Map.entry(HorizonsModifier.DAMAGE_PER_SECOND,  122.6), Map.entry(HorizonsModifier.DAMAGE,  12.26), Map.entry(HorizonsModifier.DISTRIBUTOR_DRAW,  0.79), Map.entry(HorizonsModifier.THERMAL_LOAD,  2.2), Map.entry(HorizonsModifier.ARMOUR_PIERCING,  60.0), Map.entry(HorizonsModifier.MAXIMUM_RANGE,  3000.0), Map.entry(HorizonsModifier.SHOT_SPEED,  1200.0), Map.entry(HorizonsModifier.RATE_OF_FIRE,  10.0), Map.entry(HorizonsModifier.BURST_INTERVAL,  0.1), Map.entry(HorizonsModifier.AMMO_CLIP_SIZE,  16.0), Map.entry(HorizonsModifier.AMMO_MAXIMUM,  240.0), Map.entry(HorizonsModifier.RELOAD_TIME,  6.0), Map.entry(HorizonsModifier.BREACH_DAMAGE,  8.6), Map.entry(HorizonsModifier.MIN_BREACH_CHANCE,  0.40), Map.entry(HorizonsModifier.MAX_BREACH_CHANCE,  0.80), Map.entry(HorizonsModifier.KINETIC_DAMAGE_RATIO,  1.0), Map.entry(HorizonsModifier.DAMAGE_FALLOFF_START,  2500.0), Map.entry(HorizonsModifier.AMMO_COST,  9.0)));
    public static final List<ShockCannon> SHOCK_CANNONS = List.of(
            SHOCK_CANNON_1_D_F,
            SHOCK_CANNON_1_E_G,
            SHOCK_CANNON_1_F_T,
            SHOCK_CANNON_2_D_F,
            SHOCK_CANNON_2_D_G,
            SHOCK_CANNON_2_E_T,
            SHOCK_CANNON_3_C_F,
            SHOCK_CANNON_3_C_G,
            SHOCK_CANNON_3_D_T
    );
    public ShockCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public ShockCannon(String id, HorizonsBlueprintName name, ModuleSize moduleSize, ModuleClass moduleClass, Origin origin, boolean multiCrew, Mounting mounting, int basePrice, String internalName, Map<HorizonsModifier, Object> attributes) {
        super(id, name, moduleSize, moduleClass, origin, multiCrew, mounting, basePrice, internalName, attributes);
    }

    public ShockCannon(ShockCannon shockCannon) {
        super(shockCannon);
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedBlueprints() {
        return Collections.emptyList();
    }

    @Override
    public List<HorizonsBlueprintType> getAllowedExperimentalEffects() {
        return Collections.emptyList();
    }

    @Override
    public ShockCannon Clone() {
        return new ShockCannon(this);
    }
}
