package nl.jixxed.eliteodysseymaterials.enums;

import nl.jixxed.eliteodysseymaterials.service.LocaleService;

public enum ColonisationLayout {

    NO_TRUSS,
    DUAL_TRUSS,
    QUAD_TRUSS,
    ASTEROID,
    OCELLUS,
    APOLLO,
    ARTEMIS,
    PLUTUS,
    VULCAN,
    DYSNOMIA,
    VESTA,
    PROMETHEUS,
    NEMESIS,
    HERMES,
    ANGELIA,
    EIRENE,
    PISTIS,
    SOTER,
    ALETHEIA,
    DEMETER,
    APATE,
    LAVERNA,
    EUTHENIA,
    PHORCYS,
    ENODIA,
    ICHNAEA,
    VACUNA,
    ALASTOR,
    DICAEOSYNE,
    POENA,
    EUNOMIA,
    NOMOS,
    HARMONIA,
    ASCLEPIUS,
    EUPRAXIA,
    ASTRAEUS,
    COEUS,
    DODONA,
    DIONE,
    HEDONE,
    OPORA,
    PASITHEA,
    DIONYSUS,
    BACCHUS,
    HESTIA,
    DECIMA,
    ATROPOS,
    NONA,
    LACHESIS,
    CLOTHO,
    HEPHAESTUS,
    OPIS,
    PONOS,
    TETHYS,
    BIA,
    MEFITIS,
    NECESSITAS,
    ANANKE,
    FAUNA,
    PROVIDENTIA,
    ANTEVORTA,
    PORRIMA,
    ZEUS,
    HERA,
    POSEIDON,
    APHRODITE,
    CONSUS,
    PICUMNUS,
    ANNONA,
    CERES,
    FORNAX,
    OUREA,
    MANTUS,
    ORCUS,
    EREBUS,
    AERECURA,
    FONTUS,
    METEOPE,
    PALICI,
    MINTHE,
    GAEA,
    IOKE,
    BELLONA,
    ENYO,
    POLEMOS,
    MINERVA,
    PHEOBE,
    ASTERIA,
    CAERUS,
    CHRONOS,
    AERGIA,
    COMOS,
    GELOS,
    FUFLUNS,
    TARTARUS,
    AEGLE,
    TELLUS,
    IO,
    ATHENA,
    CAELUS,
    ALALA,
    ARES,
    SILENUS,
    JANUS,
    MOLAE,
    //    TELLUS,duplicate???
    EUNOSTUS;

    public String getLocalizationKey() {
        return "colonisation.layout." + this.name().toLowerCase();
    }

    @Override
    public String toString() {
        return LocaleService.getLocalizedStringForCurrentLocale(getLocalizationKey());
    }

}
