package nl.jixxed.eliteodysseymaterials.enums;

public enum Data implements Material {
    ACCIDENTLOGS,
    AIRQUALITYREPORTS,
    ATMOSPHERICDATA,
    AUDIOLOGS,
    AXCOMBATLOGS,
    BALLISTICSDATA,
    BIOLOGICALWEAPONDATA,
    BIOMETRICDATA,
    BLACKLISTDATA,
    BLOODTESTRESULTS,
    CAMPAIGNPLANS,
    CATMEDIA,
    CENSUSDATA,
    CHEMICALEXPERIMENTDATA,
    CHEMICALFORMULAE,
    CHEMICALINVENTORY,
    CHEMICALPATENTS,
    CHEMICALWEAPONDATA,
    CLASSICENTERTAINMENT,
    COCKTAILRECIPES,
    COMBATANTPERFORMANCE,
    COMBATTRAININGMATERIAL,
    CONFLICTHISTORY,
    CRIMINALRECORDS,
    CROPYIELDANALYSIS,
    CULINARYRECIPES,
    DIGITALDESIGNS,
    DUTYROTA,
    EMPLOYEEDIRECTORY,
    EMPLOYEEEXPENSES,
    EMPLOYEEGENETICDATA,
    EMPLOYMENTHISTORY,
    ENHANCEDINTERROGATIONRECORDINGS,
    ESPIONAGEMATERIAL,
    EVACUATIONPROTOCOLS,
    EXPLORATIONJOURNALS,
    EXTRACTIONYIELDDATA,
    FACTIONASSOCIATES,
    FACTIONDONATORLIST,
    FACTIONNEWS,
    FINANCIALPROJECTIONS,
    FLEETREGISTRY,
    GENESEQUENCINGDATA,
    GENETICRESEARCH,
    GEOLOGICALDATA,
    HYDROPONICDATA,
    INCIDENTLOGS,
    INFLUENCEPROJECTIONS,
    INTERNALCORRESPONDENCE,
    INTERROGATIONRECORDINGS,
    INTERVIEWRECORDINGS,
    JOBAPPLICATIONS,
    KOMPROMAT,
    LITERARYFICTION,
    MAINTENANCELOGS,
    MANUFACTURINGINSTRUCTIONS,
    MEDICALRECORDS,
    MEDICALTRIALRECORDS,
    MEETINGMINUTES,
    MINERALSURVEY,
    MININGANALYTICS,
    MULTIMEDIAENTERTAINMENT,
    NETWORKACCESSHISTORY,
    NETWORKSECURITYPROTOCOLS,
    NEXTOFKINRECORDS,
    NOCDATA,
    OPERATIONALMANUAL,
    OPINIONPOLLS,
    PATIENTHISTORY,
    PATROLROUTES,
    PAYROLLINFORMATION,
    PERSONALLOGS,
    PHARMACEUTICALPATENTS,
    PHOTOALBUMS,
    PLANTGROWTHCHARTS,
    POLITICALAFFILIATIONS,
    PRISONERLOGS,
    PRODUCTIONREPORTS,
    PRODUCTIONSCHEDULE,
    PROPAGANDA,
    PURCHASERECORDS,
    PURCHASEREQUESTS,
    RADIOACTIVITYDATA,
    REACTOROUTPUTREVIEW,
    RECYCLINGLOGS,
    RESIDENTIALDIRECTORY,
    RISKASSESSMENTS,
    SALESRECORDS,
    SECURITYEXPENSES,
    SEEDGENEAOLOGY,
    SETTLEMENTASSAULTPLANS,
    SETTLEMENTDEFENCEPLANS,
    SHAREHOLDERINFORMATION,
    SLUSHFUNDLOGS,
    SMEARCAMPAIGNPLANS,
    SPECTRALANALYSISDATA,
    SPYWARE,
    STELLARACTIVITYLOGS,
    SURVEILLEANCELOGS,
    TACTICALPLANS,
    TAXRECORDS,
    TOPOGRAPHICALSURVEYS,
    TRAVELPERMITS,
    TROOPDEPLOYMENTRECORDS,
    UNIONMEMBERSHIP,
    VACCINATIONRECORDS,
    VACCINERESEARCH,
    VIPSECURITYDETAIL,
    VIROLOGYDATA,
    VIRUS,
    VISITORREGISTER,
    WEAPONINVENTORY,
    WEAPONTESTDATA,
    XENODEFENCEPROTOCOLS,
    UNKNOWN;

    public static Data forName(final String name) {
        try {
            return Data.valueOf(name.toUpperCase());
        } catch (final IllegalArgumentException ex) {
            return Data.UNKNOWN;
        }
    }

    @Override
    public StorageType getStorageType() {
        return StorageType.DATA;
    }


    @Override
    public String getLocalizationKey() {
        return "material.data." + this.toString().toLowerCase();
    }

    @Override
    public boolean isUnknown() {
        return this == Data.UNKNOWN;
    }
}
