name: Validate Localization

on:
  workflow_dispatch:
#  workflow_run:
#    workflows:
#      - Download from Crowdin
#    types:
#      - completed
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDKS
        uses: actions/setup-java@v4.2.1
        with:
          java-version: |
            23.0.1
            21.0.1
          distribution: 'zulu'
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run LocalizationCheckTest
        run: ./gradlew application:test --tests nl.jixxed.eliteodysseymaterials.LocalizationCheckTest