name: Validate Localization

on:
  workflow_dispatch:
#  workflow_run:
#    workflows:
#      - Download from Crowdin
#    types:
#      - completed

env:
  JAVA_VERSION: 25.0.2

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Zulu (without CRaC)
        id: download_zulu
        shell: bash
        run: |
          cd $RUNNER_TEMP
          jdk_archive_filename=$(curl -LOs -w '%{filename_effective}' "$(curl -s -X GET 'https://api.azul.com/metadata/v1/zulu/packages/?os=windows&arch=x64&archive_type=zip&java_package_type=jdk&javafx_bundled=false&crac_supported=false&release_status=ga&availability_types=CA&certifications=tck' --data-urlencode "java_version=$JAVA_VERSION" -H  'accept: application/json' | jq -r '.[0].download_url')")
          echo "jdk_archive_filename=$jdk_archive_filename" >> $GITHUB_OUTPUT
      - name: Set up JDKS
        uses: actions/setup-java@v5
        with:
          java-version: |
            ${{ env.JAVA_VERSION }}
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/${{ steps.download_zulu.outputs.jdk_archive_filename }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      #      - name: Setup Gradle
      #        uses: gradle/actions/setup-gradle@v3

      - name: Run LocalizationCheckTest
        run: ./gradlew application:test --tests nl.jixxed.eliteodysseymaterials.LocalizationCheckTest